### PR TITLE
[Cargo + RnD] Autolathe Buff

### PR DESCRIPTION
**Pull request by Swagile**
~ Adds new ammo types to autolathe that are exclusively to summon guns and admin events.
~ Boosts RnD due to combat tech levels being in ammo.
~ Possible addition to a future cargo update I am planning; this is just prep. No, I am not adding SAW's to cargo.

Some of the ammo comes in "magazines" instead of actual ammo boxes but that is just how ammo works from the code ive looked at while doing this. This is a simple change code wise, but gameplay wise it changes up RnD a lot since speed running combat tech is now easier and it allows you to print ammo for most summon guns weapons. 

This further increases the chaos of summon gun wizard rounds as everyone with a ballistic makes a mad dash for cargo. This is also a prep for a future update ive been thinking of to cargo that adds extremely expensive crates in the 500 + point margin (suggestion on forums made by another user) but in return you get special crates like nanotrasen assault rifle crates. This is in the future, however, and hinges partly on this pull request being accepted.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
40mm HE grenades?

Time for blastco ops to bumrush cargo every round. Who needs a nuke when you can erase the station manually?

**Comment by Swagile** [comment]
Added due to the fact that the carbine that spawns in summon guns has a underbelly grenade launcher with one grenade already in it.

Yes its op, but so is gyrojet and summon guns wasn't meant to be balanced anyway. The blastco thing is a concern, though most crew defend cargo like its their mother. If its too OP for head admin tastes, I can remove it.

**Comment by GuyonBroadway** [comment]
Actually I like the idea of Nukeops taking over areas of the station to prep for an assault. Could make for some interesting gameplay.... or just make it easy for nukeops to literally level the station.

**Comment by ArcLumin** [comment]
I'm for this, if only for the selfish reason to not require combat shotties anymore to do my RnD

**Comment by ArcLumin** [comment]
Wait, lame. I thought when you said "made it easier for rnd" you meant combat 5 level ammo or greater. This certainly does not help rnd then, as there's far easier ways to get combat that high

**Comment by Swagile** [comment]
From what I checked, there isn't a combat origins 5 ammo box so *shrug.

I could tweak one of the higher level ammo types in the code and make it origins 5, but thats up to head admins since it would make getting combat 6 easier since you wouldn't need a combat shotgun anymore.

**Comment by GuyonBroadway** [comment]
The things that are gated by weapons 6 are actually fairly powerful. If I was to suggest adding it then at least make the thing with weapons 5 require diamond or something so you need something from out of the lab to get it.

**Comment by LuisReyesX** [comment]
I can sort of understand the autolathe making incendiary slugs, but seriously? Grenades?. how it is possible for grenades to be made with just a bit of metal and from a simple machine that spawns at roundstart. IIRC grenade launcers are only used in nukies so thats basically just a slight crew/nukies buff

**Comment by Swagile** [comment]
Please read the full PR before posting.

As the PR states, this is more Summon Guns oriented, and is a preparation for a cargo update I am thinking of doing. No, not all ammo types will be used, but some will in the update. This was also a suggestion by another user.

Like stated before, nukies and crew that steal nuke gear might get a buff,  but besides that this is just for if you get a gun summoned and you need more ammo for it. Or if a admin allows you to trade all your TC for shit.

**Comment by McBawbaggings** [comment]
Nah. Summon guns on wizman rounds always end in bloodshed. I don't want to encourage easier murderboning with stronger cunts

**Comment by Kierany9** [comment]
swagile
wat are you doing?
**swagile**
**stahp**

>Actually I like the idea of Nukeops taking over areas of the station to prep for an assault. Could make for some interesting gameplay.... or just make it easy for nukeops to literally level the station.

Nukies can already do this, the autolathe prints out spare ammo for all of the main weapons: C20, C90, SAW and Bulldog.

**Comment by Swagile** [comment]
Im thinking of toning this down a lot more to keep certain ammo types that are used by Nanotrasen ballistics like the NT Assault rifle so that it coincides with my cargo update while removing the OP ammo types like grenades and SAW rounds. That is if the bulk of this PR doesn't go through.

The update would include higher tier crates at 250 (ballistic pistols), 350 (ballistic revolvers), and 500 (ballistic assault rifles) respectively for each crate and only what Nanotrasen uses. Gives incentive for cargo to work together and gives them a late game instead of just getting the usual combat shotgun / egun crate spam.

Thoughts?

**Comment by Kierany9** [comment]
>implying revolver crate spam will be any less cancer than shotgun crate spam

Real talk, why are features that could easily be added in their proper PR being added separately

**Comment by Hackole** [comment]
Heck no, summon guns weapons should remain limited in ammo. This would make for terrible balance

**Comment by Swagile** [comment]
Because from my understanding of the coder standards, you have to make separate PR's for separate features. Unless I read that wrong?

**Comment by Kierany9** [comment]
Yes, but the "cargo ammo" and future "cargo guns" PRs are obviously two parts of a whole though.

**Comment by Swagile** [comment]
In hindsight, after talking to Kier, I realize that my update (both this and the future one I was thinking of) would add a lot of balancing issues. Ill think of better crates to add instead of weapons for cargo.

**Pull request closed without merging**
