### PR TITLE
Syndicate Bundle Overhaul 2 - Snake's Revenge

### PR DESCRIPTION
**Pull request by Kierany9**
[Original PR that I closed because merge conflicts and other issues(had 4 head approvals)](https://github.com/HippieStationCode/HippieStation13/pull/2233)

So let's get this shit in without merge conflicts this time. The only differences are that this increases the ammount of Throwing Stars in the box from 5 to 7 because they're never used and also adds Caltrops, which were supposed to be added before the previous PR as a normal and bundle traitor item but they're currently only in the bundle due to balancing concerns. A box of five of these are in the ninja bundle, and running over them deals 10 brute and 8 stamina damage. They deal 5 brute when attacked with and when thrown, they have a 35% chance to embed and when run over they have a 70% chance to embed in either leg. Anyway, here's a picture and enjoy the copypaste of the previous PR's description.

There's also a plasma syringe in here. Added it for stuff and then removed said stuff but this might be useful for the future.

woo

sprites

**_Thanks to CrystalWarrior for the caltrop sprites_**

Syndicate Bundles, a traitor item that selects a bunch of items specialized items worth just over 20 TC, have been rather bad for a long time, often discarded for the far superior Syndicate Crate, which would grant you 50 TC worth of random items. Combine this with balancing changes which reduced the TC cost of a lot of utility items that came with the bundles and you have a recipe for a shitty item that may not even give you your money's worth. No more! Syndicate bundles have been reworked, many of which carry many unique items and allowing for more gimmicky but nonetheless powerful playstyles.

this stuff may need nerfing or other balancing please tell me if it does

**Spy Bundle:**
- 4x DNA Randomizers
- 3x Agent ID Cards
- 3x Syndicate Encryption Keys
- 2x Greater Mindslave Implants
- Syndicate Surgery Dufflebag
- Energy Dagger

The Spy Bundle is focused on obtaining a small gang of henchmen to help you complete your objectives. While you have plenty of items to help team communication, you get nothing to arm them or to help you capture them, only a mere edagger to defend yourself with. Resourcefullness is the key to getting the most out of this kit.

**Snake Bundle:**
- Sketchin Pistol (w/ Supressor and spare mag)
- Combat Knife
- CQC Gloves
- Dart Gun
- 5x Bioterror Syringes
- 2x C4
- Agent ID Card
- Syndicate Cigarretes

Fufill your fantasies of becoming Big Boss today with the Snake Bundle. This bundle is perfectly equipped for 1v1 combat and is geared at fighting and infiltrating Security/Command rather than murderboning civilians.

**Operative Bundle:**
- Blood Red Hardsuit
- Sketchin Pistol (w/ 3 spare mags)
- Syndicate Minibomb
- Detomatrix Cartrige
- Syndicate Encryption Key
- Powersink Beacon
- Singularity Beacon
- Syndicate Bomb Beacon

This bundle is for amaeteur Nuke Ops who want to spread panic throughout the station. And that's it really.

**Matrix Bundle:**
- Revolver (w/ spare mag)
- 2x Sketchin Pistol (w/ 8 spare mags)
- 3x C4
- Leather Overcoat
- Sunglasses

The Matrix Bundle offers one way to complete your objectives and one way only. That way involves explosions, gunshots and trenchcoats galore. Dual wield your Sketchins for ultimate badassery.

**Implant Bundle:**
- Freedom Implant
- Adrenal Implant
- Storage Implant
- EMP Implant
- Macrobomb Implant
- Mindslave Implant

Possibly one of the strongest bundles in the game, simply because of fuckton of implants you have including mindslave and **macrobomb**.

**Hacker Bundle:**

- Hacked AI Law Module
- Agent ID Card
- Chameleon Jumpsuit
- Armoured Labcoat
- Binary Encryption Key
- Syndicate Encryption Key
- Emag
- AI Detector
- Camera Bug
- AI Toy (Disguised Law Module)
- C4

The Hacker Bundle now actually works like a hacker's bundle. Subverting the AI is nolonger his only trick, he now has a chameleon jumpsuit and armoured labcoat, allowing him to sabotage tcomms with potent scripts or steal prototype weapons from RnD(before wiping the servers like a jackass).

**Dark Lord Bundle:**
- 2x Energy Sword
- Summon Item Spellbook
- Adrenal Implant
- Telekineses SE Injector
- Mindslave Implant
- Agent ID Card
- Dark Lord Robes

The Dark Lord Implant has received minor buffs with a mindslave implant(to turn people to the dark side of course), adrenals for stun resistance and the Summon Item spellbook to recover the double esword incase you somehow manage to lose it.

**Ninja Bundle:**
- Energy Sword
- Cloak of Darkness SE Injector
- Throwing Star Belt
- 2x Throwing Star Boxes
- Pickpocket Gloves
- Smoke Spellbook
- 2x Airlock Charge
- Caltrop Box
- Balaclava

While somewhat similar to the Dark Lord, the Ninja Bundle is more focused on maintinence prowling and otherwise staying out of sight, keeping pursuers at bay with smokescreens and an abundance of throwing stars.

**Explosives Bundle:**
- 20x C4
- 4x Syndicate Minibombs
- Syndicate Bomb

BOOM BOOM BOOM BABY!

### CODE REVIEW

**Comment by McBawbaggings** [comment]
Might want to update the PR to say the syndie ID no longer has tcomms and RnD.
+1 for the sunglasses addition

**Comment by Limed00d** [comment]
Matrix bundle seema kinda weak imo.

**Comment by Mithrandalf** [comment]
I agree the matrix bundle kinda sucks.

You should throw a sepia slime core or two in there.

**Comment by Kierany9** [comment]
>You should throw a sepia slime core or two in there.

Done

**Comment by Gandalf2k15** [comment]
Why is this not in yet!!!

**Comment by Kierany9** [comment]
Reverted sepia slime cores after some thought:

1. They were finicky to use in the heat of battle, especially when dual-wielding.
1. They would trivialize the "Steal a used slime extract" objective.
1. They lasted 14 seconds which was way too long.
1. And most importantly, they went against the spirit of the bundle which is to go all-in guns blazing. Timestop is an almost-exclusively defensive spell, allowing very easy escapes.

While points 1 through 3 could be fixed by creating a variant of the wizard's spell or a grenade, point 4 still stands. The matrix bundle may be a tad weaker than the others but a trip to the autolathe and some creative use of on-station items will make all your problems go away.

**Comment by Kokojos** [comment]
I find this a nice addition and the code works.

**Comment by Nebyab** [comment]
ok

**Comment by Kokojos** [comment]
2 heads approved

**Pull request merged**
