### PR TITLE
Random Event Tweaks

### PR DESCRIPTION
**Pull request by yobob591**
- tweak: "Event times changed from every 3 to 7 minutes instead of 3 to 10"
- tweak: "Greatly lowered the weight of the clogged vents event, hopefully we will see more variation now"
- tweak: "Tweaked a couple modes minimum times from over 1 hour to allow them to reasonably happen, hopefully this means SPACE NINJAS"

### CODE REVIEW

**Comment by ArcLumin** [comment]
I like dis

**Comment by KittyKathy** [comment]
Yes more space ninja I love playing as a space ninja running around invisible beheading people also did we forget to remove space ninja antistuns?...I think we did uh oh probably does not matter anyway they can just phase jaunt away while stunned.
Now maybe we can actually see a meteor hit the station with the stand arrow without it being a blue moon.
Are you telling me we have a blob random even and all those times i saw it, I was wrong to think it was adminbus?

**Comment by yobob591** [comment]
blob only happened after 1 hour and 20 minutes so probably not, Ive never seen a round that long

**Comment by KittyKathy** [comment]
I have on low pop that is when everyone is too lazy or dead to call the shuttle.

**Comment by gumner** [comment]
please anything for blob +69

**Comment by McBawbaggings** [comment]
Clogged events happening less often is fine.
Making events more common isn't.
Making blob appear at 30 minutes is retarded.

**Comment by ArcLumin** [comment]
Code's good

**Comment by yobob591** [comment]
Mcbaw making events more common is half of this PR, I can adjust the time though, and if enough people don't want more events I can remove it. Also what should blob spawn at, 40 mins? I chose 30 cause the station isn't fucked to the point where it can't fight it or would rather leave.

**Comment by yobob591** [comment]
The reason blob was removed from rotation was because 2 blobs was too many, the crew almost always killed one but by then the other had grown too much

**Comment by blobbernaut** [comment]
das mee!!!! +1

**Comment by yobob591** [comment]
Also mcbaw would adjusting the weight be better than adjusting the frequency

**Comment by yobob591** [comment]
I think so

**Comment by McBawbaggings** [comment]
Actually the only part of this PR I agree with is making clogged vents less common.

This PR is gonna fuck up antagonist rounds really hard way too often and I don't support it.

**Comment by yobob591** [comment]
How though, events are so goddamn rare atm you might as well not have them, especially shit like space ninja or blob, I haven't seen a meteor storm in months and I've never seen a space ninja ever

**Comment by blobbernaut** [comment]
same

**Comment by banthebantz** [comment]
same

**Comment by blobbernaut** [comment]
as long as they're rare and not happening very often, they're not gonna fuck antgonist rounds "very often". They'll make them feel more varied.

**Comment by McBawbaggings** [comment]
I saw meteors a week ago and it gave at least 5 stand arrows.

**Comment by banthebantz** [comment]
Then change the stand arrow spawn chance lol

**Comment by blobbernaut** [comment]
just add a check for when the stand arrow spawns, if there are any other stand arrows in the world then it does not spawn.

**Comment by yobob591** [comment]
That's a different issue mcbaw it's not supposed to do that, in fact the stand arrow meteor could only spawn in catastrophic storms instead

**Comment by Pyko1** [comment]
Should prolly go over all the random shit and rebalance the chance around 100% so its easier to read.

**Comment by Pyko1** [comment]
and yeah blob is a "round ender" mode might want to keep it over a hour at least.

**Comment by yobob591** [comment]
Blob is hardly a round ender imo but ok I don't really mind making that an hour

**Comment by Pyko1** [comment]
it is, since retards always charge in with plasma canisters and shit to make it easier for blob while killing half of the people fighting against it.

**Comment by GuyonBroadway** [comment]
Make it clear that charging in with plasma A: doesn't work and B : will get you fucking banned. 

Same goes for bombs, welder or otherwise.

**Comment by yobob591** [comment]
Thing is we do do that and tards do it anyways

**Comment by blobbernaut** [comment]
make blob core vulnerable to explosions again please

**Comment by blobbernaut** [comment]
then re add it

**Comment by yobob591** [comment]
Bombing blob is bad pls it kills allies

**Comment by blobbernaut** [comment]
sometimes bombing the blob is the only thing that can be done

**Comment by yobob591** [comment]
I might rebalance blob in another PR but this is mainly about events

**Comment by yobob591** [comment]
@McBawbaggings stando arrows only spawn in catastrophic storms and blob is up to 1 hour again

**Comment by yobob591** [comment]
is this better

**Comment by blobbernaut** [comment]
make blob like, 45 minutes

**Comment by yobob591** [comment]
thats up to mcbaw and other heads

**Comment by blobbernaut** [comment]
no it's up to you and then they just approve it

**Comment by yobob591** [comment]
so then its up to them, if i set it to 45 and they dont like then I have to change it

**Comment by blobbernaut** [comment]
yeah but 45 is better so try that first

**Comment by yobob591** [comment]
did it

**Comment by McBawbaggings** [comment]
Also ninjas are fucking horrible and terribly coded and shit. The less I see them, the better.
Otherwise, I guess we can try it out?

**Comment by yobob591** [comment]
I can move ninjas back to 1 hour then

**Comment by SpankMasterson** [comment]
+1

**Comment by yobob591** [comment]
I think this is ready to merge, confirm mcbaw???

**Comment by McBawbaggings** [comment]
Eh, okay +1.

**Comment by Swagile** [comment]
this will give rnd science a reason to exist (xray guns) besides a durand murdering someone once in a while

pls

**Comment by yobob591** [comment]
this is ready to merge

**Comment by ArcLumin** [comment]
Foook yeah mergan

**Pull request merged**
