### PR TITLE
Catbeasts now spawn with crippling disabilities

### PR DESCRIPTION
**Pull request by Spacedong**
Catbeasts now start with epilepsy, stupidity, coughing, and tourettes in addition to clumsiness.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Code looks good

**Comment by trifornt-tinfornt** [comment]
So what's the point of cluwnebans then?

**Comment by Nebyab** [comment]
cluwnebans are retarded and bad anyway

**Comment by Spacedong** [comment]
@nebyab is that a +1

**Comment by trifornt-tinfornt** [comment]
I'd give it a +1.

**Comment by dreamcrab** [comment]
no coughing please

dont give everyone cat aids

**Comment by Spacedong** [comment]
its the coughing disability not the coughing disease @dreamcrab

**Comment by Spacedong** [comment]
now +1 it and merge so we can fuck over cats once and for all

**Comment by dreamcrab** [comment]
OKAY WELL THE TITLE SAYS DISEASE OK

**Comment by Spacedong** [comment]
fixed bitch!!

**Comment by GeneralGoose** [comment]
now genetiists can hunt furries to unccover 5 disabilities

**Comment by Spacedong** [comment]
@generalgoose good, furry hunting is encouraged

**Comment by Hackole** [comment]
eugh, idk about this. Half the fun of cats was that they were actually capable of dunking on you and running. Also, this would fuck traitor cats which were hilarious

**Comment by Spacedong** [comment]
powergaming cats are cancer, it is and always will be a punishment race, no fun allowed

**Comment by Hackole** [comment]
If you wanted a punishment race with disabilities we have cluwnes now, though

**Comment by Spacedong** [comment]
as nebyab said, cluwnes are fucking terrible, and cats are kinda the punishment race everybody is used to, so lets make them worse and even more hilarious

**Comment by Hackole** [comment]
I just don't see a point to this, they already do have a crippling impediment in that everybody tries to murder them

**Comment by Spacedong** [comment]
but now its even more funny and hilarious

**Comment by Hackole** [comment]
tbh the funny part was them running down the halls being chased, with this they'll just have a seizure and get dunked immediately

**Comment by Spacedong** [comment]
idk I think it'd be more funnier with them shouting SHIT and FUCK while falling over every 5 seconds and catastrophically failing at everything

**Comment by Hackole** [comment]
thats what cluwnes do down to a dot though aaaaaa

**Comment by Spacedong** [comment]
no

**Comment by Mithrandalf** [comment]
Yeah this is shit. Literally cluwnes.

What's up with all these cat nerfs? Someone been getting dunked recently?

**Comment by Spacedong** [comment]
catbeasts have needed to die for a while and im finally carrying it out

**Comment by McBawbaggings** [comment]
Tourettes is overkill IMO because the 10 tick stun is awful.
Everything else is solid though.

**Comment by Voratius** [comment]
yeah sure sounds neat

**Comment by blobbernaut** [comment]
bad i disagree with this there's no point, hunting a prey that can't even run away isn't very fun or hilarious.

**Comment by dreamcrab** [comment]
yeah, i like making them retarded and stuff but making it too easy to kill them ruins the hunt

**Comment by dreamcrab** [comment]
does the dna sting that makes people into other people give people disabilities too?

cause this is a huge buff for ling if so

**Comment by McBawbaggings** [comment]
I think it would.
Having a station of screaming cats is funny though.

**Comment by Spacedong** [comment]
@dreamcrab @mcbawbaggings +1 or -1 already come the fuck on

**Comment by McBawbaggings** [comment]
"Tourettes is overkill IMO because the 10 tick stun is awful.
Everything else is solid though."

That was a conditional +1.
The condition is met so it is +1.

**Comment by Spacedong** [comment]
ok lets merge

**Comment by Gandalf2k15** [comment]
no why make cats even crappier.

**Comment by GeneralGoose** [comment]
dog bless this pear

**Comment by Spacedong** [comment]
cats must be crappier, no fun allowed for a punishment race

**Comment by GeneralGoose** [comment]
all the haters of this pear are sekretly furries

**Comment by Gandalf2k15** [comment]
i need something to piss people off when I do adminbus dont make me use birds

**Comment by Badmex** [comment]
Cats should also no longer get antag under any condition.

**Comment by Mithrandalf** [comment]
I dont see the purpose of this. We already have cluwnes.

**Comment by Spacedong** [comment]
cluwnes are useless

**Comment by Spacedong** [comment]
@generalgoose ur old avatar pic was funnier

**Comment by Pyko1** [comment]
No thanks please, hunting cats is fun, this will just make it retardedly easy.

**Comment by Spacedong** [comment]
cats should not be allowed to live, fuck off

**Comment by Pyko1** [comment]
Agreed, but its pointless to hunt them if they are almost dying on their own, and stumbling  after every 3 steps.

**Comment by Mithrandalf** [comment]
Yes cluwnes are useless. That's the point. Let's not make cats just another species of cluwne.

**Comment by Pyko1** [comment]
not to mention its going to be a huge stealth buff to changeling transformative sting.

**Comment by dreamcrab** [comment]
**let it be known that i stated this was a stealth buff to lings before i +1 this and i also brought up the potential for griefing with genetics**

OH WELL HERE WE GO +777777777777777777777777777777777777

**Comment by GeneralGoose** [comment]
fyi kluwns are robust

**Comment by calibraptor** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES
YEEEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeEeES

Yes.

+1/3

**Comment by calibraptor** [comment]
Oh shit this already has everything it needs actually.

Merge it

**Comment by GeneralGoose** [comment]
gas the kats merge war now

**Comment by Gandalf2k15** [comment]
All merge conditions met, merging.

**Pull request merged**
