### PR TITLE
Added catwalks to the station

### PR DESCRIPTION
**Pull request by Spacedong**
adds catwalks around the station (excluding the shuttle/white ship areas because fuck I have no idea how to map around those) 

http://vgy.me/I91EzO.png

### CODE REVIEW

**Comment by Cherkir** [comment]
+1

**Comment by ArcLumin** [comment]
Useful for a nice safety net if you space yourself

**Comment by Pyko1** [comment]
You did leave holes for the massdrivers, right?

**Comment by XeonFaux** [comment]
Why are catwalks not attached by lattices to the station?

**Comment by Spacedong** [comment]
yes I did leave holes for mass drivers @xeonfaux I'm dumb and chose the one preview where I didn't include the lattices, its now fixed

**Comment by Pyko1** [comment]
Included the catwalks from this in my PR as these are going to conflict with each other.

**Comment by Nokington** [comment]
I'd rather merge Pyko's PR since it adds a lot more plus this.

**Comment by Pyko1** [comment]
Should probably be closed as the catwalks and much more are already in.

**Pull request closed without merging**
