### PR TITLE
Dominator area fix

### PR DESCRIPTION
**Pull request by Spacedong**
Fixes issue #2606 where a dominator could be placed in a bluespace shelter/another area in space.

### CODE REVIEW

**Comment by McBawbaggings** [comment]
Tested this,
Only works on the station in the predefined areas.
It doesn't matter what the name of the place is.
No more building extensions or new things of station for ez control.
Renaming it to a onstation area doesn't matter.
Renaming an onstation place to something random doesn't stop you from controlling there.

This is how gangs SHOULD play IMO.
+1

**Comment by McBawbaggings** [comment]
Oh yeah, changelog please for the gameplay changes.

**Comment by Nebyab** [comment]
ok, this is a bugfix though clearly?

I doubt it was the intent to allow people to cheese shit like the way you could

**Comment by Spacedong** [comment]
oversight/bug, whatever the case, this should be merged to stop this cheese bullshit from ever happening

**Comment by ArcLumin** [comment]
This looks good, I'm all for it. After I found the bug/issue, others started trying it, so no doubt this'll be an issue unless it's  patched.

**Comment by TDcoolguy300** [comment]
This is an issue, as being able to place a dominator in a non-station area is not good.

**Pull request merged**
