### PR TITLE
Kitchen Conveyor

### PR DESCRIPTION
**Pull request by Pyko1**
capture
Moved things around quite a bit around Kitchen/bar.

### CODE REVIEW

**Comment by Carbonhell** [comment]
My opinions:
1) That disposal bin is better off somewhere on the north side of the kitchen.I dislike it being there.
2) Remove the wall under the current disposal bin for more space,and put a table and the shutters,imo
3)>chef must go in bar to enter kitchen oh god no pls why even aa i'm gona scream
4)what is the chef even gonna do with all that space, he literally has no reason to imo
5)perhaps move grinder&processor too so you can leave the ol good 4 tile table for hallway,i suggest to move them right of the ice cream vendor

**Comment by Pyko1** [comment]
As it is.
capture

**Comment by Chronitonity** [comment]
This looks super ugly and uneeded, please no

**Comment by oprayx73** [comment]
please yes. i like how this would look and it'd be funny as fuck.

**Comment by doobiedoo23** [comment]
This is honestly terrible

**Comment by oprayx73** [comment]
this is honestly great

**Comment by Carbonhell** [comment]
It could be improved somehow but i like the idea behind it. The convenyor belt in front of the door is kinda eck but the idea overall is nice

**Comment by Pyko1** [comment]
still working on it, will post latest screens just in a moment.

**Comment by Pyko1** [comment]
capture
As it is now.

**Comment by Chronitonity** [comment]
Still really bad, the lower tables in the hallway are bad, the sprite for the convery belts looks terrible on them, the kitchen is more open with nothing added, things just spaced farther apart.

:-1: Its at best an interesting idea, but the execution is not good at all

**Comment by Pyko1** [comment]
capture

**Comment by Chronitonity** [comment]
Now theres just a lot of empty space near the bar/kitchen door.

And the rest _still_ looks ugly

**Comment by Foosili** [comment]
Why does the kitchen need this sushi bar esque conveyor thing??

**Comment by Lawligagger** [comment]
Can you change the floor in the bar tender's section to the old grimy carpet tiles it used to have? http://puu.sh/l9GAI/2c8e690bb1.png

**Comment by Chronitonity** [comment]
Those carpet tiles were universally hated, and made no sense in a place where alcohol is regularly spilled.

Also they look very bad

**Comment by danhibiki** [comment]
Maybe just make the table lead into kitchen instead of outside into the main hallway. It makes a small exposure of table for people to climb into kitchen, sure, but so does the tables outside towards the hallway.

**Comment by Pyko1** [comment]
capture

**Comment by Foosili** [comment]
Man I just still do not like this change, sorry man.

**Comment by danhibiki** [comment]
I think this is something we should go forward with. For one, its a nice little gimmick to have a sushi bar like trolley system. For two, bar and kitchen, layout wise, haven't been touched in a long time and need some love.

**Comment by Chronitonity** [comment]
I think it'd be better if it wasn't so bad looking, and functionally useless.

**Comment by danhibiki** [comment]
We have _plenty_ of functionally useless things that we've added, even recently. This adds a gimmick to the kitchen job.

**Comment by Pyko1** [comment]
I'm not happy with the look either at the moment, i will be working some more on this.

**Comment by Chronitonity** [comment]
Looks and spacial functionality trump over a gimmick. The kitchen doesnt need to be even more cramped. Spots like the two doors that meet on the same tile (a big no), and the thrown around kitchen equipment like the deepfryer is just ech.

This isnt even adressing the balancing issue that you can rest or use a box to get through those plastic flaps, or breaking through the glass, making sure the chef has no perfect way and closing off the kitchen like before.

Sure a gimmick is fine, but one that adds something that probably won't be used much while making everything look and operate worse is a bad argument on why you think its okay

**Comment by Pyko1** [comment]
capture

Getting the box on the tables isn't going to be easy, and resting wont do no good if the conveyor aren't on. But I added shutters just in case on the flaps and the window. Also there is now more room than before.

**Comment by Chronitonity** [comment]
The bar-kitchen connector still looks awkward, so does deep fryer placement

**Comment by Pyko1** [comment]
Been thinking of possibly separating the "bar-kitchen connector top a small room with both chef and bartender cloth closets, so its like a dressing room or something, as the kitchen backroom is technically a cool room.

**Comment by Chronitonity** [comment]
Dont think theres enough space there for it really, and id rather not have the clothing lockers moved away from the other storage lockers

**Comment by Pyko1** [comment]
Just playing with the idea.
capture

**Comment by Nebyab** [comment]
I dunno, I dig it.

**Comment by Chronitonity** [comment]
Backroom looks weird and clashes with the bar and kitchen area, the seethrough doors don't make much sense either if you want it to be a "changing room"

**Comment by lcass** [comment]
merge
CONFLICTS!!!!!

**Comment by Pyko1** [comment]
As it is, should be done unless someone wants something changed.
capture

**Comment by Crystalwarrior** [comment]
Alright I like where the conveyor belt is now, this looks much better than before. :+1:

**Comment by Dudeinyourbackyard** [comment]
The position of your dining tables is awkward. Transition the entirety of the right-most dining table one unit down, and the left-most one is in an odd position, I'm not sure where you could move it without it looking awkward. From what I see, you also have two scrubbers, one of them being completely disconnected near the middle table.

**Comment by Pyko1** [comment]
Maybe the other is an automated back scrubber, but ill remove it just for you.

**Comment by Dudeinyourbackyard** [comment]
if it serves a purpose then by all means keep it lad

**Comment by Pyko1** [comment]
capture

**Comment by Pyko1** [comment]
Added 3 Ketchup and 3 hotsauce packs and salt/pepper shakers to the bar, pretending that anyone actually bothers to use spices at 2d spessmen game.

capture

**Comment by Dudeinyourbackyard** [comment]
not that it means anything but :+1:

**Comment by Pyko1** [comment]
Added 1 banana creampie to bar desk, since some infidel had broken the long withstanding custom of clown throwing it to the bartender, or bartender throwing it to the clown at roundstart.

**Comment by Chronitonity** [comment]
Really not a fan of the changing room. The boozeomat is next to two doors, and the entire room just feels out of place and seperates the chef bartender duo even more. Id rather we put the table with a shutter on it between them again rather than a small room for "changing".

**Comment by doobiedoo23** [comment]
I don't see the point of the room in between the kitchen and the bar

**Comment by Lawligagger** [comment]
I honestly like it.

**Comment by danhibiki** [comment]
After discussion in the wizard chat, we've come to the conclusion of denying this pull.

**Comment by Chronitonity** [comment]
If this has been denied I'll go ahead and close it for now then

**Pull request closed without merging**
