### PR TITLE
Vault entrance

### PR DESCRIPTION
**Pull request by Pyko1**
Made it look hopefully a bit nicer, and be a bit more secure.
Added windows to space from HoP office and captains private room.

capture

### CODE REVIEW

**Comment by Pyko1** [comment]
Fixed the atmos in vault.

capture

**Comment by Chronitonity** [comment]
:+1:

**Comment by Pyko1** [comment]
Connected the Vault APC to powergrid.
Made the vault security checkpoint to be part of the vault area, instead of leeching off power all the way from sec office area.
Changed the maintenance under ai upload to be Bridge maintenance area instead of AI Upload area.

capture

**Comment by Pyko1** [comment]
Removed a stray wire under a door in engineering maintenance.

**Pull request merged**
