### PR TITLE
Cameras & Mime statues

### PR DESCRIPTION
**Pull request by Pyko1**
Added Cameras to 
- Invidual Cells
- Atmos Tanks
- Clown Office
- Mime Office
- Perma hallway above isolation
- East of Sec gear room
- South Of confrence Room
- Armory barrier room

Made all the armory cameras (excluding riotgear room) once again motion sensing.

Added 2 mime statues to the Mime Office.
Added changelog for kokojos adding the mime statues to code.

### CODE REVIEW

**Comment by Spacedong** [comment]
oh ye +1

**Comment by Nokington** [comment]
sure

**Comment by Kokojos** [comment]
yes yes yes

**Comment by Pyko1** [comment]
Also fixed all the 22 Rounds start AT's we had on station and centcom level.

**Comment by Nebyab** [comment]
usre

**Pull request merged**
