### PR TITLE
Mech buffs

### PR DESCRIPTION
**Pull request by Kierany9**
You wanna know how much damage the mech LMG does? A light machine gun that's mounted on a war robot designed to kill you as efficiently as possible while tanking a metric fuckton of damage?

Five

Yep, five.

**FIVE!!!**

Anyway, this PR basically buffs some of the mech weapons to stop them from being a laughing stock and make them actually worth using, most notably the Incendinary Carbine AKA Hades(Now fires incendinary slugs instead of a single dragonsbreath pellet, increasing its damage from 5 to 20), the LMG AKA Ultra AC 2(Fires a 6-shot burst with bullets dealing 10 damage each instead of a 3-shot burst of 5 damage 80 stamina bullets), the Shotgun AKA Scattershot(Increased pellets fired from 4 to 6 and tightened the spread slightly for maximum hallway devastation) and the laser and pulse cannons AKA Immolator, Solaris and eZ-13(Fires a two-shot burst instead of a single shot).

The Immolator is no-longer behind a research wall, but the Ultra AC 2 now is. Nanotrasen tends to prefer lasers whereas the Syndicate mostly use ballistics, it didn't make sense to have the LMG(which is weaker than a fucking uzi mind you) as a starting weapon and have the laser behind a research wall.

Adds a mech disabler, the RTC Detainer. Is available from the get-go and fires a three-shot burst of disablers which is enough to knock somebody out.

This update was mostly done to make the Dark Gygax and Dark Marauder actually useful, because as it stands their main weapons are an absolute joke, combine this with the subpar defenses of the Gygax or the absolute piss-poor mobility of the Marauder and both of their incredible vulnerabilities to the Ion Rifle and you have an absolute waste of 140 TC.

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
This is gucci as hell.
From what I recall mechas were absolutely fucking devastating once someone went murderbone with them pre-rebase, so it's probably /tg/'s changes of balance that brought the mechas down to their knees :disappointed:

**Comment by Pyko1** [comment]
Realism is all nice and everything... 
But the mech guns have practically infinite ammo, and science already has pretty much all the nice things in the game if it drags on.

And unstoppable murderboning mechs are only fun to 1 person.

**Comment by Kierany9** [comment]
I'd say that right now an Odysseus loaded with initro+neurotoxin syringes is more effective than any of the mechs when it comes to killing power. Yes, even the 90-140 TC Nuke Ops mechs. One problem I see with mechs is that they only have two counters: the Ion Rifle and other mechs. EMP kits, chemistry's EMPs and juking the mech with an SMG/Combat Shotty is somewhat viable but one of those is traitor exclusive and the other two rely on cargo/research(Which you'll need to make the mech anyway so moot point). I could make the LMG Nuke-Ops exclusive if the ridiculous damage is going to be a problem.

**Comment by KorPhaeron** [comment]
Should port my mecha armour facing and strafing changss if you're looking for a mecha buff. More interesting than just raising numbers I think.

https://github.com/tgstation/-tg-station/pull/16980

https://github.com/tgstation/-tg-station/pull/16607

A good pilot can mitigate a ton of damage, people can swarm and flank mechs for bonus damage, etc

Obviously not my codebase and you guys are gonna do what you wanna do, but just thought I would throw that out there

**Comment by Kierany9** [comment]
That actaully looks really good.

**Comment by carlarc** [comment]
Still, 5 damage is pathetic against another mech.

**Comment by McBawbaggings** [comment]
This this is hippie station and not /tg/. Mining doesn't often deliver so big stompy killing mechas aren't common place. I'd like to see them get a buff and get them back into playing rotation. If they're a bit OP then we can take it from there. I've never seen a nukie mech too, anything that gets things back into the meta is nice.
Armor and strafing buffs are cool as fuck. Please add that as well.

**Comment by carlarc** [comment]
admins can't do mech battles because 1. flashbang throwers fuck everyonething 
2. no one knows who's on which team
3. NOTHING IS EFFECTIVE
this fixes one problem

**Comment by dreamcrab** [comment]
i like that junk korphareon linked than the stuff in here

**Comment by Nebyab** [comment]
i'm okay with this, but if we want to take kor's things that that works as well

**Comment by Lawligagger** [comment]
http://i.imgur.com/zdBjoug.png

**Comment by Kierany9** [comment]
If you guys want this merged as-is, go ahead. Otherwise close it because I won't be able to port over Kor's stuff for a while due to a severe lack of time (and because im bad at coding guys).

**Comment by McBawbaggings** [comment]
Just in case I wasn't explicit enough, I'm +1ing this.

**Comment by calibraptor** [comment]
Why isn't this merged yet?

**Comment by trifornt-tinfornt** [comment]
Merge it already.

**Comment by TDcoolguy300** [comment]
Codes fine

**Comment by TDcoolguy300** [comment]
Merging, two headmins approved

**Pull request merged**
