### PR TITLE
Perma plants

### PR DESCRIPTION
**Pull request by Pyko1**
Added some seeds, random plants, fertilizer, spade, 3 rats and pest spray to perma.
Fixed stray lamp in court.

capture

### CODE REVIEW

**Comment by danhibiki** [comment]
Sure!

**Comment by Chronitonity** [comment]
Please no pest spray, that shit is insanely powerful, doesn't have an inhand sprite, and is just going to be used to slip security officers. This combined with your removal of blast doors means that no ones going to use perma because its so easy to fuck a sec officer who walks in

**Comment by Pyko1** [comment]
It already had 1 pestspray and that does not slip, and got like 20 toxin damage for spraying a whole can on myself.

**Comment by Chronitonity** [comment]
Step 1. Empty bottle with one click, Step 2. Fill with water, Step 3.

http://puu.sh/l4tOg/6c90ed2d26.png

So yeah, no thanks on adding more invisible slips into a secure prison

**Comment by Pyko1** [comment]
then again there are many other containers in there that can hold water as well, and make people slip.
But why does 10 unit spray from it slip, when from a spraybottle it does not?

**Comment by Chronitonity** [comment]
I'm pretty sure a 10u from a spray bottle slip. Arguing that there are already stunning weapons in perma so lets add more isn't a decent argument, there arguably shouldnt even be one pest spray in perma.

**Comment by Pyko1** [comment]
10 units from plantbgone does not at least slip, but ill see if i can sabotage these sprays to 5 unit only so they arent an issue.

**Comment by danhibiki** [comment]
Alternatively, just put hte pest spray on the outside so they have to ask the guard for it.

**Comment by Chronitonity** [comment]
No one will give perma prisoners anything.

**Comment by Pyko1** [comment]
So I made a new type of pest spray with injectonly flag, that should solve the issue.

**Comment by Pyko1** [comment]
hmm, looks like i had some plantbgone left in bottle, it seems to now slip as well, ill fix it as well.

**Comment by Pyko1** [comment]
The perma sprays can now only spray 5 units. Trying to remove the nozzle only says "The nozzle seems to be unremovable."

**Comment by danhibiki** [comment]
Sorry buddy, Nexendias map update got patched thru first, mind updating this?

**Pull request closed without merging**
