### PR TITLE
learn to spell mothrefukcer

### PR DESCRIPTION
**Pull request by Spacedong**
god damn this went unnoticed for years

### CODE REVIEW

**Comment by ArcLumin** [comment]
>learn to spell mothrefukcer

pot, kettle

**Comment by Spacedong** [comment]
that was the joke dumbass

**Comment by ArcLumin** [comment]
>not seeing that my joke was used as an extension of yours

**Comment by McBawbaggings** [comment]
dont be dong....

**Comment by ArcLumin** [comment]
dong is the super retard

**Comment by Kokojos** [comment]
ding dong banny

**Comment by GeneralGoose** [comment]
ebin

**Pull request merged**
