### PR TITLE
Turrets are cooler now.

### PR DESCRIPTION
**Pull request by ninjacha**
http://prntscr.com/82n12o
3kpkbg3

### CODE REVIEW

**Comment by ninjacha** [comment]
Oh, woops, I commited 28b11ea to turret-port instead of another branch.

**Comment by TDcoolguy300** [comment]
We can't auto-merge this due to it not being a bug fix, i'll try and bring it up with the headmins to try and approve this for merging

**Comment by lcass** [comment]
revert the wrassling belts and entirely remove the defines file , don't mess with that. Other than that it looks good.

**Comment by ninjacha** [comment]
I'm now permabanned for scarring 2 tiles now, so no thanks.

**Pull request closed without merging**
