### PR TITLE
Ports space funeral mobs

### PR DESCRIPTION
**Pull request by Spacedong**
https://vgy.me/cnERNr.png

Horrifying abominations from the indie game Space Funeral include:
Criers
Bloodhounds
Bloodfleas
Leghorses

currently only admin-spawnable and used for shenanigans/end-round slaughterfest

### CODE REVIEW

**Comment by yobob591** [comment]
oh yes i forgot about these

**Comment by Hackole** [comment]
Hey hey, I remember these things. They used to be in xenobio, yeah? +1.

**Comment by McBawbaggings** [comment]
Yeah okay +1

**Comment by Dudeinyourbackyard** [comment]
i missed these
+1/3

**Comment by Spacedong** [comment]
2 heads approval, merge

**Comment by ArcLumin** [comment]
mergan. damn this is a fast non-bug merge. You interupted my christmas eve dinner for this lad

**Comment by JohnGinnane** [comment]
No labels? Did anybody code check this at all??

**Comment by McBawbaggings** [comment]
Arc did I would assume.

**Comment by ArcLumin** [comment]
I did. In the middle of a family dinner because dong is impatient

**Pull request merged**
