### PR TITLE
Bomb test-area and disposals

### PR DESCRIPTION
**Pull request by Pyko1**
Added vents to the mass drivers at bomb test and disposals to prevent items being dragged off the massdriver by pressure differences.
Made bomb test-area indestructible so bombs wont bounce back to station when the floor is blown up.
Made disposals slightly larger, and added 2 spots for hardworking assistants, as well as some nice random things they have saved from the grinder.
Also the conveyor is on by default.

capture

### CODE REVIEW

**Comment by Cherkir** [comment]
:+1:

Cats should count as items when going through the grinder tbh

**Comment by Carbonhell** [comment]
I think the indestructable wall was intentional so the test range wouldn't be mono-use...Isn't there anything to make it work like that again?

**Comment by Pyko1** [comment]
could make some of the floor indestructible I guess.

**Comment by Spacedong** [comment]
make some of the floor indestructible and keep the indestructable wall so it isnt used just one time

**Comment by Nebyab** [comment]
sure

**Comment by Spacedong** [comment]
DONT MERGE THIS, he got rid of the indestructable wall therefore the test range will only be one use, add the indestructable wall back or don't bother

**Comment by Pyko1** [comment]
Bomb testing area after 5 max cap bombs.

capture

As long as there is gravity the bombs wont be bouncing off to station.

**Comment by Pyko1** [comment]
Added icons for paintbrushes and palettes, and placed 2 of each in top of canvases.

**Comment by Carbonhell** [comment]
I have to do a map repathing so if this could be merged soon i can start with it

**Comment by Nebyab** [comment]
@Nokington aaaaaaaaaa

**Comment by Nokington** [comment]
WHATEVER SURE

**Comment by Spacedong** [comment]
what is with the weird lattices just floating in space in that image

**Comment by Pyko1** [comment]
they are the lattices that surround the bomb test currently, partly blown off tho.

**Pull request merged**
