### PR TITLE
Adds a medkit to the Syndicate Infiltrator.

### PR DESCRIPTION
**Pull request by Spacedong**
Adds a regular white medkit to the syndicate infiltrator medbay.

### CODE REVIEW

**Comment by McBawbaggings** [comment]
You're modifying your previous changelog to the new one.

**Comment by Spacedong** [comment]
how to fix

**Comment by Spacedong** [comment]
its ok, what do you guys think@@@??

**Comment by McBawbaggings** [comment]
Ya know, considering how often people forget their pin pointers, I've got a feeling the medkit is gonna end up forgotten by most squads. It's cool +1.

**Comment by dreamcrab** [comment]
ayeaaaaaaa

if this is all fixed up then go for it man!!! +777777777777777777777777

**Comment by Spacedong** [comment]
2 head approval, merge

**Comment by Gandalf2k15** [comment]
heead approval, merging

**Comment by McBawbaggings** [comment]
wait did this get merged with travis failing?

**Comment by Dudeinyourbackyard** [comment]
1 check passed
Details continuous-integration/travis-ci/pr The Travis CI build passed

**Comment by Gandalf2k15** [comment]
There was an issue with github, it sorted itself out however, this did indeed pass.

**Pull request merged**
