### PR TITLE
Removes the stand arrow from mining and makes it admin-spawn only.

### PR DESCRIPTION
**Pull request by Spacedong**
GOODBYE JOJO

### CODE REVIEW

**Comment by yobob591** [comment]
n o

**Comment by gumner** [comment]
W H I N E  M E  U P

**Comment by oprayx77** [comment]
or you could atleast 80% the arti rooms kek

**Comment by trifornt-tinfornt** [comment]
No reason given as to why it's getting removed, straight up removal instead of nerfs and failure to understand that the damn thing was already about to get nerfed.

WHINE ME UP INSIIIDE

**Comment by yobob591** [comment]
Saltdong

**Comment by Spacedong** [comment]
It was removed because we have had too many killings, law breakings, and general fuckery resulting from non-antags getting a fuckload of stands. Every round has become a race to see who can get a stand first. It just doesn't fit the theme of the game either. Holoparasites are a neat item and should be reserved to traitors.

**Comment by gumner** [comment]
M-MUHHH IMMERSION!!!! DOESNT FIT SS13!!!

**Comment by yobob591** [comment]
Thing is it was about to be nerfed you meme so you have to put more effort into getting stando

**Comment by Spacedong** [comment]
gumner is going full sperg now that his favorite meme is being removed

**Comment by trifornt-tinfornt** [comment]
That's better.
Not to mention drones running around having their stands interact with people, or fucking setting them on fire because Chaos is a thing.
The Stand Arrow is a cool concept but it's not done well in execution, I'll definitely agree with that.
The thing should honestly husk you, and it was about to be nerfed to be like that. I think it should also blacklist Chaos and Explosive holoparasites because those are pretty much griff-only holoparasites that could not be viably used by a non-antagonist.
Blacklist things from being able to use them as well, such as Drones. As funny as it is, it causes a fuckton of griff. Perhaps borgs as well.

**Comment by oprayx77** [comment]
hippiestations entire features dont "fit ss13" so we can throw that out the window
we can however agree that the arms race for stands is a bit silly, so lets just give it a percentile chance not to show up

**Comment by Spacedong** [comment]
>hippiestations entire features dont "fit ss13" so we can throw that out the window

How so?

**Comment by yobob591** [comment]
It SHOULD husk you but as I've said the fix that husks you was merged but since !update is BROKEN it didn't go into effect

**Comment by gumner** [comment]
space moths totally fits ss13,aye?

**Comment by yobob591** [comment]
Also there IS a chance it won't spawn

**Comment by oprayx77** [comment]
we've got rollerskating ops, runescape text chat, cats, superfarts, dildos, hiding shit up ya butt, its all very silly stuff that adds to our lighthearted atmosphere.  the nerfs you want are on their way and agreed to anwyay, it should prevent second chances, and it shouldn't show up absolutely every round.

**Comment by Spacedong** [comment]
except stands are literally a direct reference to an obscure anime series that half the server doesn't give a fuck about

**Comment by trifornt-tinfornt** [comment]
So is Time Stop for Wizards?

**Comment by Spacedong** [comment]
except thats not really a direct reference

**Comment by gumner** [comment]
It is?

**Comment by asskek** [comment]
i agree with trifornt

**Comment by yobob591** [comment]
Let's remove the Wizards revenant shit then that's a reference to a game half the server doesn't play

**Comment by gumner** [comment]
Literally a reference to jojo

**Comment by asskek** [comment]
but whereas timestop is a legitimate feature w/ a tiny reference in the spell as a joke, stands and the stand arrow exist as a reference

**Comment by asskek** [comment]
that's their entire purpose, jojo memeing

**Comment by gumner** [comment]
ok,so the stand arrow and all the code inside it isnt a feature,its just bullshit,aye?

**Comment by yobob591** [comment]
this IS a feature it's purpose is to allow for nonantags to get holoparasites in a balanced way

**Comment by Spacedong** [comment]
non-antags shouldn't HAVE access to holoparasites.

**Comment by yobob591** [comment]
They should if it's balanced, we already voted on this before

**Comment by gumner** [comment]
non-antags should be fully unprotected from antags,we're a hugbox now,please respect antag rounds.

**Comment by Spacedong** [comment]
Let's just give non-antags all the shit antagonists use but balanced and nerfed, right?

**Comment by Spacedong** [comment]
Fuck off.

**Comment by gumner** [comment]
doesnt sound that bad

**Comment by asskek** [comment]
except let's not even nerf it for non-antags let's make it the exact same as the antag version except give it a different sprite so they can't be valided for it

**Comment by asskek** [comment]
right????

**Comment by yobob591** [comment]
Sure, I'd love to have more shit in space but powergaming niggers would game it

**Comment by yobob591** [comment]
60% chance to kill and husk you

**Comment by yobob591** [comment]
Yeah that's exactly the same as the antag version amirite

**Comment by gumner** [comment]
remove powerfist since antags and non-antags can get it,aye?

**Comment by Spacedong** [comment]
Non-antags can't get a powerfist.

**Comment by gumner** [comment]
they can you fuck,R&D

**Comment by asskek** [comment]
well R&D takes effort and skill

**Comment by Spacedong** [comment]
except we only see someone get that high a research level and use it like what? twice a month?

**Comment by gumner** [comment]
mining doesnt,even though a goliath may kill you in 20 seconds,right?

**Comment by Spacedong** [comment]
Except goliaths are easy to kill, just kite them with a kinetic accelerator.

**Comment by Spacedong** [comment]
You're running out of arguments here.

**Comment by McBawbaggings** [comment]
Yes please +1

I fucking said to make some sort of really random event like meteorites to make it rare. As it stands, the entire station having antag gear that isn't antag and it opens up a slew of problems. I also said simple mobs shouldn't have stands, which I was right about.

**Comment by yobob591** [comment]
Right it's not like you can powergame through RND in 15 minutes with a guide amirite

**Comment by gumner** [comment]
>goliaths are easy to kill
nigga have you ever mined?

**Comment by Spacedong** [comment]
Yeah, I actually have, they're one of the most simplest mobs to kill as a miner.

**Comment by yobob591** [comment]
The thing is it's SUPPOSED TO BE MORE PUNISHING BUT !UPDATE BROKE

**Comment by yobob591** [comment]
Give me a chance to fucking rebalance first

**Comment by Spacedong** [comment]
It will be removed from the asteroid until you can figure out a way to make it crash into the station from a meteorite event or something.

**Comment by gumner** [comment]
kek,if you somehow get hit by two goliaths at the same time,you're literally dead unless you run,what could cause some other mob like a hivelord to spawn and cuck you

**Comment by asskek** [comment]
but you almost never get hit by two goliaths if you're not a braindead moron

**Comment by yobob591** [comment]
Right so I'll make it come from a meteor but be more powerful then

**Comment by yobob591** [comment]
Sounds fair

**Comment by Spacedong** [comment]
don't make it more powerful than it already is

**Comment by gumner** [comment]
doesnt actually,most of rounds dont even have meteors

**Comment by asskek** [comment]
yeah well most rounds shouldn't have stands

**Comment by yobob591** [comment]
If you will only get it from a meteor then it shouldn't be balanced for an asteroid nigger

**Comment by Spacedong** [comment]
What do you mean balanced for the asteroid?

**Comment by yobob591** [comment]
50% kill chance and no husky but it's from a random event

**Comment by Spacedong** [comment]
no

**Comment by yobob591** [comment]
The busking and high kill chance balanced it got the asteroid

**Comment by yobob591** [comment]
Except the husking was broken until nalar fixed !update

**Comment by SpankMasterson** [comment]
imo it should just rarely spawn in hidden rooms, like 5% chance.

**Comment by Swagile** [comment]
it was balanced the way it currently is (and is still being fine tuned) because of the fact that anyone can get it if they mine long enough / get lucky

if it becomes a meteor item only, then it doesn't have to be balanced because meteors are even rarer than mining artifact rooms

and fuck off spacedong with this theme bullshit, you literally added dragon dildos into the game

also we haven't even fully gone through the testing phase of the code as promised, and the bugs are being fine tuned

**Comment by McBawbaggings** [comment]
I even said in the original PR to make it only apply to humans.

**Comment by McBawbaggings** [comment]
Original PR shouldn't have been merged.

**Pull request merged**
