### PR TITLE
Revert "Beret Armor Value Removal"

### PR DESCRIPTION
**Pull request by blobbernaut**
Reverts HippieStationCode/HippieStation13#2474

because THIS IS A GARBAGE FUCKING CHANGE

### CODE REVIEW

**Comment by Spacedong** [comment]
:+1: I don't understand why it was nerfed at all

**Comment by calibraptor** [comment]
-1.

How I enjoy drinking your powergaming tears.

**Comment by blobbernaut** [comment]
"Powergaming"? Are you legitimately fucking retarded

**Comment by blobbernaut** [comment]
removing features (The head of security being allowed to customize his appearance a tiny fucking amount) is BAD

**Comment by doobiedoo23** [comment]
fuck off blobber

**Comment by calibraptor** [comment]
Either wear a helmet for protection or wear a beret for style points. A man cannot have both.

**Comment by blobbernaut** [comment]
WHY IS THAT BAD

**Comment by blobbernaut** [comment]
M-MUH TRAITORS NOT BEIN ALLOWED TO DUMPSTER THE HOS WITHOUT TRYIN

**Comment by blobbernaut** [comment]
This is pure fucking garbage I literally don't understand. His other hat is untouched, what's up with that? 

Why is forcing the HOS to choose between looking 1: fucking retarded or 2: having armor a healthy thing to add to the game? seriously somebody please answer this

**Comment by Kokojos** [comment]
I understand this can be frustrating, but at least wait one week. The PR just got merged, this will get the contrary votes.

**Comment by blobbernaut** [comment]
No fuck you the beret armor was merged within two days, there wasn't even a fucking real discussion about it

can you actually give me a decent argument on why removing the armor is a good thing to add to the game

**Comment by Spacedong** [comment]
why did you close this are you kidding

**Comment by trifornt-tinfornt** [comment]
People already have had a massive outcry, and you're closing this when nobody wanted that PR to begin with.
Grade A coders.

**Comment by blobbernaut** [comment]
http://i.imgur.com/FHgNocN.png

**Comment by blobbernaut** [comment]
what a surprise @Kokojos @nalarmg @Nebyab @JohnGinnane

**Comment by calibraptor** [comment]
The salt is real.

**Comment by blobbernaut** [comment]
@Kokojos @nalarmg @Nebyab @JohnGinnane

the poll doesn't stop from having happened by ignoring it.

**Comment by JohnGinnane** [comment]
I'd be happy to merge if it gets approved, just like with the original

**Comment by blobbernaut** [comment]
Wow great point cali, now if I may offer a rebuttal? You're a god damn child.

**Comment by calibraptor** [comment]
Sure thing mister salty britches.

**Comment by Spacedong** [comment]
calib you're a cunt

**Comment by calibraptor** [comment]
saltshaker

**Comment by Nebyab** [comment]
Hey calib, fuck off

**Comment by calibraptor** [comment]
Okay.

**Comment by Gandalf2k15** [comment]
Can we revert this please. Its retarded.

**Comment by Nebyab** [comment]
As much as I disagree with this PR, it has a right to exist

**Comment by dreamcrab** [comment]
i agree with this +1

the beret looks dope, why make it useless?

**Comment by McHatters** [comment]
holy moly I didn't think people would get so buttblasted about the berets, but if so many people feel so strongly about it then I guess it has a right to be changed back

**Comment by Nebyab** [comment]
If you want to look dope, you need to have the skills to back it up. Otherwise wear your dumb helmet if you want to be safe.

**Comment by McBawbaggings** [comment]
Why not just make it warden, HoS and sec officers all get the helmet and the Warden and HoS get better ones? I want goofysec

**Comment by trifornt-tinfornt** [comment]
How about you give set an AutoDrobe full of chicken hats?
Little man hide behind armor and tasers.

**Comment by calibraptor** [comment]
@McBawbaggings The HoS and Warden have caps that provide armor, and I'm making a PR that makes the HoS and standard security spawn with caps and helmets respectively.

 #2485

**Comment by dreamcrab** [comment]
@nebyab but why

**Comment by blobbernaut** [comment]
Because a ton of people disagree with the change, dreamcrab.

**Comment by dreamcrab** [comment]
i already agree with this PR, you monkey. im asking nebyab why i cant look good as hos with a unique item and also be protected

**Comment by blobbernaut** [comment]
Exactly. Realism isn't exactly an issue. We have handheld laser guns, energy shields, and space wizards. 

Hell, even today we have bulletproof business suits.

And cali, that is one of the issues I had that will be fixed if that PR gets passed.

**Comment by Gandalf2k15** [comment]
I want my barret back...

**Comment by Mithrandalf** [comment]
I miss the subdermal implant.

When do we get that back?

**Comment by blobbernaut** [comment]
as  soon as somebody wants to uncomment it

**Comment by calibraptor** [comment]
Subdermal implant was cool

**Comment by Nebyab** [comment]
It seems as though popular opinion is against this pr (even though the old ways were and are better). Doesn't seem right to push this on people if they truly do not wish it.

**Comment by blobbernaut** [comment]
Look at the vote poll I posted earlier when we asked the server whether they wanted this change reverted. 21 votes yes, 2 votes no.

Popular opinion is definitely not against this.

**Comment by doobiedoo23** [comment]
Uh he meant the beret armour removal PR ya big dumbo

**Comment by blobbernaut** [comment]
oh

**Comment by Nebyab** [comment]
Also blobber
I'm gonna say upfront that poll has 0 weight to it. The way its set up means that there is no valid conclusion that can be extracted from it.

**Comment by blobbernaut** [comment]
I disagree quite a bit with that statement, but alright.

**Comment by Nebyab** [comment]
Mate, your poll has no poll question aside from "revert" so we have no way of telling if the questions and discussion leading up to it influenced the vote in any direction.

The poll is also done over 60 seconds, and usually a lot of people don't vote which means that any conclusion that can be drawn is inherently flawed, as we have no way of telling who doesn't actually care about the issue, and who didn't know the poll was going on.

The poll also has a meme option which heavily invalidates any conclusion that can be drawn from it.

**Comment by blobbernaut** [comment]
make another poll then, a lot of players think the change is bad. Having a meme option does not invalidate it at all. It is what people who would vote randomly or people who have no opinion select.

**Comment by Nebyab** [comment]
I'm not disagreeing with your conclusion mate, just your methods. If you're going to straight up tell me a poll conducted like that, with all the missing info, and all the flawed methodology is one that should be taken at face value no questions asked, then, well I'm sorry for you.

**Comment by Pyko1** [comment]
I personally prefer the old armored berets, and would like to have them back, or couple a bit nicer looking helmets to choose from.

But what I really miss is the HoS Dermal implant, as hats and afros dont mix.

**Comment by Gandalf2k15** [comment]
Just revert it please.

**Comment by blobbernaut** [comment]
not face value, obviously, but it's certainly a fucking hint.

**Comment by blobbernaut** [comment]
yeah seriously i'm gonna make a pr for dermal implants soonish actually those were great

**Comment by Nebyab** [comment]
Does it give a clue? Certainly. Is it in any way valid as a poll? Nope

**Comment by TDcoolguy300** [comment]
Bring back dermal implant 2090

**Comment by Voratius** [comment]
-1/3rd, why?

**Comment by Spacedong** [comment]
add this back you retarded fucks holy shit push this immediately

**Comment by dreamcrab** [comment]
yea do this, literally nobody will use berets anymore and theyre cool and good

**Comment by Spacedong** [comment]
only a few people used beret anyway because it had less armor than helmet, now you've made NOBODY use it at all, this has nothing to do with powergaming, the people that removed beret armor are fucking retards who lack reading comprehension, jesus

**Comment by Gandalf2k15** [comment]
+11111111112222

**Comment by Spacedong** [comment]
big fat ol :+1:

**Comment by blobbernaut** [comment]
Spacedong, that is exactly why the first reply to this PR is probably the single dumbest thing I've read EVER on github. I don't know why cali said it because this is definitely not something that even affects powergamers. Like at all.

**Comment by blobbernaut** [comment]
Second reply, rather

**Comment by GeneralGoose** [comment]
why someone thought removing armor is a great idea????  this is retarded

**Comment by Mithrandalf** [comment]
Ree merge this.

**Comment by McBawbaggings** [comment]
Sec shouldn't look professional to me.
I'd rather we have sec start with the helmets. Goofysec best sec

**Comment by McBawbaggings** [comment]
In interests of the playerbase rather than my own opinion, I'll approve this PR.

**Comment by Spacedong** [comment]
2 heads approved, dreamcrab and mcbawg, merge it

**Comment by JohnGinnane** [comment]
@blobbernaut if you could do up a changelog so that other players are aware of the revert that would be appreciated

**Comment by Nebyab** [comment]
>2 heads approval

Mate I already gave this the a-okay 6 days ago

**Comment by Kokojos** [comment]
You guys can't merge?

Anyway, a revert would be welcome before I merge it.

**Comment by Spacedong** [comment]
oh yeah also why don't sec officers spawn with berets anymore, will this PR  fix that too?

**Comment by blobbernaut** [comment]
No all this does is revert the PR in question because I made it using the revert button there

I'll see if I can figure out how to: Add a changelog, and make officers spawn with berets

**Comment by JohnGinnane** [comment]
I think it's best to keep the "make officers spawn with berets" in Sarcalogo's PR: https://github.com/HippieStationCode/HippieStation13/pull/2428 as it's related to that.

For the changelog, you can look at https://github.com/HippieStationCode/HippieStation13/tree/master/html/changelogs and copy the example.yml

**Comment by blobbernaut** [comment]
no i know that but i have to find out how to add the file on here because i didn't make this pr with the client

**Comment by McBawbaggings** [comment]
git status
git add [THE CHANGELOG FILE DIRECTORY IN QUOTES]

**Comment by McBawbaggings** [comment]
Dunno if the changelog thing works if you modify a changelog. 
I'd just revert that changelog to the original state and make a new one. 
They auto delete after time anyway.

**Comment by blobbernaut** [comment]
It's not modifying the original changelog, that's just github's comparison checker. Note the filename also is changed.

**Comment by JohnGinnane** [comment]
Looks good. Is this good to be merged?

**Comment by blobbernaut** [comment]
I believe so

**Comment by Spacedong** [comment]
merge it already @johnginnane

**Pull request merged**
