### PR TITLE
Ports meat pizza mobs to the game and puts some on the asteroid that the clown ship is on

### PR DESCRIPTION
**Pull request by Spacedong**
From a year ago before rebase happened
They teleport you when they hit you and are generally for comedic value 

Sprites:
https://vgy.me/dsh3he.png
https://vgy.me/vETQ0U.png

NOTE: Some code related to old vars and procs has been deleted as I felt it wasn't really necessary to revitalize it. However, the change between idle states and aggressive states is not there so I'd like someone to help me figure out how to switch between the idle and aggressive states when they spot people.

E̶D̶I̶T̶:̶ ̶Y̶o̶u̶ ̶c̶a̶n̶ ̶a̶l̶s̶o̶ ̶m̶a̶k̶e̶ ̶t̶h̶e̶m̶ ̶b̶y̶ ̶c̶o̶m̶b̶i̶n̶i̶n̶g̶ ̶a̶ ̶s̶i̶n̶g̶u̶l̶a̶r̶i̶t̶y̶ ̶t̶o̶y̶ ̶w̶i̶t̶h̶ ̶a̶ ̶m̶e̶a̶t̶ ̶p̶i̶z̶z̶a̶.̶ ̶N̶o̶t̶ ̶r̶e̶c̶o̶m̶m̶e̶n̶d̶e̶d̶ ̶a̶s̶ ̶r̶e̶s̶u̶l̶t̶s̶ ̶m̶a̶y̶ ̶v̶a̶r̶y̶.̶   no

### CODE REVIEW

**Comment by McBawbaggings** [comment]
I'd like to pick up for delivery.

**Comment by McBawbaggings** [comment]
"I'd like to pickup for delivery."
"Sorry sir, we don't deliver, not after the last miscarriage."

+1 lmfao

**Comment by Spacedong** [comment]
fucking loss

**Comment by Hackole** [comment]
Gosh, all these good PR's spacedong - it's almost like you're actually contributing or something. Crazy, right? +1.

**Comment by Spacedong** [comment]
ya

**Comment by Spacedong** [comment]
REVERT THIS OH NO

**Pull request merged**
