### PR TITLE
fixes invisible cats

### PR DESCRIPTION
**Pull request by Spacedong**
merge this immediately after the revert of the revert then update after both are merged

### CODE REVIEW

**Comment by Pyko1** [comment]
is this tested?
I assume no, since its in 2 parts.

**Comment by Pyko1** [comment]
No missings tails or ears?

Seeing the onyl change is to the body, and noting to mutated bodyparts.

**Comment by QuarianCommando** [comment]
Doesn't look like there's any issue. Catbeast ears and tails aren't separate sprites like with moth wings. The revert being separate from this fix is proper protocol. 

The original revert should never have happened in the first place. A maintainer should have noticed the sprites weren't updated, and should have held off merging until this was added.

**Comment by Pyko1** [comment]
dongdong catlove Part 2 take 2

**Comment by Pyko1** [comment]
Aaaaand still broken...

**Pull request merged**
