### PR TITLE
Important Research Outpost Bug Fixes (100% Complete)

### PR DESCRIPTION
**Pull request by Sarcalogo**
- Removes the cameras from the Dorms and Bathrooms
- Adds an airlock on the station where the shuttle is to prevent depressurization and air loss
- Fixes access on the shuttle so it can be opened
- Properly names all APCs
- Removes all instances of double R-walls
- Replaces the locker corridor with a locker room that mirrors the one on the main station
- Replaces Xenobiology with a genetics research room (NO CLONER DO NOT WORRY!)
- Adds an empty construction room
- Makes Research less empty looking, adds some tables with parts on it
- Adds a windoor and table to chemistry
- Adds ONE pair of insulated gloves in the engineering section so solars may be set up properly
- Expands the kitchen by two tiles and adds an empty table and grinder
- Stacks of metal and glass are now 50 sheets instead of 1
- Fixes the Virology doors so that the patient room can be opened and the main doors start locked
- Adds a wall on the 2nd Solars Airlock
- Removes meme fixture, bringer of light.
- Adds a few windows and cameras
- Makes the station Research Shuttle area less windy.
- Fixes the camera issues
- Fixes the piping issues.

### CODE REVIEW

**Comment by Sarcalogo** [comment]
There it's done.

**Comment by calibraptor** [comment]
Hope this makes the docking area less butt ugly

**Comment by Sarcalogo** [comment]
I cannot change the docking area much considering the station map is so cramped I basically had to reroute you to south of where the shuttle lands.

**Comment by Pyko1** [comment]
in future check the ctags and roundstart AT's

**Comment by Sarcalogo** [comment]
Ctags..? What's that. Also I guess I could try to fix the shuttle on station so you board it from the left instead of the right...

**Comment by Pyko1** [comment]
...

**Comment by Pyko1** [comment]
You cant just slap cameras, you have to set their network and ctag aka camera name that they are found on camera consoles and such.

**Comment by Gandalf2k15** [comment]
I fixed the docking system you had, this creates conflicts however.

**Comment by TDcoolguy300** [comment]
I am not sure if this needs Headmin approval with the whole adding a genetics area, but whatever.

**Comment by Sarcalogo** [comment]
Now for some pictures... and Gandalf, if you don't like the new Dock still, you think it takes up too much space or whatever, then you can change it after this is all merged.

http://imgur.com/a/QJzA7

**Comment by Sarcalogo** [comment]
Well I just noticed that I included two lights on the same tile in the kitchen. I'd change it, but nah... I spent hours already on this shit... I'm pretty exhausted. Someone else can do it if it really bothers them that much. The only place that has double r walls is the virology patient cell. Maybe I could change that too, but honestly it was intentional.

**Comment by Gandalf2k15** [comment]
Yeah I'll create a new PR fixing the light and editing the dock after this is merged.

**Comment by TDcoolguy300** [comment]
Is this good to go @Sarcalogo?

**Comment by Pyko1** [comment]
Why is there over 6k changes on station level?

**Comment by Sarcalogo** [comment]
Yes it's good to go except for this map merge thing that I don't know about...do you mean this?

https://tgstation13.org/wiki/Map_Merger

Yeah I guess I can do that next time or do you want me to..

**Comment by Sarcalogo** [comment]
Okay I used Map Merge.

**Comment by Gandalf2k15** [comment]
Merge please? This is pretty important.

**Comment by McBawbaggings** [comment]
+1. It currently looks a lot nice than it was previously.

**Comment by Carbonhell** [comment]
Nerds head approval.

**Comment by Sarcalogo** [comment]
Did you just say nerd?

**Comment by Sarcalogo** [comment]
Also there are only two headmins now, and Mcbawgings is one of them and he just approved. Not sure if that's enough. In any case, I don't see what really needs to be approved, most of it is bug fixes and rearranging a few things.

**Comment by TDcoolguy300** [comment]
Technically needs Headmin approval due to it adding a genetics area and removing the Xenobio

**Comment by McBawbaggings** [comment]
To clarify Sarcalogo, you require 2 Headmin approvals. 3 Gamemasters = 1 Headmin vote though. Currently the people holding Headmin votes are myself, Nebyab and Hippie.

**Comment by TDcoolguy300** [comment]
Also codes fine

**Comment by JohnGinnane** [comment]
This might be unrelated, but someone was having an issue with not being able to open some science doors on the server last night. Are there airlocks in science department in place for this?

**Comment by Sarcalogo** [comment]
Only one is the experimentor lab on the right side. If they couldn't open the doors it has nothing to do with this. Did not touch anything in Science except for that door.

**Comment by Skullyton** [comment]
Screenshots where?

**Comment by Sarcalogo** [comment]
Don't feel like recompiling a different branch just to take a screenshot of a few rooms.. so uh just look at the imgur I posted to see most of the changes. Viro is essentially the same as it was, just moved the virus food dispenser one tile to the right and locked the doors. That's about it.

**Comment by Pyko1** [comment]
To use map merge you have to do the prepare maps before any edits, if the map is edited anyway tis pointless. But then again there is no other mapping PR:s up so i guess its fine.

But in future, before you do any edits to the current map run the prepare maps, and after you are done with your edits run the map merge before uploading your changes.

**Comment by calibraptor** [comment]
+1 Just merge this so it's less cancerous

**Comment by dreamcrab** [comment]
i don't want to replace xenobio with genetics, i like the idea of the research station being overrun by slimes. personally. the rest of it looks great, though.

**Comment by Gandalf2k15** [comment]
Alright, I'm gonna work on this once its merged. Proposed plan: Move Toxins/Xenobio to outpost, replace toxins with telesci on station, xeno don't know yet. That means scientists can make bombs to mine, and actually get R&D done, I'll likely remove everything else. But I'll see.

**Comment by dreamcrab** [comment]
gandalf, lets talk on the coderchat slack about about changes before you put a bunch of effort in

**Comment by McBawbaggings** [comment]
>Putting telescience back
It was removed for a very fucking good reason.
I mean, power gaming with telesci is fun as fuck for no one except for the guys getting free cool loot for days.

**Comment by JohnGinnane** [comment]
What sort of stuff were powergamers doing?

**Comment by Voratius** [comment]
I know the power of telescience first-hand. Never re-add it as a round-start available function again.
Telescience's only use is powergaming, it has no other proper function on the station.

You would see people teleporting gear from off-station Z levels, teleporting the nuke ops' nuke and basically making it unwinnable, destroying the malf AI within seconds of it being found it, teleporting bombs/team antags to brig, freeing other prisoners from permabrig, and if you were good, you could teleport heads and just keep them captive.

**Comment by Sarcalogo** [comment]
Work on it all you want, I never claimed to be a good mapper. You'll probably make it better.

**Comment by Skullyton** [comment]
Do you guys not have teleport-exempt areas or teleproofing?

**Comment by Voratius** [comment]
@Skullyton nope, there were talks of adding a thing like that, but I forgot what the consensus was.

**Comment by McBawbaggings** [comment]
As I keep hearing more and more about what's wrong with the outpost from mapping and coding perspective AND its current game play balance, I'm more tempted to say that the following should be done.
>Rip it up
Redo it right to be more sciency and less autismbasey
Actually fucking test it making sure it is functional
Map the area to actually be not broken too

I will get the other headmins to weigh in on this but for now, my vote stands on redoing the entire thing.

**Comment by Sarcalogo** [comment]
It's absolutely not going to happen. I already fixed all the bugs and mapping issues with this PR. If you want me to redo the whole thing because you think it's "unbalanced" it's not going to happen. I spent around 30 hours total working on this including the bug fixes and stuff. I will not redo it just so someone else can come along after it's finished and say it's still not good enough, and have wasted even more time. 

Prior to even completing it, I told everyone what was going to be on the station. Everyone who had the power to say "get rid of it" or "change this" said nothing. The PR was open for I believe, 3 weeks? Nobody said anything. Now it feels like I'm being jerked around, and my motivation to work any more on this has plummeted to zero.

It makes absolutely no sense to scrap the whole thing at this point, especially since most of the real issues have been fixed. As far as I am concerned, your options are either to: Revert the entire thing and abandon the idea entirely, or to merge this which fixes all of the bugs and mapping issues, and lets the others who want to make their own changes (hey that could even be you!) to do so. 

Nothing starts out perfect, and to expect something, especially a map, which typically evolves over time, to be so, is not a realistic expectation.

**Comment by Voratius** [comment]
You put in minimal effort into this entire thing.
You were too lazy to mark the area down properly(outpost blends into space, unidentifiable in DM), you were too lazy to set up a scrubber system, you just copy-pasted the APCs, the pipes aren't colored properly, you forgot to put up an atmos system in the docks(which themselves are just half-assed), the area itself feels extremely claustrophobic, the entire outpost has 2 disposals that both lead to space(and are at opposite ends of the outpost), but aren't connected, the lockers (botany and engineering) can't be opened by scientists, you need to steal the only hardsuit to wire solars, virology doesn't have a biosuit(???)
Why are virology, chemistry and research there? We already have those on-station.

You didn't even supply screenshots to show us what it looks like.

We didn't expect it to come out perfect, we expected it to come out half-decent and playable. When it was first introduced,scientists didn't have access to the shuttle, it was missing an airlock, the docking system didn't have an atmos system, and all the other issues listed above.

**Comment by Gandalf2k15** [comment]
Alright, I have remade the outpost. I will be making a PR to merge it.

**Comment by McBawbaggings** [comment]
Take note that I did not approve the outpost in the first place. I wasn't made headmin until after it had been merged. 

I do have a problem with the outpost being so fully stocked and essentially, a second station. Why does it have a virology? Why is there a mini medbay? The mining outpost has medkits and a drip that's all. There's a fully functional botany with easy access to chemistry, I'd be better playing botany in science rather than on the station (Easy access to floral somotray too!)



There are no scrubbers at all.
Dock room APC is still named server room APC
The camera network is SS13 despite being off shores

3 instances of wires through walls which is bad, there's even one going into chem that leads nowhere.
http://imgur.com/B0gtYMB
http://imgur.com/rwLl44P
http://imgur.com/bVl2Fn1

3 instances of lights not facing the right way. (Botany locker is also not in botany)
http://imgur.com/egFnOCJ
http://imgur.com/gHOi5oH
http://imgur.com/QGhID85

3 instances of atmos being broken.
http://imgur.com/sliWyWR
http://imgur.com/dfVN5ag
http://imgur.com/mrq0rIm

And a room missing a vent.
http://imgur.com/kfhFt5f

**Comment by JohnGinnane** [comment]
Added DNM as per Gandalf's request

**Comment by McBawbaggings** [comment]
I understand I've done a 180 on this issue, but I shouldn't have said it's gucci when it wasn't.

**Comment by Sarcalogo** [comment]
Well if Gandalf said he remade it, go ahead. He'll have better luck getting it merged anyway. And yeah man, that's how it goes. All of that stuff could have been fixed if pointed out, and it's easy to make mistakes with piping when placing an item over a pipe automatically deletes it. 

It's kind of the point of the Research station to be the place to go when you don't want to be bothered by a bunch of bullshit. That's its purpose, a place to "experiment" and "research" a bunch of the game mechanics. It comes with the downside that you are isolated and extremely vulnerable to being just picked off and fucked over. Sure you could just join as a scientist, but then you are stuck in the outpost all round and aren't really interacting with anybody or anyone. It requires a solars array because it consumes much more power than the mining station.

**Pull request closed without merging**
