### PR TITLE
Clown/Mime Office redesign and additions

### PR DESCRIPTION
**Pull request by Spacedong**
- Redesigned clown/mime office to look more clowny and mimey respectively. 
- Added a mirror to clown office. 

http://vgy.me/VwbfFe.png

### CODE REVIEW

**Comment by Kokojos** [comment]
Is the mime computer finnaly anchored?
Otherwise this seems okay.

**Comment by Spacedong** [comment]
no I didn't anchor it because frankly I didn't know it was unanchored to begin with

**Comment by Spacedong** [comment]
done

**Comment by Cherkir** [comment]
>changes tile patterns within two 3x3 areas

:+1: for effort anyway

**Comment by Spacedong** [comment]
da gwafix duud

**Comment by Limed00d** [comment]
Personally think they would both benefit from some more space, make them a bit more similar to pre-base offices.

**Comment by Cherkir** [comment]
You should map a dungeon where the clown can torture his victims instead

**Comment by Spacedong** [comment]
@cherkir there's already one in maint somewhere, also does it really matter how big they are considering its just a spawn place for mime and clown with only a few items of value really (the lockers)

**Comment by Cherkir** [comment]
@spacedong to be honest a couple botany trays and a banana seed dispenser would be nice for the clown office

**Comment by Spacedong** [comment]
there is literally a garden a few rooms down that has all of that

**Comment by Cherkir** [comment]
Oh yeah.

**Comment by Spacedong** [comment]
wew

**Comment by Cherkir** [comment]
So is this getting merged or what?

**Comment by Nokington** [comment]
sure

**Pull request merged**
