### PR TITLE
is_type_in_list performance increase

### PR DESCRIPTION
**Pull request by blobbernaut**
Ports
https://github.com/tgstation/-tg-station/pull/17717
https://github.com/tgstation/-tg-station/pull/17825

Simply put, it's an absolutely bonkers performance increase, especially in the case of the Tesla.

### CODE REVIEW

**Comment by calibraptor** [comment]
A performance boost of any sort would be welcome.

**Comment by McBawbaggings** [comment]
I really doubt that code improvements need HA approval but +1

**Comment by Nebyab** [comment]
someone code check, fine assuming this will work as intended

**Comment by Kokojos** [comment]
@JohnGinnane I bet you can codecheck this better.

**Comment by JohnGinnane** [comment]
Code looks good, hopefully this won't mess with any other procs, merging

**Pull request merged**
