### PR TITLE
Nerfs power sinks

### PR DESCRIPTION
**Pull request by Kierany9**
# Please do not use exponential scaling ever again without checking how much it will actually scale beforehand thank you very much.

(fixes https://github.com/HippieStationCode/HippieStation13/issues/1710 causing freezers to drain power as well as being able to cool gases below 0 degrees kelvin, and granting them negative pressure)

(this does not nerf actual power sinks)

### CODE REVIEW

**Comment by ArcLumin** [comment]
Sad my ghetto power sinks won't work anymore. No more direct grid wiring to instantly kill all power to the station

On the otherhand, happy idiots don't upgrade the medbay freezer and drain absolutely all power from medbay

+0.1

**Comment by McBawbaggings** [comment]
>Ghetto powersink
Why not use the engineering room above chapel as that? Or solars?

**Comment by ArcLumin** [comment]
because you could make freezers that drain 1 million+ power from the entire station at once if directly on grid

**Comment by ArcLumin** [comment]
Basically, freezers are actually more draining than actual powersinks if upgraded

**Comment by McBawbaggings** [comment]
Oh yeah I forgot.
Yeah okay +1.

**Comment by ArcLumin** [comment]
Also, 10/10 deepest lore changelog

**Comment by GeneralGoose** [comment]
>Please do not use exponential scaling ever again without checking how much it will actually scale beforehand thank you very much.

or you can like use max() to cap it

**Comment by Kierany9** [comment]
>or you can like use max() to cap it 

you'd actually have to use min() for that though

b+ for effort

**Comment by banthebantz** [comment]
finally the meme is fixed

**Comment by GeneralGoose** [comment]
yea i confuse those 2

**Pull request merged**
