### PR TITLE
TG Port #19405 : Canned Laughter

### PR DESCRIPTION
**Pull request by Spacedong**
Ports https://github.com/tgstation/tgstation/pull/19405 

Canned Laughter: A soda can filled with the canned laughter reagent has been added to the clown's backpack. Anyone who ingests it will laugh uncontrollably complete with a laughing sound effect. Honk.

### CODE REVIEW

**Comment by dreamcrab** [comment]
https://www.youtube.com/watch?v=iYVO5bUFww0

ye +4

**Comment by McBawbaggings** [comment]
Yeah okay +1

**Comment by Gandalf2k15** [comment]
Errything looks fine, merging.

**Comment by GeneralGoose** [comment]
why not make *laugh emote

**Comment by Voratius** [comment]
Did any of you mongoloids actually playtest it or even read it up?

It stays in your system forever, it spams laughing at least once per second(according to calib).
 
This PR has been up for less than 24 hours. We really need a rule that PRs should be up for at least 48 hours so that everyone can get a fucking input on it.

**Comment by PKPenguin321** [comment]
Always test your ports :laughing:

**Pull request merged**
