### PR TITLE
Increases price of adrenals from 8 to 12

### PR DESCRIPTION
**Pull request by Spacedong**
Implants are now properly tiered, with Storage being at 8, Adrenals being at 12, and Uplink being at 14.

### CODE REVIEW

**Comment by oprayx73** [comment]
pls

**Comment by Swagile** [comment]
why is uplink so high?

there is like 0 reason to buy it since most of the time you are killed then cremated / spaced / morgued, not perma brigged which is its entire purpose of existing.

**Comment by JohnGinnane** [comment]
@Spacedong don't forget about changelog please

**Comment by JohnGinnane** [comment]
And also update wiki if this goes through: http://wiki.hippiestation.com/index.php?title=Syndicate_Items#Adrenal_Implant

**Comment by banthebantz** [comment]
I don't like this.

**Comment by Kierany9** [comment]
-t Unrobust Dude

**Comment by Swagile** [comment]
how is unrobust a valid reason not to put this through, kier?

id argue its unrobust to be able to get a 3-time lifesaver from any conflict that is a anti-stun + full heal from all damage types, especially considering that people use epherdine on top of adrenaline.

**Comment by blobbernaut** [comment]
Epinephrine needs a buff seeing as it's pure adrenaline, it makes a real shitty anti stun

**Comment by Kierany9** [comment]
@Swagile 

I was talking to blob.

**Comment by banthebantz** [comment]
@Kierany9 I don't even use adrenals much because they're not essential, but they are certainly useful. By increasing the price so much you are just ensuring they'll never be used and are nerfing traitors to be even more pathetic in comparison to other antags.

**Comment by banthebantz** [comment]
@Swagile 

Weren't you arguing adrenals weren't worth the TC a bit ago?

**Comment by McBawbaggings** [comment]
I don't like anti stun chems but honestly all you're gonna do is make it more worthwhile to use shit like ephedrine in place of them.

**Comment by Swagile** [comment]
i thought they were worthless because i remember a changelog that stated they were one use now, but that got changed. its 3 uses and does a full heal, as well as gives you temp super speed, so all the damage you did to the dude / stuns are completely worthless three full times.

if you aren't completely inept, you can easily only have to use this in the most dire situations (which are rare if you raided armory / cargo for eguns and det's office for .38 / space for .38 revolver)

**Comment by trifornt-tinfornt** [comment]
saltdong
Adrenals already just got nerfed, they're no where near as efficient any more. Even then after Kierany decided to screw around, Ephedrine and others are even better and permanent if you're able to access chemistry/ghettochem in time. Increasing the price won't really change anything besides people running around on ephedrine instead of adrenals - saving the TC and being even more powerful instead of just going the lazy route to adrenals. If you're going up against a confirmed traitor by yourself without any gear besides a stunprod or something then you pretty much deserve to get your face bashed in.

Adrenals and Antistuns are lame, however as I've stated this will change nothing (thanks kierany). Besides, Adrenals just recently got nerfed.

**Comment by Swagile** [comment]
mate ive faced a traitor high on both epherdine and had adrenaline as backup

i was captain and required both a ranged holo (cheap as hell), high on epherdine, and another partner (my farm) to take him down. i was also high on morphine on top of all of that just so i could keep moving at full speed even while damaged since the dude had a .38 revolver and a glock that he kept firing at me.

its seriously overpowered as it currently is, and epherdine is a discussion for another day.

**Comment by banthebantz** [comment]
@Swagile No you just need to git gud and learn how to deal with people that don't go down in one taser shot.

**Comment by trifornt-tinfornt** [comment]
@Swagile 
Double downing on chems shouldn't be possible, the most powerful should override/flush out the others immediately. I'd agree on that in a heartbeat.
However something like that has been around for ages, especially in dental implants. Meth was never actually so powerful that they were practically immune to stuns, they just had eighteen thousand antistun chems running at once which got them up immediately. It's boring and it's lame.
This isn't going to change that, nor is it going to fix that.

**Comment by banthebantz** [comment]
Anti stuns don't stack.

**Comment by Swagile** [comment]
@banthebantz 

you mean three taser shots and still running

and you can't shoot them to death due to their hyper speed going faster than laser / ballistic shots

literally only won because my ranged holo got 8 lucky shots in which slowed them down enough that epherdine was useless, then the rest was just keeping them down till they died to ranged spam

**Comment by trifornt-tinfornt** [comment]
@banthebantz 
They've always stacked. They might not stack any more with the new system, but before that they absolutely did stack. Hackole can confirm it, I can confirm it, pretty much anyone who has used the stuff and actually looked for a difference can confirm it. Plus, there was nothing in the code that said that they couldn't/shouldn't stack.

**Comment by banthebantz** [comment]
@Swagile You should be using disablers, they're far more effective against ephedrine than tasers.

@trifornt-tinfornt I'm almost sure they didn't but it's been a while so maybe I'm remembering wrong.

**Comment by Spacedong** [comment]
ill just remove all anti-stuns ok

**Comment by ArcLumin** [comment]
Fake adrenals sometimes being purchased instead of normal adrenals WHEN

**Comment by Spacedong** [comment]
changedong incoming

**Comment by JohnGinnane** [comment]
Code looks good by the way

**Comment by LuisReyesX** [comment]
Remove stuns when?

**Comment by Spacedong** [comment]
soon

**Comment by Swagile** [comment]
All sec officers now spawn with lethal ballistics instead of tasers and have the ability to use lethal force if they are being assaulted. HoS and Captain start with a NT assault rifle instead of eguns and armory now only has shotgun.

i can dream, can't i?

**Comment by Hackole** [comment]
Adrenals have never been an issue - the normal chemistry-made antistuns ARE, though, at the moment.

**Comment by Spacedong** [comment]
ngl @swagile that would solve a lot of problems, assistants wouldn't fuck with security as much because of the fear of being shot up and dropped, one-stun-combat would be less prominent and people would need to gear up more to assault the HoS and Captain

**Comment by Swagile** [comment]
thats the problem with sec, there is no fear in facing them.

but thats a discussion for another time.

**Comment by oprayx73** [comment]
-t alberto barbossa

**Comment by JohnGinnane** [comment]
Need head input on this as it's 23 days

**Comment by SplergeBucket** [comment]
idk the stats on adrenals rite now
it shouldnt heal
nor should you be quicker than before; if anything you should just have regular movespeed from them
them being taken to 12 is big
i like 8, but 10 is probs better rite now with them
again i dunno the stats someone gimme em

**Comment by McBawbaggings** [comment]
No please

**Comment by JohnGinnane** [comment]
Two heads said no, closing

**Pull request closed without merging**
