### PR TITLE
Waste Disposals "Fix"

### PR DESCRIPTION
**Pull request by Pyko1**
Made the Waste Disposals once again shoot the thrash out of Z level instead of the singularity cage wall.
image

### CODE REVIEW

**Comment by Chronitonity** [comment]
Honestly my main gripe is that the conver belt is just super stretched and that the room where everything is in is now just huge and open with nothing else in it besides a lever

**Comment by Pyko1** [comment]
I guess i could add some shit or move things around a bit as well.

**Comment by Pyko1** [comment]
Update Image:
capture

**Comment by Chronitonity** [comment]
:+1:

**Comment by Kokojos** [comment]
Too many warning signs.
Also IIRC there's no need for double launchers, one should do.

**Comment by Pyko1** [comment]
I kinda agree on the signs.But with just 1 launcher it will break after a while once the tile under the blast door is depressurised. But placing the vent under the blastdoor might fix tho.

I'll see what I can do.

**Comment by Pyko1** [comment]
Better?
capture

**Comment by Kokojos** [comment]
Just make sure all your signs are correctly labelled and I see no problem with this at first view.

**Comment by Pyko1** [comment]
Yeah, changed the name and desc on those sign.

**Comment by JustinBNewton** [comment]
remove the walls that are in space as well as the catwalks outside the door and leading off the southern catwalk to the north. That area in south arrivals is supposed to be a docking port for larger ships.

img

**Comment by Pyko1** [comment]
As it is now.
capture

**Comment by Chronitonity** [comment]
Catwalk should probably extend more so they almost touch each other.

**Pull request closed without merging**
