### PR TITLE
Sleeper pod balance

### PR DESCRIPTION
**Pull request by blobbernaut**
Prevents sleeper pods from injecting hilariously lethal amounts of healing chemicals as a result of /tg/'s new overdose system. 

Adds an emag option to sleeper pods. 

There is a 2% chance for sleepers to become death pods which can inject a lot of nasty chemicals. 

The pod can be taken apart and put back together to reset the damage.

Also changes superfart damage to 50 because it needed to be done. 75 was a death sentence because you'd bleed into crit in like 30 seconds.

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
The lack of file changes is strangely appetizing

**Comment by blobbernaut** [comment]
Whoops

**Comment by Nokington** [comment]
10/10

**Comment by blobbernaut** [comment]
Im out right now I'll add it when I get home. Would anybody object to this change in principle


Sent from my Sprint Samsung Galaxy S® 6.-------- Original message --------

**Comment by blobbernaut** [comment]
ok

**Comment by Lawligagger** [comment]
Seems good to me.

**Comment by Nokington** [comment]
Why not?

**Pull request merged**
