### PR TITLE
changed the new admin jumpsuit's description and sprite to mimic the old one and because im autistic

### PR DESCRIPTION
**Pull request by Spacedong**
thats pretty much it, it looks like the old one and I got rid of the cybernetic fluff bullshit

### CODE REVIEW

**Comment by ArcLumin** [comment]
Sure

**Comment by TheOneAndOnlyCreeperJoe** [comment]
No fuck you I like turtlenecks

**Comment by blobbernaut** [comment]
body_parts_covered = CHEST|GROIN|LEGS|FEET|ARMS|HANDS

**Comment by McBawbaggings** [comment]
lmao okay +1

**Comment by Spacedong** [comment]
2 head approval, merge

**Comment by ArcLumin** [comment]
Merging dongcode, hope I don't regret it

**Pull request merged**
