### PR TITLE
Catwalks

### PR DESCRIPTION
**Pull request by Spacedong**

### CODE REVIEW

**Comment by whitefox08** [comment]
Please provide pictures when you do map edits :ok_woman:

**Comment by Spacedong** [comment]
they're literally everywhere, I cannot sum it all up, I just deleted errors and shit resulting from pyko's copypasting of em

**Comment by Carbonhell** [comment]
screens or it didn't happen
no really did you just add lattices everywhere or what,more info please

**Comment by Spacedong** [comment]
I added lattices everywhere where there needed to be

**Comment by Spacedong** [comment]
Ill get pictures soon

**Comment by Spacedong** [comment]
pics as requested
https://vgy.me/CarPcQ.png

https://vgy.me/PNKQYs.png

https://vgy.me/9dtKZy.png

https://vgy.me/3mVpOy.png

**Comment by Kokojos** [comment]
There seems to be a little problem here.
+"cQi" = (/obj/structure/lattice,/obj/structure/grille,/obj/structure/lattice,/turf/space,/area/space)
 +"cQj" = (/obj/structure/grille,/obj/structure/lattice,/obj/structure/lattice,/turf/space,/area/space)

Those 2 paths mean here that there's
cQi : latticce, then a grille, then another lattice, on top of space?
cQj = grille, then lattice, then another lattice, on top of space?

Im unsure if this is really the case (mapmaker's a bit chunky) but I'd advice checking via testing the server and running around the whole lenght.

**Comment by Nebyab** [comment]
It'd be nice if you made a zoomed out picture of what the latticework sure, also check out what koko is talking about. If everything is fine i'm fine with it

**Comment by Spacedong** [comment]
@kokojo yeah its a result of pyko copypasting my catwalks half-ass into his map update a while ago

**Comment by Spacedong** [comment]
ill check it later or tomorrow

**Comment by blobbernaut** [comment]
what are even the purposes of the lattices if they're broken in places

**Comment by Spacedong** [comment]
closed til I figure out more shit

**Pull request closed without merging**
