### PR TITLE
Makes CQC gloves robust

### PR DESCRIPTION
**Pull request by blobbernaut**
Gives them heat resistance and insulation and makes them look like regular fingerless gloves. Description is still different though.

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
++++++×1

**Comment by Mithrandalf** [comment]
Yessssss.

Wrestling belt next, right?

**Comment by calibraptor** [comment]
Sweet, now nobody can instantly know you're valid salad just by examining you.

+1/3rd

**Comment by dreamcrab** [comment]
this is super dope +1

**Comment by blobbernaut** [comment]
Sure mithrandalf, but I don't know how to make the wrestling belt stealthy, my idea is to have the special effect of the wrestling belt basically drastically increase your tankiness and stun resistance from anybody you haven't done a wrestling move against recently.

**Comment by calibraptor** [comment]
@Blobbernaut I disagree, it should only really do that against someone you're currently wrassling. Have the wrassling individual no sell it and scream 'NO WEAPONS IN THE RING!'

**Comment by Mithrandalf** [comment]
I'd make it interrupt speech on slams like eswords, buff the damage and give it a little armour and stun reduction personally.

**Comment by Kokojos** [comment]
Yes

**Comment by McBawbaggings** [comment]
Remove electrical protection please.

**Comment by dreamcrab** [comment]
actually yeah remove their insulated properties

**Comment by Voratius** [comment]
ye, sounds neat +1/3rd

**Comment by Kokojos** [comment]
As soon as the insulation is gone this is mergeable.

**Comment by blobbernaut** [comment]
Sorry. I have been unbelievably, incredibly busy. Busy enough I literally did not have time to merge a single line of code.

**Comment by McBawbaggings** [comment]
Merging this, change was made.

**Pull request merged**
