### PR TITLE
GOODBYE JOJO PART 1

### PR DESCRIPTION
**Pull request by Spacedong**
Reverts HippieStationCode/HippieStation13#3211

### CODE REVIEW

**Comment by Spacedong** [comment]
After this is merged, the initial stand arrow PR will be reverted as well.

**Comment by banthebantz** [comment]
you fucking hero

**Comment by ArcLumin** [comment]
Dong, just fuckin remove the arrow from mining, make it admin spawn or in a random z level template.

Less removal, more reworking

**Comment by Spacedong** [comment]
fine

**Pull request closed without merging**
