### PR TITLE
get your shit together coders you're expected to know the science behind the things you code

### PR DESCRIPTION
**Pull request by Spacedong**
"The IUPAC adopted the spelling sulfur in 1990, as did the Royal Society of Chemistry Nomenclature Committee in 1992."

### CODE REVIEW

**Comment by banthebantz** [comment]
rename all chems to IUPAC systematic names when

**Comment by Spacedong** [comment]
all the chemicals were named after their IUPAC names except sulfur because eurocucks need to put their spellings into everything

**Comment by banthebantz** [comment]
No I mean the full https://en.wikipedia.org/wiki/IUPAC_nomenclature_of_organic_chemistry

**Comment by Spacedong** [comment]
oh god

**Comment by KittyKathy** [comment]
If you are fixing descriptions here are a few to consider mostly medical reagent stuff found in https://github.com/HippieStationCode/HippieStation13/blob/master/code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm
1. Silver Sulfadiazine and Styptic Powder - they no longer work overtime. They only heal once on touch application, should also add to the description over 30 units of this chemical in a patch does not add to the effectiveness.
2. Saline-Glucose Solution, Styptic Powder and Omnizine - does not state in the descriptions that they help stop bleeding.
3. Miner's Salve - does not state that it is touch based only and that on other methods of consumption result in stamina damage(pretty much the same as Styptic Powder non touch based consumption resulting in toxic damage but for this it is stamina damage).
4. Synthflesh - does not state that it does stamina damage based on the amount applied times 1.5(So a 50 unit patch applied to someone will do 50*1.5 = 75 stamina damage and splashing a large beaker full of it will do double that 150 stamina damage).
5. Calomel - does not state that it corrects the consumers sense of direction( it does M.client.dir = NORTH so if you get shot with Rotatium inject this to instantly fix your screen).
6. Pentetic Acid - no it does not have a chance of dealing brute damage.
7. Morphine - It only makes you drowsy when it leaves your body. It makes you sleep when you have 30 or less health and it has been in your body for 10 or more cycles. It makes you sleep when it leaves your body and you have 30 or less health. It does not drain faster on sever injury or decrease the effectiveness of stun resistant chemicals.
8. Epinephrine - "Minor boost to stun resistance" this has not been true since the last time it was changed.
9. Antihol - does not state it heals toxin damage a tiny bit.
10. Insulin- does not state that it helps prevent sleeping one of the symptoms of "hyperglycaemic shock"(Yes this is probably not how you spell it but look at this https://github.com/HippieStationCode/HippieStation13/blob/master/code/modules/reagents/Chemistry-Reagents/Consumable-Reagents/Food-Reagents.dm#L57).
11. Sugar - does not state you can overdose on that and sleep for eternity when you do consume 200 units of sugar.
12. Bromelain and Dermaline - "Effective at healing severe brusing and very efficient but acts somewhat slowly" misleading description it heals the same amount no matter how hurt you are, 2 damage per tick same as the basic version(Bicaridine/Kelotane) of it. The only real difference from the basic versions is that when you have 30 or more damage of the type it heals it stays in your body twice as long until this is no longer true and it checks this every tick.
13. Tricordrazine and Omnizine - they use the word "all" when technically they only heal certain damage types not all types of damage. They should just state specifically what types they heal because they don't heal clone damage, brain damage, Tricordrazine does not heal bleeding(which is BloodLoss that Omnizine heals), ear damage, eye damage and stamina damage.
14. Cryoxadone and Clonexadone - "A chemical mixture with almost magical healing powers" does not really explain what it does except well magic healing? So Clonexadone is a stronger magic healing chemical seems like a good description right?
15. Iron - does not state that it helps generate blood I think it is pretty much the best reagent to take when you need blood. Proof: https://github.com/HippieStationCode/HippieStation13/blob/master/code/modules/mob/living/carbon/human/blood.dm#L70
16. Space Lube - Maybe it should say on the description that it makes you valid if you spray this?

**Comment by Spacedong** [comment]
so you want everything spelled out for you

**Comment by MethMedic** [comment]
Normally I'd call you a fucking autist but this triggers me too please merge.

**Comment by KittyKathy** [comment]
Oh no not for me i know all this stuff already, it is mostly for people like you and newbies who probably don't know this. Also wrong/inaccurate descriptions are bad descriptions why do we have a chemical that says it reduces stun resistance when we got rid of all stun resistance chemicals? At least fix that ones that are just plain wrong if you are going to listen to me at all.

**Comment by Sarcalogo** [comment]
A shame that Kitty Kathy is a psychopath, you can tell from their posts on Github that they are High IQ. What a waste!

**Comment by Spacedong** [comment]
Sad!

**Comment by ArcLumin** [comment]
>spacedong says coders need to be knowledgeable about things they code

pot, meet kettle

**Comment by Sarcalogo** [comment]
"Needs code review" It'sfixing a spelling error, literally modifying a string, it doesn't need to be checked.

**Comment by tortellinitony** [comment]
last time spacedong modified a string it made catbeasts invisible

**Comment by ArcLumin** [comment]
it was a single letter typo. And he made all cats in the game invisible. Don't underestimate dongpower

**Comment by Spacedong** [comment]
it doesn't need a changelog

**Comment by ArcLumin** [comment]
More me being sarcastic than anything

**Comment by ArcLumin** [comment]
Code's good, just surprised you didn't fix the typo on the commented parts of files. Sloppy dong, sloppy.

**Comment by Spacedong** [comment]
its internal shit, i dont give enough of a fuck

**Comment by ArcLumin** [comment]
You dongtism works in mysterious ways

**Comment by Spacedong** [comment]
aye

**Comment by ArcLumin** [comment]
See your dongtism didn't activate when I said you instead of you're.

**Comment by ArcLumin** [comment]
Merging since it's just typo fixes

**Pull request merged**
