### PR TITLE
Clown and Mime Spacesuits & Clownship template

### PR DESCRIPTION
**Pull request by Pyko1**
Adds Clown and Mime spacesuits, and the spacesuit storages for the said suits to the code.

cloonspess
mimspess

And a clown ship template that has clownspacesuits in it.
Also changed the lab shuttle template to use /area/template/Labshuttle instead of /area/template.
cloonship

The ship also has 25 bananium sheets, about 10 bananium coins, prototype clownshoes and cordinates to clown planet.

### CODE REVIEW

**Comment by FuryMcFlurry** [comment]
we dont use stunned sprites anymore, we use some code fuckery for that

**Comment by Pyko1** [comment]
the stunned sprites are not in actually, just copy pasted the sprites from my source file that had em.

**Comment by Pyko1** [comment]
Also changed the lab shuttle template to use /area/template/Labshuttle instead of /area/template.

**Comment by Pyko1** [comment]
Turned off the cannons by default, and added a powersupply if someone wants to turn em on again.

cloonship

**Comment by Pyko1** [comment]
Clownship just got a bit bigger.

cloonship

**Comment by Nokington** [comment]
:+1: what could possibly go wrong

**Comment by Nebyab** [comment]
why nopt

**Pull request merged**
