### PR TITLE
Clown shoes now honk with every step you take

### PR DESCRIPTION
**Pull request by Spacedong**
as opposed to honking every other step because FUCK /TG/ 

credit to tdcoolguy

honk

### CODE REVIEW

**Comment by Zadeon** [comment]
Add this in now.

**Comment by Memendia** [comment]
oh dear god....

**Comment by Nokington** [comment]
nein. i dont need my ears to bleed

**Comment by Spacedong** [comment]
WOW >VOTING NO 

AHAHAHA THE FIRST COWARD TAKES HIS PICK, WHO WANTS TO TRY NEXT? :HONK:

**Comment by Limed00d** [comment]
Nah.

**Comment by Carbonhell** [comment]
Rejected sadly

**Pull request closed without merging**
