### PR TITLE
Adds HUDglasses to the Captains Locker

### PR DESCRIPTION
**Pull request by Sarcalogo**
Self explanatory. Captain should have HUD's.

### CODE REVIEW

**Comment by carlarc** [comment]
also add gar huds and cuffs

**Comment by oprayx73** [comment]
cap shouldnt have huds removed ban banned banned nad removed bandedhevn
please ad this

**Comment by Nokington** [comment]
k

**Comment by Pyko1** [comment]
code is fine

**Comment by Carbonhell** [comment]
-1, gives the captain even more reason to act like security imo.

**Comment by meteoses** [comment]
Cuffs too please, and yes, definitely HUD as well.

**Comment by Nebyab** [comment]
alright

**Pull request merged**
