### PR TITLE
Map fixes

### PR DESCRIPTION
**Pull request by Pyko1**
Fixed things around sec.
Removed the cell shutters.
Made the sec halway hopefully a bit more nice looking.

### CODE REVIEW

**Comment by Chronitonity** [comment]
Needs pictures of everything changed

**Comment by Pyko1** [comment]
capture
And 5 legal posters at sec office, could be some minor thigns like lamps elsewhere.

**Comment by Chronitonity** [comment]
http://puu.sh/kGXhB/c54452eec4.png

This cell up here really just needs to be cut out, its a major eyesore.

**Comment by Chronitonity** [comment]
http://puu.sh/kHywK/505d07920f.png

Remove the fireaxe from the armory, theres no reason for one to be in there

**Comment by Pyko1** [comment]
But what if the greytiders are in fire, you need to chop it off.

**Comment by Chronitonity** [comment]
Its some powercreep and really shouldn't be there

**Comment by Pyko1** [comment]
capture

**Comment by Pyko1** [comment]
capture

**Comment by Pyko1** [comment]
capture

**Comment by Pyko1** [comment]
capture

**Comment by Chronitonity** [comment]
ding ding

**Pull request merged**
