### PR TITLE
Removes the extra chemical generation speed from engorged glands

### PR DESCRIPTION
**Pull request by blobbernaut**
Why DOUBLING how fast you can use your powers only cost 1 mutation point, I have no idea. This is long overdue.

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
While this is grudgecode
fuck Changelings.
Nerf them into oblivion.
:+1:

**Comment by Spacedong** [comment]
its not grudgecode when the entire playerbase hates it

**Comment by Hackole** [comment]
:+1:

**Comment by TheOneAndOnlyCreeperJoe** [comment]
yeah go for it just stop touching my cluwnes

**Comment by Kokojos** [comment]
Good grudgecode +1

**Comment by Kierany9** [comment]
Grudgecode but good grudgecode

**Comment by banthebantz** [comment]
no not me precious meta!1111

**Comment by McBawbaggings** [comment]
Honestly this isn't even lings most broken power.
But yeah okay +1.

**Comment by SplergeBucket** [comment]
is this the only gland which increases chem regen speed i dont remember
if it is then the chem regen speed needs to be made another power or included but nerfed a bit

**Comment by ArcLumin** [comment]
This is the only chem regen speed power

I don't think it should be removed, but reworked/nerfed

**Comment by blobbernaut** [comment]
No fuck regen speed

**Comment by ArcLumin** [comment]
Why not break them up into one with amount increased, and one with increased regen speed, and increase the cost/tier?

**Comment by blobbernaut** [comment]
Because I don't think increased regen should be a thing at all, you can make the PR for it as another power if you want

**Comment by SplergeBucket** [comment]
well im on no but there's two headmins on yes

**Comment by doobiedoo23** [comment]
-1/3, go away grudgecode

**Comment by blobbernaut** [comment]
> basing your entire opinion on the fact that it's grudge and not
commenting on the actual balance of the issue

Go away doobie

**Comment by trifornt-tinfornt** [comment]
Lings are horrendously OP murderbone machines that need nerfing/rebalancing.
PR gets put up to take out one of their more obnoxious powers.
"-1/3 go away grudgecode"
10/10 dis guy knows what's UPPP
in fact I'm gonna leave this PR a THUMBS DOWN
:-1:

**Comment by ArcLumin** [comment]
confirmed massive disapointment in this grudgecode pr, even trifornt thumbed down

**Comment by Nebyab** [comment]
i dunno

**Comment by SplergeBucket** [comment]
why would we want oldling
a terrible idea which doesnt fit in the present climate of playerbase issuses

**Comment by trifornt-tinfornt** [comment]
Even then oldling would still be insanely overpowered. Now you don't even have tiers, and you can get the incredibly powerful paralysis sting (it's better than the one we have for current lings) even earlier, on top of your mute sting. There was a reason it was replaced, but it got replaced with murderbone incarnate - which ended up getting replaced with murderbone incarnate.
honestly just remove everything that has "ling" in the title. it's a curse

**Comment by LuisReyesX** [comment]
change the name of shadowlings to negromen and change the name of changeling to changesuccs
the curse is broken.

**Comment by Lawligagger** [comment]
ok

**Comment by Gandalf2k15** [comment]
Code check passed. 2/3 headmin approval. Final checks in progress.

**Comment by Gandalf2k15** [comment]
All systems are GO. Merging as all requirements have been passed.

**Pull request merged**
