### PR TITLE
North Arrivals/EVA Maintenance change.

### PR DESCRIPTION
**Pull request by Pyko1**
Tried to make it look nicer.

capture

### CODE REVIEW

**Comment by danhibiki** [comment]
I like it

**Comment by Cafaling** [comment]
Is it even possible to make Maint look nice without making it more bloated?

**Comment by nalarmg** [comment]
Conflicts. Needs further head input.

**Comment by Pyko1** [comment]
Re-added the map changes that were accidentally reverted.
Added chrons armory removes to my PR as this will most likely conflict with any map change.

**Comment by Chronitonity** [comment]
Needs a quickmerge

**Pull request merged**
