### PR TITLE
Ported canaries from /vg/ 

### PR DESCRIPTION
**Pull request by Spacedong**
rip my nigga foos taken too soon
squawk

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Code looks fine but can you post a pic of the new sprite(s)?

**Comment by JohnGinnane** [comment]
Also conflicts need to be resolved

**Comment by JohnGinnane** [comment]
For conflicts I believe it's easiest if you go to your master, get the latest updates and then start again, and this is a very small PR so it shouldn't take long

**Comment by McBawbaggings** [comment]
What do these even do?

**Comment by Pyko1** [comment]
Kinda like ovaries, but not really?

Also I should not need to ask this, but you added the sprites to our .dmi, instead of just over writing it, right?

**Comment by JohnGinnane** [comment]
@McBawbaggings It just looks like a simple toy

**Comment by Pyko1** [comment]
naw, abort, that made it jsut worse, still need to pull out more shit to resolve conflict.

**Comment by Pyko1** [comment]
Actually @Spacedong your fork is horribly outdated.

Rebase it to master or something, and then try again.

git remote add upstream https://github.com/HippieStationCode/HippieStation13.git
git fetch upstream
git checkout master
git rebase upstream/master
git push -f origin master

**Comment by JohnGinnane** [comment]
Yeah, I would close this, fix your fork and then begin again

**Pull request closed without merging**
