### PR TITLE
Removes artificial lag on AI tracking

### PR DESCRIPTION
**Pull request by Sarcalogo**
Ported over from /tg/. Some faggot a long time ago added artificial lag on the AI camera tracking. /tg/ removed it there a few months ago, and now I'm removing it here.

### CODE REVIEW

**Comment by calibraptor** [comment]
yes yes yes Yes Yes Yes YES YES YES

**Comment by calibraptor** [comment]
Literally 5 lines changed, somebody code check this and shake the headmins from their power induced euphoria to approve it.

**Comment by JohnGinnane** [comment]
Code looks good.

Also mfw artificial lag in byond

**Comment by Crystalwarrior** [comment]
Haha holy shit yes

**Comment by McBawbaggings** [comment]
Yes please.

**Comment by Gandalf2k15** [comment]
no my immersuns -10

**Comment by trifornt-tinfornt** [comment]
Thank you.

**Comment by dreamcrab** [comment]
ye sure +33

**Comment by Nebyab** [comment]
it took someone outside of the team to finally do what i asked without even knowing i asked for it

**Pull request merged**
