### PR TITLE
Makes Adrenal Implant Nuke Op / Surplus crate only

### PR DESCRIPTION
**Pull request by Sarcalogo**
Discuss.

### CODE REVIEW

**Comment by Kierany9** [comment]
>lets remove traitors only counter to stuns so i can powergame harder

go away sarcalogo

**Comment by Sarcalogo** [comment]
>Lets keep the antag murderbone invicibility cheat so I can murderbone the whole station effortlessly

Adrenal implants didn't always exist you know.

**Comment by Kierany9** [comment]
That still doesn't invalidate my point.

Also if you're going to remove stimpacks as well don't try and sneak it into the PR without listing the changes.

also also no logs you doofus.

**Comment by Limed00d** [comment]
No thanks

**Comment by Crystalwarrior** [comment]
No changelog, no compromise presented, this is just a straight up nerf with little thought put into it.
Adrenal Implans are the single saving grace for Traitors if they actually manage to get themselves stunned, and even then a very good counter to adrenals are the fucking disablers everyone has.

This is yet another nerf designed to fuck over traitors while giving even more power to security. Please think this through.

**Comment by Crystalwarrior** [comment]
by "everyone has" I mean security bleh

**Comment by Sarcalogo** [comment]
Your point is wrong considering the counter to stuns is not getting stunned, then there is also the dental implant thing you forgot about. 

> even then a very good counter to adrenals are the fucking disablers everyone has.

Adrenals instantly heal all stamina damage.

**Comment by Sarcalogo** [comment]
You don't walk up to the deal table with a compromise ready, you let other people offer and see what happens. That's the art of the deal baby!!!

**Comment by Kierany9** [comment]
>You don't walk up to the deal table with a compromise ready

You also don't walk up to the table and then refuse to explain what you bring to the table. Here's a question: what does this accomplish? I mean you've just presented this PR with no context or explanation for why you think this is a good idea, you just did it and expect people to approve of it.

**Comment by Sarcalogo** [comment]
I don't expect anyone to approve it actually, I expect it to get denied. It should be obvious what it's meant to accomplish. Stopping murderbone traitors who are pretty much invincible after they get a certain set of equipment.

**Comment by Kierany9** [comment]
Adrenals are a one-use item, cost 8 TC and serve as the only counter traitors have to stuns which are stupidly OP as it is.

also hackole tells me this is grudgecode did he ruin your validhunting lately?

**Comment by McBawbaggings** [comment]
Traitor tots already have it rough with random searches from shitsec which is allowed. The only way to prevent murderboners is to make it bannable.

**Comment by JohnGinnane** [comment]
> pretty much invincible after they get a certain set of equipment

Isn't that the point though? If you work very hard and get all the best gear then you're going to have an advantage of other players, that's the point. The item itself is very expensive for a single use.

**Comment by Gandalf2k15** [comment]
Fuck off

**Comment by dreamcrab** [comment]
nah

**Comment by calibraptor** [comment]
No thanks.

**Comment by Nebyab** [comment]
In spite of the staggering lack of polite discourse in this pr, this is just grudgecode that even you admit would get denied.

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/tgstation/pull/16807

I have a potential compromise here if anyone cares

**Comment by trifornt-tinfornt** [comment]
That's also stupid. It would affect basically nothing as Hippie is rarely lowpop.

**Comment by Kokojos** [comment]
2 heads nos

**Pull request closed without merging**
