### PR TITLE
Fixed the abandoned lab area being called "Incinerator" on area lists

### LINKED ISSUE #2735: the abandoned lab near medbay maint is still marked as "Incinerator" area-wise
probably a leftover from old code

### PR DESCRIPTION
**Pull request by Spacedong**
Fixes #2735

### CODE REVIEW

**Comment by Pyko1** [comment]
Technically changes nothing besides how something is called codewise. But should had prolly preserved the old incinerator area just incase some other hellhole also uses it.

**Comment by Spacedong** [comment]
I don't think anything else uses it

**Comment by QuarianCommando** [comment]
What even happened to the old incinerator? I used to actually use it.

**Comment by yobob591** [comment]
idk, can someone bring the incinerator back?

**Comment by ArcLumin** [comment]
It LOOKS fine but you know, >dongcode

Merging as it's a fix

**Pull request merged**
