### PR TITLE
Changes the chance of certain gamemodes showing up + Abduction Mode

### PR DESCRIPTION
**Pull request by Kierany9**
# Somebody call Nalar I'm touching the config

This has been a long time coming, the introduction of King of the Disk didn't help matters either. The total weight has been changed from 31 to 34 (w/abductors), and the combined weight of all traitor/ling modes has been reduced from 17 to 13. Traitor/Ling variants now occur around 40% of the time instead of 60%, and some seriously rare modes such as Cult and Malf AI have been given a boost in their chance to appear. I'm open to feedback on any changes to the weights but for now, the PR's out there.

*Edit:* Now with abductors because headmins.

**New modes in rotation**
Abductors(3)

**+1 Weight**
Nuclear Emergency(2 -> 3)
Gang(2 -> 3)
Malf AI(1 -> 2)
Cult(1 -> 2)

**+/-0 Weight**
Traitor(5)
Changeling(2)
Wizard(4)
Revolution(2)
Shadowling(2)

**-1 Weight**
King of the Disk(3 -> 2)
Double Agents(3 -> 2)

**-2 Weight**
Traitor+Changelings(4 -> 2)

### CODE REVIEW

**Comment by banthebantz** [comment]
yes

**Comment by Kierany9** [comment]
Also considering doing the thing suggested on the forum and changing the population requirements for malf and ling, thoughts?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Nudge wizard up by 2 since it's getting no longer disintegrate cancer.

**Comment by banthebantz** [comment]
do it, down with low pop lings

**Comment by McBawbaggings** [comment]
Reduce Cult and add Abductor

**Comment by Spacedong** [comment]
thats some good shit right there also mcbawg abductor isn't a real gamemode lmoa

**Comment by McBawbaggings** [comment]
Doesn't matter, abductor is getting added.

**Comment by Pyko1** [comment]
should just bump up the abductor random event chance

**Comment by blobbernaut** [comment]
Not sure about the actual numbers, but I like the idea of more gamemode variety. Haven't played a cult round in ages myself.

**Comment by ArcLumin** [comment]
Obligatory add nations post

**Comment by oprayx77** [comment]
played my first cult round in ages yesterday,  i agree that tot and ling need to get lowered for 
funstuffs to appear

**Comment by Hackole** [comment]
As bawb said, add in abductor - we had a server poll on that matter

**Comment by trifornt-tinfornt** [comment]
Reduce Cult by 1.
Add Abductor.
Make Abductor 1.
_make wiz 99_

**Comment by Kierany9** [comment]
now with headmin strongarming

**Comment by Anderbergst** [comment]
this is great

**Comment by McBawbaggings** [comment]
I think cult should stay at 1, or be bumped down to 2. Otherwise everything is fine imo.

**Comment by Kierany9** [comment]
Bumped cult down to two because Mcbawbaggings has showed me the aneurysm-inducing pain that is adminning during cult.

**Comment by McBawbaggings** [comment]
+1

**Comment by Hackole** [comment]
kill me +1

**Comment by McBawbaggings** [comment]
THIS NEEDS NALAR TO DO IT

**Comment by blobbernaut** [comment]
oh yeah lmfao btw this won't change anything in game, these are server-side config options

**Comment by Pyko1** [comment]
Call nalar!

**Comment by Kierany9** [comment]
@nalarmg 
i summon thee

**Comment by nalarmg** [comment]
Server side game mode options in the config now reflects this.

**Pull request merged**
