### PR TITLE
Revert "Fartmospherics"

### PR DESCRIPTION
**Pull request by Spacedong**
hey dude, lets add a permastun gas that can't be avoided and completely depletes your stamina

sounds good man 

oh yeah lets make it come out of people every time they fart

# fuck you

### CODE REVIEW

**Comment by gumner** [comment]
just fucking make less gas come out when you fart you absolute dong

**Comment by Spacedong** [comment]
or how about remove it because its a stupid concept

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Every meme PR is unbalanced, per usual.

balancedmyass

**Comment by Spacedong** [comment]
i rest my case

**Comment by gumner** [comment]
make that when your attach your butt,you need to re-do the surgery,you probably dont even need 1 line of code

**Comment by Spacedong** [comment]
also you can literally have this gas be invisible and it still depletes your stamina, holy fuck

**Comment by Spacedong** [comment]
may I also add that scrubbers don't scrub it and don't even have an option to?

**Comment by gumner** [comment]
N2O can be invisible and still knock you out though

**Comment by Spacedong** [comment]
oh wait they do, but its not on by default.

**Comment by Spacedong** [comment]
also, superfarting on a tile makes anyone standing on the tile, in addition to getting 50 brute damage, take constant stamina damage

**Comment by QuarianCommando** [comment]
I agree with this PR.

**Comment by PopNotes** [comment]
Rework, rework, rework.
Rework instead of fucking removing everything like a shitler.
Make fart gas dissipate really quickly and decay much faster, problem solved and you can still choke someone with your ass blasts so long as you stay on the same tile.

**Comment by yobob591** [comment]
lets just remove stuns instead they are unfair

how bout removing stamina too it can get you killed

oh lets remove health cause you can die

**Pull request closed without merging**
