### PR TITLE
Added bear traps to autolathe (hacked).

### PR DESCRIPTION
**Pull request by Spacedong**
Janitor only has 2 and if they're lost they're gone for good. They have a high cost of metal to make so you can't spam the fuck outta em.

### CODE REVIEW

**Comment by Pyko1** [comment]
Oh god, I can see the front of cargo already full of bear traps, just like there is banana peels in front of botany.

**Comment by Spacedong** [comment]
w h y    n o t

also it has a high cost so you need a lotta metal family

**Comment by Carbonhell** [comment]
Spacedong making an actually good PR?
run
fuck
+1

**Comment by Kokojos** [comment]
I running as fast as I can to the :+1:

**Comment by danhibiki** [comment]
OK

**Comment by Nokington** [comment]
wure shatever

**Comment by Cherkir** [comment]
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:

**Pull request merged**
