### PR TITLE
Sec power fixes

### PR DESCRIPTION
**Pull request by Pyko1**
Reduced the amount of lamps in perma/armory, those things are powerhogs and areas are still well lit with less lamps.
Buffed the steam generator to make at least enough power to keep the lamps on at the perma.

### CODE REVIEW

**Comment by Lawligagger** [comment]
Looks good to me.

**Comment by Pyko1** [comment]
still removing few more lamps and possibly splitting the sec hallway to sec hallway area and sec lobby areas.

**Comment by Pyko1** [comment]
Removed some more lamps, split the sec lobby in to its own area.
Fixed some Roundstart AT's at eva maintenance airlock.
The remaining  roundstart AT's seem to be caused by the tubetransit, i think.

**Comment by Pyko1** [comment]
Slightly reduced the buff on steam generator.

Its max output is now 2400W, while perma uses 1529W at idle.
In comparison the P.A.C.M.A.N.-type portable generator has max output of 40000W.

**Comment by Pyko1** [comment]
Moved things slightly around in armory. Nothing added, nothing removed.
capture

**Pull request merged**
