### PR TITLE
Redone Law Office and Detective Office

### PR DESCRIPTION
**Pull request by Spacedong**
-Detective Office now has a noir tileset.
-Law Office now has wooden floors.
-Changed Law Office to not being so loooooooooooooong. 
-Moved some things around in Law Office.
-New maint area in the back of Law Office.
https://vgy.me/7TTCiG.png

https://vgy.me/yI8Q1i.png

### CODE REVIEW

**Comment by carlarc** [comment]
Add a assistant spawn point and it's perfect.

**Comment by Kokojos** [comment]
I can't find out by the code withouth wasting 30 years of my life, so did you check if you CORRECTLY ported the disposal pipes, aka, things sent to the office will go to the office?

**Comment by Kokojos** [comment]
Also, please make sure the maintenance doors have proper access?

**Comment by Spacedong** [comment]
don't merge this yet I gotta find out if they have correct access, also @kokojo I preserved any disposal pipes and stuff from before so if it doesn't work it didn't work before that so idk

**Comment by Kokojos** [comment]
Aight, just asking to be sure.

**Comment by Spacedong** [comment]
alright, the door has proper access and disposal pipes are presumably sound from what I can tell, you can merge it if you want

**Comment by carlarc** [comment]
Hey, make a assistant spawn point. It seems like a perfect place. Of course if you don't want to no but fart

**Comment by Nokington** [comment]
:+1: no on assistant spawn point

**Comment by Carbonhell** [comment]
@Nebyab are you ok with this and @Kokojos did you map-check it, does it have any issue especially with piping

**Comment by Nebyab** [comment]
i dunno sure whatever why not yeah alright good

**Comment by Kokojos** [comment]
seal

of approuval

**Comment by Spacedong** [comment]
neat

**Comment by Carbonhell** [comment]
decent enough,merging

**Pull request merged**
