### PR TITLE
Perma Changes

### PR DESCRIPTION
**Pull request by Pyko1**
Added bowls, fork and drinking glasses to perma kitchen.
Removed 1 maintenance loot spawner from perma area and replaced it with
contraband.
Added conveyor belt to safely deliver items (assistants) to perma.
Moved the isolation down by 1 tile.
Added a gaming table to isolation maintenance so officers can loiter too.
Made a steam generator that burns wooden planks for small amount of power, and added it in perma and above botany.
The generator now also accepts logs, thanks to carbonhell.
Made 1 new tile.
Replaced the perma blastdoors with bolt buttons.
Made anchored portable atmos gear to connect to ports below them at initialize.
capture

### CODE REVIEW

**Comment by Pyko1** [comment]
Added couple steam generators to the maintenance above botany.

**Comment by Carbonhello** [comment]
Did you test if logs work with ..(planks)? Not dure if you need to pass the user in arg too

**Comment by Pyko1** [comment]
Both logs and planks seemed to work as fuel for it, and no errors on my playtest.

**Comment by Chronitonity** [comment]
:-1: on the contraband spawner

**Comment by Pyko1** [comment]
on average its a lot less useful than maintenance spawner it replaced.

**Comment by Chronitonity** [comment]
It can also give a literal cannon so no thanks

**Comment by Pyko1** [comment]
and how many large oxygen tanks there is at perma?

**Comment by Chronitonity** [comment]
seeing how you can use any kind of tanks thats a flawed argument. Still :-1:, contraband shouldnt be spawning in perma

**Comment by oprayx73** [comment]
i like the rubber flap thingy, you can sneak in via a box. badass

**Comment by Pyko1** [comment]
You can only use the large ones, which are not available at perma. And quite frankly illegal items are quite common inside jails. and the maintenence loot spawner has a lot more useful items.

**Comment by Pyko1** [comment]
The maintenace loot spawner has a lot higher chance of having usable items than contraband spawner.

Only usable items in contraband spawner are:
/obj/item/weapon/veilrender/honkrender  1 out of 1880 or so
/obj/item/weapon/baseballbat  2  out of 1880 or so
/obj/item/weapon/baseballbat/metal 10  out of 1880 or so
/obj/item/weapon/switchblade =  5 out of 1880 or so

and anyone with access can just take these items away

**Comment by Chronitonity** [comment]
Shouldn't have that chance at all if you want to put it in an area with prisoners.

**Comment by Pyko1** [comment]
no harm in giving them a minimal chance of escaping if sec is not willing to check random items.
They alreayd hace a chance for toolbox and and shit, Contraband is a lot worse than maintenance if you plan on escaping.

**Comment by Carbonhell** [comment]
How about we remove the straight jackets since they're pratically only used for torturing/pissing off peeps and remove those blast doors aswell ayy

**Comment by Pyko1** [comment]
I kinda like the blast doors to be honest. as they are thre mostly for antigreytide

**Comment by Carbonhell** [comment]
I mean,the ones in permabrig that each hos uses so you cannot do shit like grow plants and cook stuff

**Comment by Pyko1** [comment]
oh those, I agree. We have isolation now.

**Comment by Pyko1** [comment]
i'll replace the blastdoors buttons with jsut the bolt buttons, same as inside.

**Comment by Pyko1** [comment]
Replaced the perma blastdoors with bolt buttons.

**Comment by lcass** [comment]
+1 on the contraband spawner , it's actually useful for possible escapes. The things it gives have stupidly low probablity so you have one round where one guy stabs the warden 3 times then gets cuffed and isolated so what. All the other stuff that spawns is just random stuff that is hardly useful at all such as drugs which there is already a supply of in perma.

**Comment by Pyko1** [comment]
Counted and added the current amount of possible "items" on lootdrops.

**Comment by Pyko1** [comment]
capture

Moved the perma conveyor lever closer to wall.

**Comment by Pyko1** [comment]
capture
Floorgrime version of the bot tile.

**Comment by Pyko1** [comment]
Made anchored portable_atmospherics gear automatically connect to ports below them
at initialize.

**Comment by Pyko1** [comment]
capture
As it is now.

**Comment by Foosili** [comment]
Don't like the contraband, don't like the removal of the shutters. Other than that this is tite.

**Comment by Pyko1** [comment]
To be honest the maintenance loot spawner it replaced, is a lot more useful for escaping.
And the shutters are most of the time used to ensure that the remaining round is ruined for any prisoner, just because you can.
If you really must lock someone in a small cell for rest of the round, the isolation is right there.

**Comment by danhibiki** [comment]
I can dig it.

**Comment by Pyko1** [comment]
Also, if you really really must leave someone stuck in to the small permacells, you can always weld the door.

**Comment by Chronitonity** [comment]
None of the maint shit is as bad as the contraband shit. You can literally get a weapon that spawns 50 clowns from your spawner, that shouldnt have a CHANCE to spawn in perma

**Comment by Pyko1** [comment]
It only spawns 10 clowns that only attack if attacked. And I see no harm of that possibly happening once in average of 1886 rounds.

**Comment by Chronitonity** [comment]
Like before, averages and chances don't matter. Theres a possibility of it happening and it shouldn't even be there.

**Comment by Pyko1** [comment]
Whats the harm in it happening?
Not like its going to be every day occurance, more like once in 100 days or so.

**Comment by Chronitonity** [comment]
Because the chance of a perma prisoner getting a 20 force weapon like the switchblade or a knife that also spawns hostile clown mobs that can fuck up securities day is a huge balance issue. If you honestly think thats okay to happen because it "wont happen every day" then I don't know what to say. It's shit that security can possibly be fucked over because some prisoner got the luck of getting a switchblade and killed him, or used the Honk render to flood perma with clowns, making it unusable and possibly killing an officer or two. 

Its the same thing with you putting an antag spawner in the contraband vendor. Just because its a low chance, doesn't mean it should be there at all. If its there for even one round its not good.

**Comment by doobiedoo23** [comment]
Having the honk render spawn is a really shit idea, even if it's a small chance.

**Comment by Pyko1** [comment]
With same logic the random events/antags should also be removed. As they can also cause someone to die or something.

**Comment by Pyko1** [comment]
Removed honkrenderer, switchblade, baseball bat and metal baseball bat from contraband, no more issues?

**Comment by Chronitonity** [comment]
I guess but you couldve literally just replaced it with a maint spawner instead of removing nice things from a contraband spawner.

**Comment by Pyko1** [comment]
I kinda wanted to make it less likely to get items that allow you to escape.

**Comment by Nebyab** [comment]
Yeah sure

**Pull request merged**
