### PR TITLE
New icons for strange objects

### PR DESCRIPTION
**Pull request by Pyko1**
made by 1Block

### CODE REVIEW

**Comment by Chronitonity** [comment]
Unless block is gonna sprite like 5 more, :-1: We're going from 10~ different objects to 3.

**Comment by block100** [comment]
ill make some more

**Comment by Chronitonity** [comment]
:+1: now, actually much cooler looking than the current objects.

**Comment by danhibiki** [comment]
This looks good

**Comment by Foosili** [comment]
Yes. :+1:

**Pull request merged**
