### PR TITLE
holy fuck you'd think coders didn't go to elementary school or something

### PR DESCRIPTION
**Pull request by Spacedong**
god fucking damn it how can you get something so simple so wrong

### CODE REVIEW

**Comment by ArcLumin** [comment]
pot, meet kettle

**Comment by Spacedong** [comment]
there was no typo in my sentence

**Comment by Hackole** [comment]
Does this really even need head approval?

**Comment by Spacedong** [comment]
no, it is a fix, merge it

**Comment by Pyko1** [comment]
But what happened last time you were fixing typos?

**Comment by JohnGinnane** [comment]
Typo fix, merging

**Pull request merged**
