### PR TITLE
Mapfix & Chefs vender

### PR DESCRIPTION
**Pull request by Pyko1**
Removed derelict cameras that were on ss13 network.
Added more lights to Sec Equipment room, returned disposals bin to Sec_office.
Added a vender for chef to store his food.

capture

Issues fixed:
https://github.com/HippieStationCode/HippieStation13/issues/1822
https://github.com/HippieStationCode/HippieStation13/issues/1818

### CODE REVIEW

**Comment by Cherkir** [comment]
holy shit :+1: :+1: :+1: I've wanted a chef vendor for so long

**Comment by Cherkir** [comment]
10/10 basically second coming of jesus merge this now

**Comment by Cherkir** [comment]
@dragonrobot IMO there should be a way to make flour from sugar and vice versa with chemistry because muh realisms. Botanists never do shit anyway.

**Comment by sp1d3rx** [comment]
> there should be a way to make flour from sugar and vice versa
flour is made from wheat.

**Comment by Cherkir** [comment]
>memetexting on github

Flour is a complex carbohydrate, sugar is a disaccharide

You should be able to make something like flour from sugar by removing enough hydrogen in the sugar bonds. Micro-chemistry and shit fam

**Comment by Pyko1** [comment]
Why stop there, when you could just breath heavily in to an empty flour bag, and have CO2 re-assembled in to a flour?

**Comment by Cherkir** [comment]
@Pyko H O L Y S H I T

coding this now

**Comment by Cherkir** [comment]
Although honestly there should be a Swedish cooking update, involving fine Scandinavian-themed dishes like rotten salted cod(space carp + salt) and blood pudding(blood + enzyme + flour)

they should infect the crew with contagious swedishness

**Comment by Nokington** [comment]
yes

**Comment by danhibiki** [comment]
Yes

**Pull request merged**
