### PR TITLE
Adds Powergamer to Select Equipment verb (50% Done)

### PR DESCRIPTION
**Pull request by Sarcalogo**
Load out is

HoS Cap
HUD Eyepatch
Bowman Captains Headset
Armored Greatcoat
Captains gloves
Brown shoes
Cap's spare ID
Security belt (2 flashbangs, a baton, 2 cuffs)
Captain's satchel
Left pocket = hand tele
right pocket = one cuff
suit storage = captain's laser gun
left hand = riot shield
right hand = energy gun
backpack = medkit, two tasers, surgical drill, box with drapes and a pill bottle of 8 unit meth pills.

Just have to create a new loaded security belt item, a new meth pill bottle item, a new box item that has surgical drapes, internals, and the pill bottle inside. Also have to fix a bug I did not fix...

It's used for admin events, and to make testing things easier. That's about it. It's obviously an admin only thing so...

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
why

**Comment by Crystalwarrior** [comment]
:+1: 
I can actually see this getting some use :^)

**Comment by Nebyab** [comment]
memes

but since its an admin loadout who really cares

sure fine whatever

**Comment by Spacedong** [comment]
na

**Comment by Sarcalogo** [comment]
Also I can't finish this till 

https://github.com/HippieStationCode/HippieStation13/pull/2428

Is merged, because I plan on just using the new loaded by default Security belt instead of the belt Cappy uses.

**Comment by Nebyab** [comment]
since nobody else cared to comment on it, I think we can treat this as dead and buried pretty much tbh

**Pull request closed without merging**
