### PR TITLE
Ghosts can now zoom out using the mousewheel.

### PR DESCRIPTION
**Pull request by Spacedong**
QoL feature ported from /vg/station, gives ghosts the ability to look at the big picture of how bad the station is damaged or in chaos.

obligatory fuckhuge GIF: https://vgy.me/G0aCeG.gif

### CODE REVIEW

**Comment by yobob591** [comment]
amazing marg now

**Comment by SpankMasterson** [comment]
My only issue would be maybe we should make a toggle for this so peopel dont accidentally use scroll wheel and get annoyed.

**Comment by Spacedong** [comment]
I mean, its easily revertable if you accidentally scroll a bit.

**Comment by SpankMasterson** [comment]
yea I dono. I like it and I guess people dont really use scroll wheel anyways, that's just the only problem I can see. I'd +1 this

**Comment by MethMedic** [comment]
Make an option to toggle it cuz zooming crashes me every time

**Comment by doobiedoo23** [comment]
Meth get a computer that can actually run SWAT 4 at over 10FPS then come back to me

**Comment by MethMedic** [comment]
F-FUCK YOU!

**Comment by Spacedong** [comment]
lmao

**Comment by SpankMasterson** [comment]
if it crashes people then yea make a toggle

**Comment by SpankMasterson** [comment]
whoops sorry

**Comment by SpankMasterson** [comment]
i enjoy power

**Comment by Swagile** [comment]
if you make a toggle ill support this

**Comment by McBawbaggings** [comment]
ENHANCE FURTHER DETECTIVE, I THINK I SEE SOME SUSPECT ACTIVITY
+1

**Comment by TDcoolguy300** [comment]
I DEMAND ZOOMING IN

**Comment by JohnGinnane** [comment]
Wow, cool

**Comment by Spacedong** [comment]
do not merge until  I can figure out how to make sure zoom status resets upon ghosts entering back into a new body

**Comment by asskek** [comment]
FUCK THIS BRING BACK TREKCHEM

**Comment by ArcLumin** [comment]
uh, dong
make it client view range not server view range

**Comment by gumner** [comment]
dong will fuck that up and ghosts will be visible and turn into human beings

**Comment by Hackole** [comment]
Neat. +1

**Comment by ArcLumin** [comment]
This should really check for when they are no longer a ghost. I can see lings suiciding, regenerating, and then boosting their view to 14 so they can see across the map, and then regenerating

Also, put a limit on how much they can see or else they'll be crashing up a storm

**Comment by Spacedong** [comment]
@ArcLumin you can't zoom out until infinity, also im working on the former

**Comment by Pyko1** [comment]
approved, and waiting for more dongcode...

**Pull request closed without merging**
