### PR TITLE
Removes Paladin Lawset from AI Upload and Roundstart

### PR DESCRIPTION
**Pull request by Spacedong**
title, since TD and others wanted me to seperate the previous fuckhuge PR into two, here it is

### CODE REVIEW

**Comment by Spacedong** [comment]
crap Ill get changelogs on both, hold on

**Comment by Mithrandalf** [comment]
tbh if antimov is in the upload I dont see why paladin shouldnt be

**Comment by tabsiforu** [comment]
I support making the AI my bitch.

**Comment by Kokojos** [comment]
I agree with the removal at roundstart, not from the upload.
:-1: For now.

**Comment by Dudeinyourbackyard** [comment]
leave it in the upload

otherwise ok

**Comment by Mithrandalf** [comment]
I agree with bruce

**Comment by Pyko1** [comment]
AI should always start with asimov.
But removing this would prolly just result in purge -> Freeform shit.

**Comment by banthebantz** [comment]
Seems silly to remove this from the upload, I don't mind the AI not starting with it though since Corporate is best lawset anyway

**Comment by SplergeBucket** [comment]
no

**Comment by Kokojos** [comment]
2 heads denied.

**Pull request closed without merging**
