### PR TITLE
oh shit what was that noise 

### PR DESCRIPTION
**Pull request by Spacedong**
i didn't hear anything

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Code looks good. Did you test this?

**Comment by JohnGinnane** [comment]
You better test it fam, just to be on the safe side. What you can do is is when you've joined your server you can close byond and join it again and it'll use a guest account (assuming you have that enabled). Just mute one of the clients and superfart on it and see if the unmuted one can hear it with the extra range

**Comment by Spacedong** [comment]
or you can just jump on my test server and help me you kike

**Comment by JohnGinnane** [comment]
Yes

**Comment by Spacedong** [comment]
code confirmed good

**Comment by Spacedong** [comment]
throw the memes tag on there just for fun

**Comment by Dudeinyourbackyard** [comment]
nice

**Comment by McBawbaggings** [comment]
Yeah boy +1

**Comment by JohnGinnane** [comment]
Heads happy, merging

**Pull request merged**
