### PR TITLE
Adds the map changes we used to have v2 + FIXES

### PR DESCRIPTION
**Pull request by Pyko1**
Original PR before dan derped it: https://github.com/HippieStationCode/HippieStation13/pull/1746

The lagging is almost 99.9% sure not a mapping issue.
This re-adds all the fixes and content that had been added to map.

Also includes roundstart AT fix to z2.

Made the nukeops blastco access a bit more bomb/emag proof.
The button is new kind of emagproof_button, generally the same as button, but missing constructing and emagging options.

### CODE REVIEW

**Comment by Pyko1** [comment]
Actually, Ill just rig the BlastCo room with explosives, so if the door gets blown up, everything in the room gets blown up.

**Comment by Pyko1** [comment]
Rigged the BlastCo door/area with explosives.

capture
capture2

**Comment by Pyko1** [comment]
Added 2 more BlastCo Anti-Burglar Payloads to ensure all gear is lost.
capture

**Comment by Pyko1** [comment]
Added the catwalks from https://github.com/HippieStationCode/HippieStation13/pull/1737 with some edits due to map changes.

Since these 2 are going to conflict anyways.

**Comment by SplergeBucket** [comment]
should probably avoid adding what was new arrivals, it wasnt liked
or in better taste ask an admin to run a few polls to gauge opinion

**Comment by Pyko1** [comment]
As far as I know this only addresses some of the issues that was complained about the new arrivals that is already currently in.

**Comment by Spacedong** [comment]
stealing credit for my work huh

**Comment by Pyko1** [comment]
Well either of us had to import all the changes the other made, since these PR's are going to conflict.
No where I have been claiming your work as mine tho.

**Comment by SplergeBucket** [comment]
so with this aint #1737 no longer necessary and therefore we fuck spacedong

**Comment by Pyko1** [comment]
Yeah, I added a changelog crediting him to this PR.

**Comment by nalarmg** [comment]
Needs head input for the arrivals changes - last I checked we were on the fence about reverting it.

**Comment by Pyko1** [comment]
You mean for the "new arrivals" that is already live?

Or for the fixes that this contains for it?

**Comment by Pyko1** [comment]
Fixed Lots of ctags, made the camera coverage better on new areas.
Also Fixed issues with pipes/wires/areas/APC's.

**Comment by Nokington** [comment]
Once the freeze is over, :+1:

**Comment by Pyko1** [comment]
Mime statues and Honk-cooler added to mime/clown offices. Credit to who ever made em.

**Comment by Nokington** [comment]
Sweet

**Pull request merged**
