### PR TITLE
Removes Security Cyborgs and Detective Cyborgs

### PR DESCRIPTION
**Pull request by Spacedong**
split from previous PR

### CODE REVIEW

**Comment by tabsiforu** [comment]
great commit best commit 10/10 reblogging and favouriting

https://github.com/HippieStationCode/HippieStation13/pull/2826 previous pull for reference

**Comment by McBawbaggings** [comment]
Yeah okay +1.
I would prefer secborgs getting move speed nerfed and detective borgs staying removed.
Detective borgs exist to replace the detective solely which is retarded.
Sec borgs are pretty dangerous borgs notoriously played by shitters. Their main drawback should be their laws making them impartial and having a severe detriment to their effectiveness (which I why I suggest they move slower than humans and other borgs)
Although removing them all together is still a preferable state.

**Comment by Pyko1** [comment]
Should still just remove them from selections than completely from code if you insist on removing them as an option.

**Comment by Pyko1** [comment]
And yes that is my opinion on code review, its always better to remove them game, or even comment them out if needed than straight out delete the code.

**Comment by calibraptor** [comment]
Just comment them out rather than deleting them outright.

**Comment by Kokojos** [comment]
As said before, would prefer a nerf to outright removal/outcommented.

 :-1: from me.

**Comment by banthebantz** [comment]
If you really hate them that much then just nerf them as multiple Kokojo said.

**Comment by tabsiforu** [comment]
"nerfing them" isn't a clearcut solution, the same as "removing them" is. it helps to be willing to discuss the intimate mechanics of the game and how they affect the players as opposed to giving vague suggestions.

**Comment by GeneralGoose** [comment]
@Kokojos @banthebantz if you say to nerf them then say how

**Comment by Kokojos** [comment]
Ways to nerf :
- Slower speed
- Special laser substype that does less stamina damage.
- Increased cost from zero to 200 per shot
- Limited number of shots

**Comment by GeneralGoose** [comment]
cool now you should make a pr

**Comment by blobbernaut** [comment]
What the fuck it costs 0?

**Comment by tabsiforu** [comment]
If we're talking about game mechanics, we should also talk about how the secborg fits in with the whole security dynamic, seeing as of now players tend to murderbone with it instead of following their laws.

**Comment by SplergeBucket** [comment]
no, do wot kokojo sayeed or rnd research wall

**Comment by Nebyab** [comment]
secborgs are bad

**Comment by Nebyab** [comment]
to follow that up

rnd research wall

so if you really want to be a secborg it requires interacting with other people to achieve it

**Comment by LufgtHuron** [comment]
How is this change good? All it takes to kill a borg is a flash/RDs level access ID. And considering how easy it is to break into robotics/tech storage and get a flash AND how often it happens, this change is pointless. 

Seems to me there's just lots of unrobust complainers here that can't handle the borg. Besides, the real problem here isn't how powerful borgs are (because they arent) but its their laws and abuse of them by shitcurity. I we want to remove security borgs we might as well remove shitcurity completely because in all the time I played, it happened way more often that I was perma'd by a piece of shit HoS for some meaningless item instead of an overzealous borg.

**Comment by danhibiki** [comment]
@LufgtHuron stop with that, the players are suppose to hate secborg and detborgs, your ruining the circlejerk

**Comment by GuyonBroadway** [comment]
My issue with Detborgs is how much they overlap with secborgs. If a Detborg had a module that gave it remote medical and security records access with a search function that would be pretty fucking handy to have. 

A Detective could have their borg buddy check recods of stuff they've found without having to trek back to Security.

**Comment by blobbernaut** [comment]
I approve of this because of one fucking reason.

Emagged sec borgs.

**Comment by Uqualm** [comment]
Hippiestation turning into baby station /tg/ rip off with NO FEATURES. No wonder the player count is down the drain. RIP Kitty Kathy

**Comment by Limed00d** [comment]
Stop acting as if this pr has been accepted yet lmao

**Comment by SplergeBucket** [comment]
yeah bro its okay ur waifu is dead and the dream may also be dead but the server is dying not dead ffs get it right

**Pull request closed without merging**
