### PR TITLE
Atlas Canvas

### PR DESCRIPTION
**Pull request by Pyko1**
Ports atlas canvas, this is apparently an improved version of the canvas we are currently using.
I slapped our burn states on the new content so we can always burn em if we don't like it.
atlascanvas

Credits to crystalwarrior and Atlas Coders.

### CODE REVIEW

**Comment by Pyko1** [comment]
atlascanvas

**Comment by Spacedong** [comment]
aren't canvases currently buggy as shit on hippie, ii remember trying to draw something and it kept flashing and I kept drawing on the floor instead, is all that shit fixed?

**Comment by Pyko1** [comment]
Didn't have any issues drawing on my test server at least.

**Comment by danhibiki** [comment]
Sure

**Comment by Nokington** [comment]
why not

**Pull request merged**
