### PR TITLE
fixed some bullshit

### PR DESCRIPTION
**Pull request by Spacedong**
ay

### CODE REVIEW

**Comment by McBawbaggings** [comment]
Less info than my flux PR somehow.

**Comment by McBawbaggings** [comment]
But yeah sure the changes are fine +1

**Comment by GuyonBroadway** [comment]
call it "real villains suit" and its good.

**Comment by GuyonBroadway** [comment]
because it's the suit of a real villain

**Comment by KittyKathy** [comment]
Do we have a Memes label? also pretty sure villains would need more protection than 10 melee...

**Comment by McBawbaggings** [comment]
It's a cosmetic item that makes you scream robbie rotten lines. It shouldn't be viable armor.

**Comment by KittyKathy** [comment]
Well then when are we going to add traitor only versions with upgrades to replace the mind slave gang leader bundle?

**Comment by GuyonBroadway** [comment]
Oh heck yes we should add a gang uniform version. 

We could make the non gang version the "Villain's outfit" and the Gang version the "Real Villains outfit!"

**Comment by Spacedong** [comment]
be careful not to make a sound!
_guy steps on bear trap in maintenance_
NO DON'T TOUCH THAT

**Comment by McBawbaggings** [comment]
>Robbie Rotten Gang

FUND IT.

**Comment by banthebantz** [comment]
>Real Villain Gang

The only guys who can counter Rigatoni and their Krav Magooba

**Comment by Anderbergst** [comment]
looks good

**Comment by SpankMasterson** [comment]
seems dangerous, did you check the code? +1

**Comment by Spacedong** [comment]
yes

**Comment by Scinexx** [comment]
change the DIO outfit to vampire clothes while your at it

**Comment by blobbernaut** [comment]
Ok +1

**Comment by ArcLumin** [comment]
Code's good, head approved, mergan

**Pull request merged**
