### PR TITLE
Shadowling tweaks boogaloo

### PR DESCRIPTION
**Pull request by blobbernaut**
This has been a long time coming. They're literally unbeatable right now.

This nerfs shadow walk by a huge amount: 300 ticks to 900 and the duration to 3 seconds, from 4 seconds. I want it to be more of a "Holy shit, I'm stunned, being shot at, abort abort" spell. I'm considering removing it from them period and having them start off with blindness smoke, or drain life, for that same purpose.

In return, shadowlings get a knock ability to open doors. It's literally the wizard's knock spell. So shadowlings that don't have maint access can play the game too. 

Thrall glare range has been reduced to 5, from the whole screen.

Shadowlings heal 20% slower in darkness.

Super thralls, from the revive spell, heal twice as fast in darkness.

Superthralls get both knock and shadow walk.

Removes icy veins as a starting spell. It is now unlocked with 9 thralls.

Changes thralls needed to 20. Am willing to remove this bit, I just think that late game shadowling spells see almost no use.

Nerfs ascendants to be actually killable, for adminbus purposes. 75 shots from a pulse rifle oughta do one in, the singularity or a large bomb will also work. But no regular damage short of a pulse rifle will even scratch them.

Ascendants now do less damage per attack and attack stupidly fast. Their gibbing spell has a cooldown and has the range nerfed. Actually makes it somewhat easier to use as it won't pull up a huge list all the time.

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
:+1:

**Comment by Sarcalogo** [comment]
You guys really never want Shadowlings to win do you? 210 seconds? You realize how long that is right? You do realize how easy it is to shut down MOST shadowlings once they are caught right? You are way too overzealous with nerfs. There are much easier ways to balance shadowlings without making them garbage.

As for Ascendants, they are supposed to be overpowered. And there is literally no point to nerfing them.

**Comment by Crystalwarrior** [comment]
On second thought I honestly don't even have any say in this, I have no idea what shadowlings are and how they work. :V

**Comment by doobiedoo23** [comment]
this is dumb

**Comment by blobbernaut** [comment]
Of course you'd be the one to be against this sarc.

**Comment by blobbernaut** [comment]
great input doobie

**Comment by doobiedoo23** [comment]
ok better input 4u
ascendants are /meant/ to be unkillable
210 second cooldown is the dumbest shit i've ever heard
antags don't need to be perfectly balanced, stop trying to nerf everything, i've seen shadowlings lose a ton

**Comment by blobbernaut** [comment]
I should just make ascendants cause the end of the round then

I haven't, I honestly can't remember a single time in the past several months where shadowlings have all been killed. They're literally impossible to kill if they're good.

**Comment by Spacedong** [comment]
why nerf ascendants?????????? thats dumb

shadowwalk is terrible and has needed a nerf for some time

**Comment by blobbernaut** [comment]
the only thing they're nerfed to is round end adminbus really

**Comment by dreamcrab** [comment]
ascending does call the shuttle, dude?? doesn't it? either way I am not a huge fan of nerfing shadowlings. there are a few good options we already went with

**Comment by blobbernaut** [comment]
like what? I still haven't seen the crew kill the lings ONCE in months.

**Comment by blobbernaut** [comment]
Making thrall glare not work against eye protection doesn't change the fact that shadowlings can jaunt on a 30 second cooldown, a jaunt which removes all stuns from them. Jaunt is just far too good. So good in fact, that they effectively immortal as long as they know what it does.

**Comment by trifornt-tinfornt** [comment]
Shadow Walk needs to be more like ethereal jaunt. Adding Knock is a good idea, but I feel like you want to trash Shadow Walk down to Knock. This is a terrible idea because Knock will end up removing the Shadowling's ability to jump through maint without being spotted.
Shadow Walk can be fixed by:
slowing it down a tid.
giving it a start-up delay.
not letting you must when stunned while shadow walking.
That way it isn't the "LOL I GOT STUNNED NOW I'M IN ENGI MAINT" but it still lets Shadowlings not have Sec immediately arm up with laser guns because they walked down the hall trying to get to another maint and some cargonian saw them.
Icy Veins nerf is called for. Thank you.
Also, Superthralls are suddenly viable? This feels more like a "makes Shadowlings more fun for the thralls" change if anything - so thanks again.

Also nerfing Ascendants is dumb. Deal with it, they won, shuttle is called and arrives in three minutes. Making them NOT immortal to reward those who won and then I'd question why something like Nar-Sie can't die from pulse rifles. Nerf Nar-Sie!

**Comment by blobbernaut** [comment]
well ascendants aren't gods, just really powerful psychics. What kind of god can run off the power of 15 regular old humans? 

thanks for the input though. The primary changes of this are:

Shadow walk cooldown tripled
Icy veins replaced with knock, icy veins unlocked with 9 thralls
thralls needed upped to 20 (This should really be dynamic, we need to decide on a good number)

**Comment by trifornt-tinfornt** [comment]
15 thralls is fine for me for the sole reason of "Cult is even easier to get converts, and it requires only 9 50% of the time" and the fact that Slings isn't very fun - so the faster it's over the better.

**Comment by blobbernaut** [comment]
that's actually a great argument for keeping it at 15.

**Comment by blobbernaut** [comment]
I really don't care if this is the form the nerfs take, I just think that icy veins needs to be replaced, and shadow walk needs a nerf. If you have any input on this suggestion, feel free to share it or other ideas for how to balance them. Shadowlings are just far too slippery.

**Comment by McBawbaggings** [comment]
Ascendants should still be unkillable.
Ascend count should be 15.
Otherwise, good shit. There should be the reward of ascending but it should be tough. Knock change is great for non-maint shadowlings.

**Comment by blobbernaut** [comment]
I'm closing this and reopening it because of a bug with my github client on this branch

**Pull request closed without merging**
