### PR TITLE
Random Contraband spawner for armory

### PR DESCRIPTION
**Pull request by Pyko1**
Made a random contraband spawner that spawns 10 random contraband items in the contraband locker at armory.
Removed 1 stray tile at space.

### CODE REVIEW

**Comment by Chronitonity** [comment]
Yes

**Comment by lcass** [comment]
Honk render? Remove that or you will have lots of dead pepes.

**Comment by danhibiki** [comment]
Totally for this, why not

**Comment by Nebyab** [comment]
yeah sure

**Pull request merged**
