### PR TITLE
Merge ASAP I fucked up

### PR DESCRIPTION
**Pull request by Kierany9**

### CODE REVIEW

**Comment by Kierany9** [comment]
>min_temperature = min(0,T0C - (170 + (T*15)))

Instead of preventing freezers from obtaining negative temperatures, I did the exact opposite and made them only accept negative temperatures.

good fucking job me and good fucking job whoever codechecked

**Comment by McBawbaggings** [comment]
TEST UR FUKKEN PRS

**Comment by TDcoolguy300** [comment]
http://i.imgur.com/tTyVIEQ.gif

**Comment by McBawbaggings** [comment]
I'll wait for travis, merge and force an update.

**Pull request merged**
