### PR TITLE
Revert "Adds clocks"

### LINKED ISSUE #3368: clocks are retarded
shitty sprites that conflict with the artstyle, they're all at different positions, and they appear outside of the room they're supposed to be in because whoever added them to the map didn't fucking offset them

### PR DESCRIPTION
**Pull request by Spacedong**
Fixes #3368

### CODE REVIEW

**Comment by gumner** [comment]
stoopid

**Comment by GuyonBroadway** [comment]
Improve not remove!

**Comment by MethMedic** [comment]
Dongtism strikes again

**Comment by MethMedic** [comment]
Also yea improve not remove you nigger

**Comment by yobob591** [comment]
spacedong is autistic, but its not like we didnt already know that

**Comment by JohnMcLaime** [comment]
Those clocks every few tiles are autistic, you got a pda to check the round time, it only serves as an excuse to end round earlier for people.

**Comment by yobob591** [comment]
what if someone steals your PDA ngiger

**Comment by tortellinitony** [comment]
"fixes #3368" when it's your own issue lmao

**Comment by JohnMcLaime** [comment]
If your pda got stolen, station time is your least concern,

**Comment by gumner** [comment]
LEAVE DUWANG

**Comment by QuarianCommando** [comment]
Let's be honest here, Dong is just looking for an excuse to delete code.

**Comment by Kierany9** [comment]
I mean, they look like ass.

**Comment by MethMedic** [comment]
Just resprite then, a removal is retarded

**Comment by banthebantz** [comment]
Improve don't remove you lazy cunt

**Comment by JohnMcLaime** [comment]
Why the fuck do we need a clock every few tiles? Maybe add that clock code to newscasters?

**Comment by SpankMasterson** [comment]
-1 imrpove the sprite dont delete, why do u hate clocks? bro?

**Comment by JohnMcLaime** [comment]
Just give that "current time" examining line/code to a newscasters, they at least dont look like shit and even if they looked like shit, at least they arent spammed on every wall every other few tiles.

**Comment by Kierany9** [comment]
https://github.com/HippieStationCode/HippieStation13/issues/3382
https://github.com/HippieStationCode/HippieStation13/issues/3381

Revert dis

**Comment by ArcLumin** [comment]
Okay looking at the issues I say we should revert as they're causing more issues than they're helping.

**Comment by Pyko1** [comment]
revert, and author can add the fixed version to rebase since its approved content.

**Comment by Spacedong** [comment]
revert it, they look like ass and you can see the station time in your status bar at all times anyway

**Comment by dreamcrab** [comment]
yea the clocks are fuckin bad lmao

**Comment by Dudeinyourbackyard** [comment]
yeah we can improve it on the rebase
revert dis bitch

**Comment by ArcLumin** [comment]
Reverting since issues

**Pull request merged**
