### PR TITLE
Reworks a lot about how armor works and re-adds armored cloaks

### PR DESCRIPTION
**Pull request by blobbernaut**
IN PROGRESS. Just wanted to put this up here for code review, not 100% sure what else I'm going to add but I have a few ideas. Some sort of pin that you can tag onto your jumpsuit that blocks energy by a bit? Why not.

Short list: 
*Armor stacks multiplicatively instead of additively. This prevents situations where armored jumpsuits and stuff let the wearer stack to 100% protection.

*Cloaks in the heads start with can be toggled to fit on the back or on the chest. They function as reduced capacity backpacks while on the back, but provide armor. 

*Accessories can now have armor. Attaching to a jumpsuit increases the jumpsuit's armor value by the armor of the accessory. 

*Explosion damage and chance to stun is now is properly reduced by bomb armor, instead of doing basically nothing. As of now this is a strict nerf to the lethality of explosions, but it would be easy to change it so explosions are more lethal against unarmored targets, having a tiny bit of armor go a long way, etc. Feel free to discuss your opinions.

*Slime feeding is now protected against by bio armor. A bio suit with 100 bio armor will protect completely against the clone damage, leaving only a small bit of toxin damage.

*Xeno spit weaken is now protected against by bio armor as well, instead of bullet armor. Labcoats and such will reduce your stun time, while a bio suit will make you immune to spit.

*Adds permability coefficient to labcoats, they will now properly guard against disease contraction.

*Jackboots and engineering shoes given the same temperature protection as black shoes.

### CODE REVIEW

**Comment by McBawbaggings** [comment]
>Those commits.

Respective +1 from the old PR

**Comment by dreamcrab** [comment]
i like a lot of the concepts in here, especially the bio damage from xenos and slimes. seems cool

**Comment by carlarc** [comment]
Y E S

**Comment by blobbernaut** [comment]
Since reception has been positive so far, I'll talk a bit about how cloaks will work, as they are the prime example of how the new armor system works. Basically, you can think of it like each new piece of armor acting independently on the damage that remains after the previous bit of armor blocks it. Two pieces of armor that are both 40? That's 0.6 as a fraction of incoming damage, (0.6)*(0.6) = 36% incoming damage, or 64 effective armor.

On the back, they will have 5/7 the storage capacity of a backpack, able to hold 15 tiny items (paper, shards), up to 5 normal size items (energy guns, boxes). On the torso, they have capacity and size limit equivalent to two extra pockets.

The HOS cloak:
armor_backslot = list(melee = 30, bullet = 13, laser = 25, energy = 8, bomb = 20, bio = 0, rad = 0)
armor_exoslot =  list(melee = 50, bullet = 20, laser = 40, energy = 12, bomb = 30, bio = 0, rad = 0) //greatcoat is 50, 30, 50, 10, 25, 0, 0

Combining this with a greatcoat and sec jumpsuit gives: 
70 melee,  39 bullet, 62 laser, 17 energy, 40 bomb, 0 bio 0 rad.
Seem overpowered? Probably is! Give feedback on these numbers and i'll change them. 

again that 70 comes from the 15 from sec jumpsuit too, so together you get 
(1-(100-15/100)*(100-25/100)*(100-50/100)) * 100 = 70.25 armor
...............^sec suit........^back cloak....^armored greatcoat

The captain's cloak:
armor_backslot = list(melee = 25, bullet = 20, laser = 25, energy = 13, bomb = 20, bio = 20, rad = 20)
armor_exoslot =  list(melee = 40, bullet = 30, laser = 40, energy = 20, bomb = 30, bio = 30, rad = 30) 

Hey hackole I don't know if i'll increase these numbers but there's plenty of room to go down.

Other cloaks:

**Comment by blobbernaut** [comment]
Owl's cloak
body_parts_covered = CHEST|GROIN|LEGS|ARMS
var/armor_backslot = list(melee = 30, bullet = 30, laser = 15, energy = 15, bomb = 30, bio = 20, rad = 20)
var/armor_exoslot =  list(melee = 60, bullet = 60, laser = 30, energy = 30, bomb = 60, bio = 40, rad = 30)

CMO Cloak:
icon_state = "cmocloak"
permeability_coefficient = 0.05 // Blocks disease super gud.
armor_backslot = list(melee = 10, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 40, rad = 15)
armor_exoslot =  list(melee = 20, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 80, rad = 30)
flags = THICKMATERIAL // blocks syringes.

CE Cloak:
armor_backslot = list(melee = 10, bullet = 0, laser = 10, energy = 10, bomb = 15, bio = 0, rad = 40)
armor_exoslot =  list(melee = 20, bullet = 0, laser = 20, energy = 20, bomb = 30, bio = 0, rad = 80)
heat_protection = CHEST|ARMS
max_heat_protection_temperature = FIRE_SUIT_MAX_TEMP_PROTECT
cold_protection = CHEST|ARMS
min_cold_protection_temperature = FIRE_SUIT_MIN_TEMP_PROTECT

RD Cloak:
armor_backslot = list(melee = 0, bullet = 0, laser = 0, energy = 25, bomb = 30, bio = 30, rad = 0)
armor_exoslot =  list(melee = 0, bullet = 0, laser = 0, energy = 50, bomb = 60, bio = 60, rad = 0)
permeability_coefficient = 0.5
heat_protection = CHEST|ARMS
max_heat_protection_temperature = FIRE_SUIT_MAX_TEMP_PROTECT

**Comment by McBawbaggings** [comment]
>Effective health didn't exist before doda
Didn't exist in the very game it came from

Oy vey

**Comment by blobbernaut** [comment]
Bomb armor!

Bomb armor now reduces damage taken and chance to be paralyzed.

**Comment by Pyko1** [comment]
what about a chance of losing a limb?

**Comment by blobbernaut** [comment]
Yes that too

**Comment by carlarc** [comment]
did you know you can clip a flashlight to shadowling exosuit

**Comment by blobbernaut** [comment]
Anybody got more ideas for this

**Comment by dreamcrab** [comment]
i still like this idea, but i need to spitball it a bit more. if anyone has any suggestions feel free to throw em out

**Comment by danhibiki** [comment]
I could be totally off base here, but isn't multiplicative not a good way to go about this, especially since your multiplying the products to themselves?

Like if you had gloves that gave 15% defense from brute and a helmet that did 20%, your end product would be 3% defense (0.15*0.2). Unless I'm missing something, what you would want is diminishing returns, not a multiplicative product.

**Comment by McBawbaggings** [comment]
It is diminishing returns, you'd get 32 armor as opposed to 35.

**Comment by danhibiki** [comment]
I see now, I didn't even look at the code, I just read a comment

**Comment by Carbonhell** [comment]
News on this PR?Is it still being developed? @blobbernaut

**Comment by blobbernaut** [comment]
Yeah but i want feedback on the current stuff before adding more

**Comment by Nebyab** [comment]
i dunno sure. I'm still hesitant about this.

**Comment by Spacedong** [comment]
neat but I think workboots should have increased heat protection since ya kno

**Comment by calibraptor** [comment]
@Spacedong Lrn2Read nerd he said in this PR that engineering footwear gets protection too.

**Comment by Spacedong** [comment]
@calibraptor *Jackboots and engineering shoes given the same temperature protection as black shoes.

are you fuckin stupid

**Comment by blobbernaut** [comment]
engineering shoes are the workboots right? The yellow, ugly ones?

also nebyab, what parts of this do you agree with and disagree with. Being hesitant about this doesn't really give me insight on what to change considering this touches quite a few different things and has a couple bug fixes as well as balance changes and features. If you could let me know your opinion on the things this changes on a more individual level that'd be cool.

**Comment by blobbernaut** [comment]
Considering the lack of balance discussion I'm asking for, how bout this, I could break up this rework into it's individual components and make separate PR's for each. Or somebody could read through it and let me know what they think about it piecewise. 

I could definitely add more to this, but not until I see some tangible feedback on the existing bits.

**Comment by blobbernaut** [comment]
hello

**Comment by Gandalf2k15** [comment]
hi

**Comment by Carbonhell** [comment]
Need news, or this pr will be considered dead and will be closed

**Comment by blobbernaut** [comment]
The news is that I am done working on this, and that I am waiting for the heads to talk with me about each particular change. I'll contact them on slack and make em look it over with me.

**Comment by McBawbaggings** [comment]
>*Armor stacks multiplicatively instead of additively. This prevents situations where armored jumpsuits and stuff let the wearer stack to 100% protection.

Considering how you're only gonna have 2 sources of resist for each region, it's an okay change since it solves the issue of 100% armor stacking.

>*Cloaks in the heads start with can be toggled to fit on the back or on the chest. They function as reduced capacity backpacks while on the back, but provide armor.

I don't object to this considering that I never see cloaks getting use.

>*Accessories can now have armor. Attaching to a jumpsuit increases the jumpsuit's armor value by the armor of the accessory.

I like the idea of medals importance being the fact they are medals, and not stat items. I don't object to the functionality per say but more so implementing damage resisting accessories

>*Explosion damage and chance to stun is now is properly reduced by bomb armor, instead of doing basically nothing. As of now this is a strict nerf to the lethality of explosions, but it would be easy to change it so explosions are more lethal against unarmored targets, having a tiny bit of armor go a long way, etc. Feel free to discuss your opinions.

I guess this is changing to something to work as intended? It seems fine either way.

>*Slime feeding is now protected against by bio armor. A bio suit with 100 bio armor will protect completely against the clone damage, leaving only a small bit of toxin damage.

Cool idea, I like to see biosuits get more use but this feels more like a crutch rather than it being useful on its own accord.

>*Xeno spit weaken is now protected against by bio armor as well, instead of bullet armor. Labcoats and such will reduce your stun time, while a bio suit will make you immune to spit.

I like this, makes biosuit hoods even better.

>*Adds permability coefficient to labcoats, they will now properly guard against disease contraction.

Changing to something to work as intended. Seems good.

>*Jackboots and engineering shoes given the same temperature protection as black shoes.

Yeah okay.

**Comment by Spacedong** [comment]
was this ever completed? what is going on with this PR?

**Comment by blobbernaut** [comment]
This is completed yes but nobody reads the new posts aaaaaaaaaaa

**Comment by Spacedong** [comment]
2 head approval, fuckin merge this, its ready to go, remove do not merge label

**Comment by blobbernaut** [comment]
Look honestly these numbers are probably not perfect, bomb protection could still use tweaking especially, but hell

i'm not going to know how to tweak this optimally without seeing it in practice, so if you agree with the principles of this PR just say so

**Comment by Gandalf2k15** [comment]
Awaiting code check for merge.

**Comment by Gandalf2k15** [comment]
Code is fine, @blobbernaut is this good to go?

**Comment by Gandalf2k15** [comment]
All checks passed, criteria met, merging.

**Comment by blobbernaut** [comment]
this somehow made captain's gloves invisible even though i don't touch them anywhere, what

**Pull request merged**
