### PR TITLE
fixes giant tajaran species typo

### PR DESCRIPTION
**Pull request by Spacedong**
its spelled "tajaran" not "tarajan" you fuckin idiot whoever coded this

### CODE REVIEW

**Comment by McHatters** [comment]
literally unplayable

**Comment by Spacedong** [comment]
aye

**Comment by McBawbaggings** [comment]
yeah okay? +1

**Comment by Pyko1** [comment]
kitty lover spotted!

**Comment by ArcLumin** [comment]
what a pussy

**Comment by dreamcrab** [comment]
just rename it to catbeast

**Comment by doobiedoo23** [comment]
do it

**Comment by Nebyab** [comment]
>tarajan 
ech

+1

**Comment by Spacedong** [comment]
2 head approval, merge

**Comment by ArcLumin** [comment]
Is this only for giant tajarans?





:^)

**Comment by SplergeBucket** [comment]
its called catbeast you fuckin faggots

**Comment by Pyko1** [comment]
apparently approved by catlovers heads.

**Pull request merged**
