### PR TITLE
Slight reactive teleport armor nerf.

### PR DESCRIPTION
**Pull request by Sarcalogo**
Lowers the activation rate by half and adds a slowdown effect. As discussed in https://github.com/HippieStationCode/HippieStation13/pull/1872

### CODE REVIEW

**Comment by GunHog** [comment]
Heh, you Hippies have an odd definition of "Slight".

**Comment by Carbonhell** [comment]
Isn't slowdown 3 pretty big?Also..There are so many commits, can you squash them in one,by any chance?I'm unsure how to do it,never had to..

**Comment by Sarcalogo** [comment]
The last commit is the only relevant one, the others are from the prior PR. I dunno how the fuck GitHub works or how to get a "clean slate" so nothing I can do. It's not that big of a slowdown at all considering people will most likely be using drugs all the time to counteract the slowdown.

**Comment by Memendia** [comment]
No mentions of CamilleNerf :c :-1: 

Good update :+1:

**Comment by Sarcalogo** [comment]
There are more Camille nerfs coming if that's what you want to call them. Namely changing how Meth works (it won't decrease .Weaken similar to how Crank doesn't), removing chemical implants... uh... then there are the dental implants, not sure what to do about that. Someone will figure it out.

**Comment by Pyko1** [comment]
reactive

Seems pretty ridiculous slowdown.

**Comment by danhibiki** [comment]
Thats the highest slowdown of the entire game, especially on any piece of clothing. Set it to 1 if anything. And yes, its intended for it to still slow you down in hand @Pyko1 , its a measure that was introduced to stop people from taking their exo suits off and keeping them in hand to run faster down the halls.

**Comment by danhibiki** [comment]
Yes, you can use fractional numbers.

**Comment by TDcoolguy300** [comment]
I dont know why this needs a code review, but the code is fine

**Comment by nalarmg** [comment]
All PRs (technically) need code review by default, so it probably doesn't really matter.

 Needs more headmin input.

**Comment by Spacedong** [comment]
i want this please

**Comment by Nokington** [comment]
The slow down should be the same as riot armor.

**Comment by Sarcalogo** [comment]
It has a slowdown of 1 now, the same as Riot Armor.

**Comment by Nokington** [comment]
:+1:

**Comment by nalarmg** [comment]
Further head input needed.

**Comment by Carbonhell** [comment]
If you can squash your commits( https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ ) ,the pr should be good to go

**Comment by Sarcalogo** [comment]
kek. Well the combined commit counts as a new commit so now I have even more commits.. Maybe I should use your guide instead.

**Comment by Sarcalogo** [comment]
Nope sorry. That guide is the same as the other one. It doesn't do anything.

**Comment by Sarcalogo** [comment]
FUCK GITHUB

**Comment by Nebyab** [comment]
Honestly I'd rather just see this dead as a roundstart thing. The RD doesn't need it, it makes no sense that he'd have it, just make it tied to bluespace,materials and combat in R&D or something.

**Comment by Sarcalogo** [comment]
Nebyab, buddy. I tried that already made it researchable but Dan and Nokington disagreed. Anyway, shit was fucked. Had to delete my whole repository. I learned how to use GitHub though! Lesson learned. Don't commit changes to your master branch.

**Pull request closed without merging**
