### PR TITLE
Nerfs the reactive teleport armor.

### PR DESCRIPTION
**Pull request by Sarcalogo**
Lowers the activation rate by half and adds a slowdown effect. As discussed in https://github.com/HippieStationCode/HippieStation13/pull/1872 and https://github.com/HippieStationCode/HippieStation13/pull/1881

It already has had head approval and a code review, I was asked to squash all the commits into one which was impossible without deleting the repository (good thing there wasn't much on it).

### CODE REVIEW

**Comment by Nokington** [comment]
:+1: Ill bug @Nebyab to respond again since he thought it should be researchable which is dumb imo because we dont need more than one of these things around. I am all for just flat removing it though if Neb and @Lawligagger agrees.

**Comment by Nebyab** [comment]
Noking, I sai remove it from the R an make it an R& item instea mate. Make it a high tier thing that has to be worke towars, because then it makes sense an becomes a neat rewar, but this is also a tolerable solution for the foreseeable future.

**Comment by Nokington** [comment]
All I can see if we make it into R&D is multiple of them around the station. Which would be bad

**Comment by Sarcalogo** [comment]
I wanted to outright remove it as well. 

I originally made it so it cost a shit load of materials and required really high research levels. You can check that out.

`+/datum/design/armor/reactive  
 279   +	name = "Reactive Teleport Armor"  
 280   +	desc= "Someone seperated our Research Director from his own head!"  
 281   +	id = "reactive"  
 282   +	req_tech = list("materials" = 7, "combat" = 6, "powerstorage" = 6, "magnets" = 6, "programming" = 6, "bluespace" = 7)  
 283   +	build_type = PROTOLATHE  
 284   +	materials = list(MAT_METAL = 25000, MAT_GLASS = 10000, MAT_SILVER = 20000, MAT_GOLD = 20000, MAT_PLASMA = 6000, MAT_DIAMOND = 2000)  
`
If you can both agree on that, I'd much rather push that than this slight nerf which in my mind doesn't do much to solve the issue. 

As for it being wildly available. Hah. At that point in the game, if you have that much research and mats than that's the least of your problems as shit has gone to hell already. Just tell me what you think.

**Comment by Nokington** [comment]
We have players that can literally max research five minutes in. Combine that with a good miner and everyone has bags of holdings at 15 minutes in

**Comment by Sarcalogo** [comment]
As far as I know, Bluespace 7 requires items not normally acquirable, like abductor gear. I know you can power game it, but it rarely happens.

**Comment by Nokington** [comment]
Eh alright. Put it in RnD

**Comment by Sarcalogo** [comment]
It's done.

**Pull request merged**
