### PR TITLE
Food & Plant spawners

### PR DESCRIPTION
**Pull request by Pyko1**
Added random spawners for plants and food
10 random plants at garden instead of static ones.
1 random food at the kitchen table
Moved the vent and lamp next to the wall at the 2 "premium" dorm rooms.
Made the theater backroom lighting better.
Added some more rats (8 or so) around maintenance so we can have decent amount of rat burgers, if anyone wants to go hunt em.

### CODE REVIEW

**Comment by Chronitonity** [comment]
:-1: Kitchen fridge already has some plants in it, let botanists actually do their job instead of spawning more plants for people.

**Comment by Carbonhello** [comment]
Gotta agree with Chron,it would become way too easy.

**Comment by Pyko1** [comment]
If it has plants, then those should be removed as well. Having 10 plants wont get you far, just means you have small random variety to start cooking with at the round start.

**Comment by Carbonhello** [comment]
I meant fridge plants plus yours. IMO my ones in the fridge are enough, i am OK with alla the other changes through..i'd like to keep donuts thro

**Comment by Pyko1** [comment]
If I'm chef, I'd rather have selection of random plants, instead of the same things every round.
But removing the ones at fridge that i didint know of.

**Comment by Carbonhello** [comment]
Well then to do that you could easily edit the smartfridge/kitchen new proc. It'd be way easier than just map them in imo

**Comment by Chronitonity** [comment]
Still a staunch :-1: On actual food being on a spawner, just make it plants instead of this.

**Comment by Pyko1** [comment]
cant really make it random variety without spawner?

**Comment by Chronitonity** [comment]
I'm okay with a plant spawner, not a food spawner

**Comment by Pyko1** [comment]
whats wrong with it, it barely makes any more food than the donuts its replaces, I guess i could even reduce the spawnpoints down from the current, and the list has no harmful foods in it.

**Comment by Chronitonity** [comment]
We want the chef do have a job to do, not to spawn food for him. The plants being spawned are for in case botanists arent around.

**Comment by Pyko1** [comment]
well there are donuts on the desk at the moment, this just replaces them, and adds a food spawner if its ever needed.

**Comment by Chronitonity** [comment]
Just put the random food in the kitchen fridge, keep the donuts there as they heal security, and don't put a food spawner on the map, thats all this needs to do.

**Comment by Pyko1** [comment]
There are now 10 random foods at garden instead of static ones.
And 1 random food in top of kitchen microwave.

And the spawners in code of course, ultimately would be neat to have random plants in the smartfridge, but I'm not a coder.

**Comment by Pyko1** [comment]
also moved the lamps and vents next to wall at premium dorm rooms and upgraded the theater backroom lighting.

**Comment by Pyko1** [comment]
Added random spawners for plants and food
10 random plants at garden instead of static ones.
1 random food at the kitchen table
Moved the vent and lamp next to the wall at the 2 "premium" dorm rooms.
Made the theater backroom lighting better.
Added some more rats (8 or so) around maintenance so we can have decent amount of rat burgers, if anyone wants to go hunt em.

**Comment by Chronitonity** [comment]
All good with me :+1:

**Comment by Nebyab** [comment]
Yeah sure

**Pull request merged**
