### PR TITLE
The Spesser

### PR DESCRIPTION
**Pull request by Pyko1**
Execution room redesigned and added the missing sec door.

### CODE REVIEW

**Comment by Chronitonity** [comment]
I'm gonna post the picture here: https://slack-files.com/files-tmb/T085X750F-F09RYHME0-5fcf49507d/selectable2_360.png

This lets any security officer get rid of someone from the round permanently. It adds another, (imo) unneeded mass driver and gets rid of one of the few special things the Chaplin had that was his.

We shouldnt be encourging executions to remove people from the round, and we shouldnt be encouraging security to be shooting criminals into space instead of putting them in prison or borging them.

**Comment by danhibiki** [comment]
Aside from (also) disagreeing with the mass driver, I'm OK with the rest of the rework. Its an area that could use some love.

**Comment by Chronitonity** [comment]
Imo then just remove the entire mass driver gimmick and keep the rest then

**Comment by Pyko1** [comment]
Apparently i left part of the old execution room floating in space next to sec, ill fix it, and change the massdriver to some other execution thing, i quess.

**Comment by JustinBNewton** [comment]
The mass driver also behaves strangely...

**Pull request closed without merging**
