### PR TITLE
Sec overhaul and generic fixes

### PR DESCRIPTION
**Pull request by Pyko1**
Improved the execution room.
Returned the stolen sec door.
Fixed broken button for xenobio8.
Added missing atmos pipes to sec lounge.
Moved things slightly around in permabrig.
Added basketball, reading corner, and hidden corpse behind bookself to permabrig.
Changed the armory.
Arcade area was called as garden, fixed it.
Moved the catwalks slightly around the sec, to ensure there is always at least 2 tiles of space between them and walls.

### CODE REVIEW

**Comment by Chronitonity** [comment]
Still think there shouldnt be doors into space to encourage throwing prisoners out.

**Comment by Pyko1** [comment]
they are actually meant to to flood the the air out of the chamber

**Comment by Chronitonity** [comment]
Why would you need that, it still promotes throwing bodies out.

**Comment by Pyko1** [comment]
I really think some form of "spacing" should be an execution method for sec.
And even if they toss someone out the corpse will just crash to the grilles covering the catwalk above execution.

**Comment by Pyko1** [comment]
I guess the button could be changed to armory access only so only warden/hos/cap could use it.
And those 3 surely can get rid of corpses in a way or another even if there is no blast doors in execution room.

**Comment by Chronitonity** [comment]
Warden sure can't. I just don't think there's a reason for us to put a way to remove corpses and players permanently from the game.

**Comment by danhibiki** [comment]
When I saw the door, I thought of it being used to de-pressurize and kill the prisoner that way. There is always a couple airlocks officers could space corpses through, this one wouldn't add anything new.

**Comment by nalarmg** [comment]
I dislike the blast doors personally. At least with the airlocks in other parts of the station it's fairly obvious the intent was to space the corpse and actual effort has to be put into it.

**Comment by JustinBNewton** [comment]
reinforced walls errgghghg

**Comment by lcass** [comment]
It should only be usable by the hos or captain as spacing could be used here. there needs to be some sort of way for people to break into perma execution as there was in the last execution chamber. Antag rescue and such. Other than that I am fine with it , if people don't like it being used for spessing then maybe put some walls just outside the podlocks with 1 tile of space/

**Comment by Pyko1** [comment]
Currently it looks like this.

morechanges

**Comment by Pyko1** [comment]
ehh i see an error already

**Comment by Pyko1** [comment]
capture

**Comment by Pyko1** [comment]
Oh yeah, I bet the perma prisoners will love that lamp in the reading corner when the power runs out.
Sucks to sit in darkness.

**Comment by lcass** [comment]
I like it.

**Comment by Pyko1** [comment]
Separated the executees fun room from atmos, and added 3 options for the filling. Air, sleeping gas or CO2
.
capture

**Comment by Pyko1** [comment]
Also Changed the required access for shutters, and for the "atmos closet" to 3, same as armory.

So only Cap, HoS and Warden should have access to these.

**Comment by Pyko1** [comment]
Electrified the atmos closet windows.

**Comment by Pyko1** [comment]
Unreinforced some walls, removed duplicate wires.

capture

**Comment by Pyko1** [comment]
Made the scrubber scrub N2O and toxins since spills are ensured.

**Comment by Pyko1** [comment]
Added Scrubber to atmos closet.
capture

**Comment by Pyko1** [comment]
Made some changes to pressures to make it easier to use.

**Comment by Pyko1** [comment]
Unanchored the extra brig closets, so they are not in the way if someone
wants to go in or out from the window.

capture

**Comment by Pyko1** [comment]
Added mounted flash.
capture

**Comment by SplergeBucket** [comment]
I like Permabrig how it is.

**Comment by Pyko1** [comment]
Fixed the missing atmos pipes in sec break room.

capture

**Comment by Pyko1** [comment]
Kinda had to make small change to permabrig since the glass cage preventing bodies being thrown off the z-level looked a bit silly before it. I doubt there is really any harm done with the reading corner and hidden corpse&paper. Had to use the empty space somehow.

**Comment by Pyko1** [comment]
Changed tile appearances.
capture

**Comment by Pyko1** [comment]
More tile changes, made the reading corner smaller.
capture

**Comment by Pyko1** [comment]
Current appearance.

capture

**Comment by Pyko1** [comment]
Current appearance.
capture

**Comment by Pyko1** [comment]
Current appearance.

capture

**Comment by Pyko1** [comment]
Current Appearance.
capture
Any ideas, suggestions?

**Comment by Chronitonity** [comment]
I'm still pretty against this, why do we need to give security a ton of ways to kill people? This also makes it easier to break out of security due to the fact that theres just a million windows there.

**Comment by Pyko1** [comment]
I don't really see any harm done in giving them couple options beside the electric chair. If they are going to kill someone they are going to do it anyways even if they don't have a fancy array of things to choose.

Also, before they had to break 1 window on permabrig hallway to get out, now they have to do exactly the same thing (except the windows are now electrified). Going through the Execution Room takes more effort.

**Comment by Pyko1** [comment]
But I can remove some windows if it really is an issue.

**Comment by Pyko1** [comment]
capture
Would this be better?

**Comment by Pyko1** [comment]
Would this be better?
capture

**Comment by whitefox08** [comment]
What would be really cool is to allow the public to see the execution

**Comment by Pyko1** [comment]
Current appearance.
capture
Reworked the armory.

**Comment by Pyko1** [comment]
Current appearance.
capture

**Comment by TheMocheeze** [comment]
Suggestion: Move the riot room shutter to the security gear room (white tiles) so that you can move the armory desk flush with the security gear room, that way you eliminate the narrow hallway and impending fuckery from that.

**Comment by Pyko1** [comment]
Current appearance.

capture

**Comment by Pyko1** [comment]
Current Appearance.

capture

**Comment by Chronitonity** [comment]
Honestly the execution area is a mess and i'm not a fan. The armory is really great and i love it.

**Comment by nalarmg** [comment]
Not sold on security needing more ways to keep people and dump the corpses somewhere hard to reach, and I generally dislike the execution room with the blast doors.

**Comment by lcass** [comment]
I like the idea of the execution room and I support it but I can see where the others are coming from ,  I do like the armoury though , that should be implemented ASAP.

**Comment by Pyko1** [comment]
Currently make some major changes around sec.
Moving things around, making high risk isolation chamber, and execution observatory, accesible to sec/lawyers from brig hallway. From there any spessed executee should witin 2 reinforced windows and 1 or 2 tiles of spess and no corpses lost in process unless actually take down some walls/windows in space.

**Comment by Pyko1** [comment]
Currently making some major changes around sec.
Moving things around, making high risk isolation chamber, and execution observatory, accesible to sec/lawyers from brig hallway. From there any spessed executee should be in 2 reinforced windows and 1 or 2 tiles of spess  away and no corpses lost in process unless actually take down some walls/windows in space.

Work in progress
wip

**Comment by lcass** [comment]
moving execution into that room isn't really good , the second sec comes in with the prisoner they will be lynched

**Comment by Pyko1** [comment]
Thats just high risk isolation chamber, ill put flashers in it, and 2 doors that work like virology, except there is only 1 button outside that operates it, so you need 1 person on button and another with prisoner.

**Comment by Pyko1** [comment]
Also shutters or blast doors to make it overkill.

**Comment by Pyko1** [comment]
Oh I think you meant the execution area as its now, I just moved it away for the time being.

**Comment by Pyko1** [comment]
Would this look any better?

Still Work in Progress.
execution wip

**Comment by Chronitonity** [comment]
What is that huge glass space area

**Comment by Pyko1** [comment]
its high risk isolation room it should have airlock like virology has, and shutters/blastdoors. You need 1 guy outside to operate doors, and another guy with prisoner.

**Comment by Pyko1** [comment]
Current appearance.
secoverhaul

**Comment by Pyko1** [comment]
Current appearance.
secoverhaul

**Comment by Pyko1** [comment]
Any ideas or suggestions, personally I'm starting to think its pretty close to finished product.

**Comment by danhibiki** [comment]
I like it, especially the large viewing room for the execution chamber. I like that the shutters are now leading to a contained area of space, which would prevent any increased ability to space corpses.

**Comment by Pyko1** [comment]
The final look.
capture

**Comment by Pyko1** [comment]
Hopefully all done.

capture

**Comment by Pyko1** [comment]
Now its done (like its ever done).

capture

**Comment by lcass** [comment]
you are missing a pipe on the injection to the solitary area.

**Comment by Pyko1** [comment]
Already fixed.
Sec Overhaul 1.1.3 …
Returned the missing pipe to isolation.

**Comment by Pyko1** [comment]
Latest, should be done.
capture

**Comment by TheMocheeze** [comment]
Small things: Fix the light by this charger http://i.hizliresim.com/ly4J1b.png

**Comment by Pyko1** [comment]
Finished now.

**Comment by TheMocheeze** [comment]
I don't see any glaring issues otherwise, just playtest the atmopsherics and buttons, make sure doors IDs are all good, and it's got my support.

**Comment by Nebyab** [comment]
I don't see a problem with it, I think it'll shake things up, which honestly would be nice.

**Comment by whitefox08** [comment]
:+1:

**Comment by whitefox08** [comment]
@Pyko1 is this finally finished?

**Comment by Pyko1** [comment]
yeah its finished

**Comment by SplergeBucket** [comment]
Love the armoury, though I preferred the version with the door and shutters rather than pressing a button to lift the shutters and allow access but i'm fine with either version.
Fine with all the map fixes you're adding.

I still dislike the execution area though.

**Comment by Pyko1** [comment]
Made some changes in armory, and will probably keep on doing until end of the world until someone does something.

As it is now.
capture

**Comment by Pyko1** [comment]
Also ready when ever it has enough approvals and someone feels like it.

**Comment by Pyko1** [comment]
Better Image of the armory area.
capture2

**Comment by lcass** [comment]
I like it , probably best to stop modifying it until they approve changes. Hope it gets merged.

**Comment by whitefox08** [comment]
@Pyko1 #503 was merged before this, you going to have to merge the dmms.

**Comment by Pyko1** [comment]
I have no idea how to do that.

**Comment by Pyko1** [comment]
Looks like I have to manually piece the maps together, or the medbay sec checkpoint was not properly map merged as it had +7,256 −7,296 lines changed which seems way too much.

**Pull request closed without merging**
