### PR TITLE
SMESlog fix

### PR DESCRIPTION
**Pull request by yobob591**
No more spammy SMESs in the admin logs, message only goes when
deconstructed

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
Merge conflicts, probably due to a previous fix made by Spacedong

**Comment by yobob591** [comment]
well if its already fixed just get rid of this one

**Comment by TDcoolguy300** [comment]
Alright

**Comment by yobob591** [comment]
took me 10 minutes to fix but 2 days to figure out how to get git working

**Pull request closed without merging**
