### PR TITLE
Nerfs armor penetration for ranged holoparasites

### PR DESCRIPTION
**Pull request by Spacedong**
seriously at the rate of which they fire who in their right mind thought this was acceptable for them to COMPLETELY IGNORE armor

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
ehh
20 TC traitor item. Buff the shit outta the other ones.
You can get extremely deadly gear for less than 20 TC, and this is an item that might give you a shitty player or someone who has no idea what they're doing. I'd say Ranged isn't bad, just the other ones need to be considerably better.

**Comment by Swagile** [comment]
what trifront said

i was initially angry as fuck when i saw a mime kill people who were wearing full riot armor

but then i realize its a 20 tc item and you can buy a ebow + esword that does essentially the same thing without the risk of getting a bad player from the ghost pool as your holopara

or if you prepare enough, you can get the entire armory with just an emag + thermals + adrenalines and be just as powerful if not more

all other holo para's fucking suck right now because if your not a dumbo you can get a firesuit to negate chaos fire, and avoid teleport while lasering the holo

standard is just absolute garbage tier and needs something like time stop spell to make it worthwhile

explosive is REALLY gimmicky and requires you to get valuable items people are willing to pick up without suspecting it to be a trap, and has no offensive ability to protect its master if people realize you have a explosive holopara. needs the fire ball spell so it can protect its master and do damage besides shitty bombs

healing is ok, it just needs a buff so that you can instantly teleport your master if you touch them. right now there is like a 5 second time before you teleport your master away, which is fucking retarded because in 5 seconds you can be lasered to crit / be pulled away from the holo para. it needs to be instant for healing to be worth anything except as a gimmick / stolen by sec and used by them (looking at you solidfury)

**Comment by McBawbaggings** [comment]
Nah, buff other holoparasites that need it (Standard, bomb)
Chaos is great for atmos techs and CEs,
Support has huge utility and can drag you to safety while healing you and teleport things,
Ranged is highest DPS and has good vision but glass cannon.

Standard just offers very little that the others don't already offer (Punching anything that isn't an rwall)
Bomb holoparasites require good bait but can be devastating.

I think potentially reducing the CD on teleporting a master on support would be good.
Standard needs timestop to be useful.
Bomb could use SHEER HEART ATTACK or some other secondary function to help in 1 v 1 scenarios.

**Comment by Swagile** [comment]
mcbawger stealing my swagger

:((((

**Comment by Spacedong** [comment]
>good vision but glass cannon

nigger he can fire down a hallway like a machine gun without any harm to himself

**Comment by McBawbaggings** [comment]
He has shite damage reduction compared to other holos.
If anything, decrease the damage reduction further so that shooting the ranged holo yields more damage than shooting the master.

**Comment by ArcLumin** [comment]
So give his spray damage falloff by range traveled

**Comment by GuyonBroadway** [comment]
Crystal spray deals 5 damage that bypasses armour. But getting augmented means you take a flat 5 damage reduction AFTER armour. It does not work as armour and ignores penetration, no ifs and no buts. Flat 5 brute reduction. Get augmented and laugh at ranged holoparas as they do nothing to you. For 20 fucking tc you should not be countered without SOME kind of minimal effort.

**Comment by banthebantz** [comment]
Holoparasites are fine, 20tc for an unreliable item that essentially means you take a ton of extra damage (especially if the holopara decides to not bother dodging).

**Comment by ArcLumin** [comment]
Code's good

**Comment by JohnGinnane** [comment]
Closing as head says no, plus standard is being buffed in another PR

**Pull request closed without merging**
