### PR TITLE
carbon told me to make this pr i have no idea why or what it does

### PR DESCRIPTION
**Pull request by Kierany9**
I dont even know

lelo
rero

### CODE REVIEW

**Comment by TDcoolguy300** [comment]
This fixes a table issue i believe to do with polls.

**Comment by Carbonhell** [comment]
do not merge, nalar only needs to see the commit to do some weird stuff

**Comment by JohnGinnane** [comment]
Do we not have a way of making changes to the database schema?

**Comment by nalarmg** [comment]
Changes made server-side. Merging.

**Pull request merged**
