### PR TITLE
Such beautiful duwang

### PR DESCRIPTION
**Pull request by Kierany9**
Added new brain damage lines from the infamous 'Duwang' translation of Jojo's Bizzare Adventure: Diamond is Unbreakable.

_Removed a bunch of lines because there were too many and a lot felt out of place_

- such beautiful duwang
- YOU ARE THE super retard
- dont be dong...
- SHOW YOUR BITCH ASS?!?!
- ;dont feel so well

As well as a couple of lines from Monty Python while I'm at it.

- MY BREAIN HURTS!!1
- ;NUUUUUUUURSE!??!?!

### CODE REVIEW

**Comment by doobiedoo23** [comment]
oh my god

**Comment by McBawbaggings** [comment]
"such a beautiful duwang"
otherwise this PR is solid shit and makes me the fucking strong +1

**Comment by doobiedoo23** [comment]
also add ';make everybody happy' and 'you are the super reatard'

**Comment by doobiedoo23** [comment]
nvm for the second one I'm blind

**Comment by Gandalf2k15** [comment]
+69

**Comment by McBawbaggings** [comment]
infact we need more like
"dont feel so well......"
"ABAJ"
"make everybody happy"

**Comment by Spacedong** [comment]
niceu +1

**Comment by danhibiki** [comment]
-1 animu shit, for serious how can we chastise people for adding gar glasses cuz weeaboo and turn around and do this.

**Comment by ArcLumin** [comment]
get a feeling so complicated

**Comment by Kierany9** [comment]
Added a couple of lines from Monty Python while I'm at it.

- MY BREAIN HURTS!!1
- ;NUUUUUUUURSE!??!?!
- I'M GOING TO OPERATE!"

**Comment by Spacedong** [comment]
@danhibiki who did we chastise again lmfao what are you talking about dawg

**Comment by Kokojos** [comment]
Add ''Every sperm is sacred'' and ''IM' LOOKING FOR AN ARGUMENT'' and ''BIGGUS DICCUS''

**Comment by danhibiki** [comment]
I think its just sort of needless to add so many lines, especially referenced from a source material that bares no relevance outside of the people who watch it. We have plenty of meme-y brain damage messages, but most of them bare relevance to the game itself, either mocking stupid player statements or gaffs in trying to communicate OOCly. Otherwise, they are pretty widespread memes that transcend the media its referencing. While some of these may be humorous, its ultimately stale because its only references that will amuse a niche group.

Except don't be dong. I like that one.

**Comment by Nebyab** [comment]
What dan said.

Hell, even most of the memey lines in the braindamage text that are from outside sources have been integrated into the larger game. These don't fit, and will please a single demographic.

**Comment by Kierany9** [comment]
Point taken. I'll probably go ahead and reduce the number of lines so that they don't need their own subcategory and take up 20% of all braindamaged lines just for jojo references.

**Comment by Spacedong** [comment]
*chew*

**Comment by Limed00d** [comment]
neb and dan being no fun WOW geez

**Comment by Nebyab** [comment]
I didn't become headmin because of my innate sense of fun

**Comment by GeneralGoose** [comment]
>no 'i'm wood stupid'

**Comment by oprayx73** [comment]
add "get a feeling so complicated"

**Comment by GeneralGoose** [comment]
feel you deeply

**Comment by Nebyab** [comment]
okay, this is a bit better

**Comment by Voratius** [comment]
god no please no

**Comment by Carbonhell** [comment]
Heads give your opinions please

**Comment by McBawbaggings** [comment]
+1

**Comment by Carbonhell** [comment]
Code ok,merging

**Pull request merged**
