### PR TITLE
Removes references of players in dakimakuras

### PR DESCRIPTION
**Pull request by Spacedong**
honestly these people didn't do anything noteworthy to warrant their place in the game code and as such they don't deserve to be immortalized here

### CODE REVIEW

**Comment by tabsiforu** [comment]
Add yourself to the list

**Comment by GeneralGoose** [comment]
10/10 the most important fix of the year, instant merge, commended, liked, subscribed, retweeted and reposted
vote 5 fgts and im out of here

**Comment by tabsiforu** [comment]
i'm downvoting until spacedong adds himself

**Comment by GeneralGoose** [comment]
^ i bet it's spacedongs fake account ;^)

**Comment by Mithrandalf** [comment]
Literally no fun allowed.

**Comment by GeneralGoose** [comment]
how is this fun

**Comment by Mithrandalf** [comment]
HUMAN

WHAT IS THIS 'FUN' YOU SPEAK OF?

EXPLAIN.

**Comment by tabsiforu** [comment]
@Mithrandalf it's fun for the users being added ebin :^)

**Comment by Kokojos** [comment]
Yeah okay.

**Comment by Kierany9** [comment]
rip sue

**Comment by Kierany9** [comment]
>No changelogs

spacedong pls

**Comment by GeneralGoose** [comment]
there's no need for changelog
it shouldn't have been a thing in the first place

**Comment by GeneralGoose** [comment]
frick yeah

**Pull request merged**
