### PR TITLE
Cigarettes with Blackpowder and Nitroglycerin now explode when lit

### PR DESCRIPTION
**Pull request by Kierany9**
Works exactly like plasma and welding fuel cigarettes, nitroglycerin explodes with the same power as plasma and Blackpowder is 2/3rds the strength of Plasma.

### CODE REVIEW

**Comment by dreamcrab** [comment]
neat why not +1

**Comment by Carbonhell** [comment]
code ok just needs another head @McBawbaggings

**Comment by McBawbaggings** [comment]
Why wasn't this a thing before? +1

**Comment by TDcoolguy300** [comment]
Two head approvals, merging

**Pull request merged**
