### PR TITLE
Janitors now start with soap in their backpack.

### PR DESCRIPTION
**Pull request by Spacedong**
self-explanatory, should be useful for encouraging them to clean gang-signs and other hard-to-reach areas that a spray bottle can't reach.

### CODE REVIEW

**Comment by Dudeinyourbackyard** [comment]
This is the Best Clean Station of All Time

+1/3

**Comment by Hackole** [comment]
Outrageous powercreep this will ruin the entire server

**Comment by gumner** [comment]
i agree with hackole,this is too much powergaming

**Comment by ArcLumin** [comment]
wow janitors being allowed to clean fuck no -1

**Comment by yobob591** [comment]
>actually using soap
not slipping everyone

wow shitty -1

**Comment by Swagile** [comment]
+ 1 from me, 2/3 GM vote

**Comment by SpankMasterson** [comment]
I support this, I'd merge it now if I could.

**Comment by yobob591** [comment]
2 gms and a ha means a merg right?

**Comment by Swagile** [comment]
as long as the code is good, i don't see why not

**Comment by McBawbaggings** [comment]
Yeah okay +1

**Comment by McBawbaggings** [comment]
CHANGELOG IS NOT .YML

**Comment by banthebantz** [comment]
dongcode kek

**Comment by Spacedong** [comment]
OK

**Comment by Pyko1** [comment]
I keep checking back to confirm it says soap on the code, since I'm half expecting janitors to spawn with singularity or something in their backpack instead...

**Comment by Swagile** [comment]
LOL

**Comment by ArcLumin** [comment]
It's actually saop, singularity assimilated orbiting particle

**Pull request merged**
