### PR TITLE
Nerfed the Roman Shield because it was better than any of the security shields

### PR DESCRIPTION
**Pull request by Spacedong**
Fixes issue #3039

fuck you crystal

### CODE REVIEW

**Comment by ArcLumin** [comment]
Minor reduction, still no slowdown or swap, I guess I'm fine with this.

**Comment by McBawbaggings** [comment]
+1

**Comment by Hackole** [comment]
I'd prefer it be kept as is and just removed from the autodrobe, honestly.

**Comment by GuyonBroadway** [comment]
Can just make a child of the roman shield called replica roman sheild and set all its resistancies to be 0, add that to the autodrobe so clowns can pretend to join the chaplain crusade. That way skeleton thralls from the necromancer stone don't get gimped by proxy

**Comment by yobob591** [comment]
that sounds way better

**Comment by blobbernaut** [comment]
should just give a shitty version to the autodrobe, skeletons should be stronk.

**Comment by Pyko1** [comment]
If we make replica Roman shield, it still should have at least some resistance since there is only 1 and it costs coin.

**Comment by Spacedong** [comment]
ok

**Pull request closed without merging**
