### PR TITLE
Removes all tasers and energy guns from the game

### PR DESCRIPTION
**Pull request by Sarcalogo**
This is for testing purposes. 

http://hippiestation.com/showthread.php?tid=4111

All experienced players think there is an issue with "the meta" but nobody can agree how to fix it. I think the way to fix it is to remove anti stuns. Some people take issue with energy guns and tasers.  This is an attempt to measure objectively what would happen if the most common stuns were outright removed. 

Because those people have no ambition and no ideas of their own, I've created this. The idea is, you remove energy/taser guns and see exactly what the effects are if they are removed, and take note of them.

I think this will be a disaster, but at the very least those who cry to remove stuns, Kierany9, can learn a lesson and offer some constructive criticism.

The next step is obviously a nerfing of stuns, but that can be tested after this. 

Feel free to close and open when anyone can actually be convinced to run some test changes. Until then, DISCUSS!

### CODE REVIEW

**Comment by McBawbaggings** [comment]
I will tell you right now, nebyab will not let this through. This is gonna fuck security way too hard as well.
People will resort to water, lube, soap, flashes, flashbangs, pepperspray, spraytan grenades etc.

**Comment by Sarcalogo** [comment]
Yes, but at least I tried.

**Comment by Kokojos** [comment]
The armor PR that makes multiplicative armor could prove usefull here. Stun resistance is either you get a full stun or you get no stun. It should be changed to a % of the total stun resistance.

This is bad pr.

**Comment by Sarcalogo** [comment]
This isn't Grudgecode you moron.

**Comment by dreamcrab** [comment]
id rather just uhh, ignore the small minority of people that are upset and keep the game running???

so.. no? this is a game that many people enjoy, not your platform to try to make people look stupid. only do that to yourself.

**Comment by Sarcalogo** [comment]
It's a test change. It doesn't even compile right now because I messed something up. Every experienced player is in a tizzy about "the meta" you should read OOC some time. It's a mess. Arguments all over, the same discussions day in and day out. I just think if we try stuff and see what happens eventually people will shift into one direction and come to a consensus.

**Comment by dreamcrab** [comment]
you sound like the ghost of christmas past or whatever. HERES WHAT THE FUTURE WOULD LOOK LIKE WITHOUT YOU.

gonna go ahead and reiterate my no.

**Comment by Sarcalogo** [comment]
Well I didn't expect any different. But I tried.

**Comment by calibraptor** [comment]
Dude no.

**Comment by Kierany9** [comment]
This is just sarcalogo going out of his way to try and make me look bad because I posted a thread on the forum about stuns that he disagreed with, which I suggest you all take a look at. There is absolutely zero thought put into this change and once again a really dumb PR made out of spite. Basically:

>this is not your platform to try to make people look stupid. only do that to yourself.

-1

**Comment by Mithrandalf** [comment]
You're pretty much a crying bitch, aren't you?

**Comment by Sarcalogo** [comment]
No it isn't, Kierany. You're mistaken. Obviously removing tasers and energy guns won't fix anything. Everybody knows that. Everybody knows that it will just cause more issues.

But I think if you want to "fix" the "stun meta" you need to have some actual data. You need to make a lot of changes, and see what the effects of those changes are. This is an attempt to learn something about why it is the stuns are the way they are. You cannot just hypothesize in a vacuum, without making changes. You have to make changes, observe, tweak, and think about it. Nobody is ever going to get anywhere unless SOMETHING is done. I'm not mocking you, I can mock you in much more effective ways.

**Comment by Spacedong** [comment]
even travis hates this update, :-1:

**Comment by TDcoolguy300** [comment]
Your basically removing Security's non-lethal way of detaining people, how the hell do you expect to get people who fuckin run like the wind with just a flash? :-1:

**Comment by Nebyab** [comment]
I find this hilarious.

-1

**Comment by TDcoolguy300** [comment]
Headmin denial has sent this into Limbo, one more denial from a headmin means to close this

**Comment by Nebyab** [comment]
uh td all three headmins have said no, me, teamstab, and mcbaw

**Comment by TDcoolguy300** [comment]
Then i fucked up, closing

**Comment by blobbernaut** [comment]
this would be better as an event

**Comment by Kierany9** [comment]
>give sec innate CQC powers and robotic augments and remove all tasers

yes

**Pull request closed without merging**
