### PR TITLE
Adds recharger to Escape Security Checkpoint.

### PR DESCRIPTION
**Pull request by Spacedong**
pretty useful to recharge your guns before you leave to face hell on the shuttle

### CODE REVIEW

**Comment by Nokington** [comment]
:+1:

**Comment by Nokington** [comment]
nevermind because fuk u spacedong

**Comment by Spacedong** [comment]
rude???

**Comment by Nokington** [comment]
Rude because I gave you a plus one? Wow. I should just take that back now.

**Comment by Spacedong** [comment]
wow stop deleting ur messages banter tier

**Comment by XeonFaux** [comment]
Where's the pic?

**Comment by Spacedong** [comment]
bam http://vgy.me/VRAAMV.png

**Comment by Nokington** [comment]
why did you close this???

**Pull request closed without merging**
