### PR TITLE
Prevents changelings from using the gateway

### PR DESCRIPTION
**Pull request by blobbernaut**
This will make balancing the gateway maps a million times easier. Changelings should not have access to the types of things you can get in those missions as well as the free absorbs from the mob corpses. Their natural abilities make them FAR too strong when combined with guns and energy shields and stuff. 

I didn't want to ban them during changelings rounds because that'd allow for easy meta. 

it doesn't alert anybody but the ling, and the gateway is very far from the cremator and the gibber. A caught ling should easily escape in the time it takes to get tested. Plus even at roundstart they have headslug.

Alternatively, it could just be a rule that this isn't to be used as a ling tester. Like with checking the crew monitors and the 'who' list to check for nuke ops not being allowed.

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Yus

**Comment by trifornt-tinfornt** [comment]
I can see this end up being a "hey, touch the gateway or else you're a ling lol" method.

**Comment by blobbernaut** [comment]
it doesn't alert anybody but the ling, and the gateway doesn't open until half an hour into the round. Half an hour in, a ling should have a few absorbs, and having security use the gateway to test them would give them a lot of opportunity to use their escape abilities. I don't see that being a problem, trifornt.

**Comment by Spacedong** [comment]
@trifornt-tinfornt   we can easily warn people not to that as its practically metagaming, same as how people aren't allowed to use crew monitors and compare player count to see if theres nuke ops, its plain meta and garbage

**Comment by blobbernaut** [comment]
Also, sec throwing people into the gateway against their will would probably be highly discouraged especially since a few of the gateway locations have no atmosphere.

**Comment by Gandalf2k15** [comment]
@blobbernaut Its not half an hour its 8 mins.

**Comment by Spacedong** [comment]
it should be a half hour

**Comment by Gandalf2k15** [comment]
Nope > Go in gateway > Emergency Shuttle has been called > Waste of time > Gateway = Obsolete. Leave as is.

**Comment by Gandalf2k15** [comment]
Infact I might change it back to the default 5 mins.

**Comment by blobbernaut** [comment]
Ok, i rewrote my comment

**Comment by Nebyab** [comment]
You've literally added a lingtest back into the game.

**Comment by blobbernaut** [comment]
And? Better than allowing them access to the missions I think.

**Comment by Pyko1** [comment]
Could add some shit "We restrict our powers to conserve energy, until we are back again in a suitable breeding ground."

**Comment by Crystalwarrior** [comment]
This is absolutely stupid.
Like I said I think we're overall better off if gateways were a random space location you'd have to stumble into instead of being an on-station thing.

**Comment by Pyko1** [comment]
Yeah off station gateway at a template could be a lot better. But then again is it worth to sacrifice so much resources to a thing that maybe 1 person uses in a round.

**Comment by Pyko1** [comment]
Why there is map edits and shit if this only restricts changelings from entering?

**Comment by Gandalf2k15** [comment]
This PR is broken. Its two PRs in one.

**Comment by Pyko1** [comment]
BROKEN as gandalf said

**Comment by blobbernaut** [comment]
what the fuck it was only one file changed last night

**Comment by TDcoolguy300** [comment]
We had a repo failure Blob, so you gotta either clear the bad files from your fork OR refork

**Comment by blobbernaut** [comment]
how do I do that

**Comment by TDcoolguy300** [comment]
Update the offending files from the the main repo to attempt to match them up, or delete your fork and refork

**Pull request closed without merging**
