### PR TITLE
Clown/mime hardsuits

### PR DESCRIPTION
**Pull request by Pyko1**
clown/mime hardsuits.
cloonspess
mimspess

### CODE REVIEW

**Comment by Pyko1** [comment]
Same as earlier, fixed some conflicts.

**Comment by Kokojos** [comment]
Some questions first :
Are those mobs or statues in the mime ship?
SO MANY PLASMA CANISTERS WHY?

Concerns :
We already have the ''clown planet outpost''. I fear they might be too many clowns.
That is a LOT of clown mobs.
That is also a lot of free spacesuits. (While I do like the spacesuits themselves)

**Comment by Pyko1** [comment]
Those are statues on the mime ship, the actual mimes are ash piles.
Surely the poor honkers need some ammo for their massdrivers, but yeah i quess they could had used some more of it already.
I guess i could remove couple clowns and suits, even tho they are in middle of space so i doubt there wont be many people taking em.

**Comment by Pyko1** [comment]
I guess this could be technically merged, as it only adds to  the mime/clown harduits and a suit storages to the game. The Z8.dmm map isnt used by the current code so it wont be added. But if anyone bothers to configure teh Torus Space it might be nice to have there.
Also, quick before there is any more conflicts!

Oh yeah updated the pictures on OP.

**Comment by Kokojos** [comment]
Assuming it<s merged, it will still add at least 16k instances if you map is 128x128. Technicaly it can, but il be honest I don't like this too much. Waiting on head's opinions.

**Comment by Pyko1** [comment]
I don't think it will add any instances, as the map is not even loaded when compiling.
It will just sit there, unused until someone decides to delete it or add it to torus config or swap it with some other Z-level,

**Comment by Pyko1** [comment]
But yeah, mainly I'd just prefer to get the .dmi files in before someone else adds some other items, and they start conflicting again.

**Comment by Pyko1** [comment]
Removed the Z8 for the time being, only contains the clown and mime hardsuits, and a hardsuit storage for em.

**Comment by Chronitonity** [comment]
Where are the hardsuits located?

**Comment by TDcoolguy300** [comment]
I would presume the suit storages on either ship

**Comment by TDcoolguy300** [comment]
Nevermind me, being stupid

**Comment by Pyko1** [comment]
For now they are just in the code, waiting for time and place. 

And for someone to actually add them on a map or make other ways to get em.
Sure they are on my z8 but thats not going to be in any time soon at least I guess.

**Comment by Pyko1** [comment]
Would be nice to get head aproval for the addition of clown/mime harsuits.

**Comment by SplergeBucket** [comment]
if it's just an inclusion in the code i have no objection to it

**Pull request merged**
