### PR TITLE
Bar & Kitchen

### PR DESCRIPTION
**Pull request by Pyko1**
Some minor changes around bar and kitchen.
Mainly to make it look better.
Should be more or less how it used to be before rebase.

Added a spare universal enzyme to kitchen locker.

### CODE REVIEW

**Comment by Pyko1** [comment]
capture

**Comment by danhibiki** [comment]
Looks good

**Comment by Chronitonity** [comment]
I'm not a fan of having a glass door at the front of the bar tables and a door to the Bartenders backroom. Just having one of those would be the best imo

**Comment by Pyko1** [comment]
Replaced the bar windoor with table and stool.
Rotated the vault windoor to south.

**Comment by Pyko1** [comment]
Made some changes to kitchen back room to get rid of the ugly double wall between kitchen and botany back rooms.

capture

**Comment by Foosili** [comment]
Looks radical :+1:

**Comment by Chronitonity** [comment]
This got two heads approval so

**Pull request merged**
