### PR TITLE
Reduces the price of the Wrestling Belt and CQC

### PR DESCRIPTION
**Pull request by Kierany9**
This was previously in the King of the Disk PR and didn't have much to do with the gamemode so I took it out.

Reduces the price of Wrestling and CQC from 12 TC to 5 and 7 TC respectively. I have no idea what Crystal was thinking when he made these 12 each, both are fun memey 1v1 items, neither of them can compete with the Esword or Power Fist in terms of usability or power.

### CODE REVIEW

**Comment by Mithrandalf** [comment]
Kierany does it again.

10/10

**Comment by GeneralGoose** [comment]
tru
also someone can be bothered enough to copypaste disguise code from the gloves onto belt and make it possible to disguise it as any other belt (fanny packs, medical and toolbelt), so it isn't an instant giveaway

**Comment by Badmex** [comment]
Maybe cqc is still a bit too high? Overall yeah they are gimmik items that nobody is using because they cost so much tc. +1/3

**Comment by calibraptor** [comment]
+1 I'd love to see them used more often.

**Comment by GeneralGoose** [comment]
@Badmex CQC gloves can be disguised, belt can't, higher price makes sense

**Comment by Nebyab** [comment]
ok

**Comment by Kokojos** [comment]
+1/3 our savior is here, amen praise be to the lord Kienranyyyeyeneyen7

**Pull request merged**
