### PR TITLE
Nerfs ephedrine

### PR DESCRIPTION
**Pull request by Spacedong**
Anti Stuns Are Gay Part 2: Electric Boogaloo

### CODE REVIEW

**Comment by Swagile** [comment]
why the fuck are you nerfing its stun resist when the worst part about it is the FAST flag?

remove FAST and keep normal stats; that'll make it fine.

**Comment by Spacedong** [comment]
ok ill up it to [VERY_FAST]

**Comment by Swagile** [comment]
scrub

**Comment by yobob591** [comment]
my stand, 「ＶＥＲＹ　ＦＡＳＴ」

**Comment by ArcLumin** [comment]
Code's good.

**Comment by QuarianCommando** [comment]
Why not just make it metabolize really, really fast? You know, like in real life.

**Comment by trifornt-tinfornt** [comment]
Something that nerfs Ephedrine? And a mute sting nerf?
Spacedong is the hero we needed, but not the one we deserved.
add it

**Comment by McBawbaggings** [comment]
yeah

**Comment by trifornt-tinfornt** [comment]
personally I'd rather see all antistuns get removed, but that'd get shot down by a whiny playerbase

**Comment by SplergeBucket** [comment]
tbh the biggest issue with chems will always be the lack of a proper overdose system
mixing drugs and overusing/using them in large doses should fuck you

**Comment by Kierany9** [comment]
Question: Do you understand the numbers you've changed?

**Comment by TDcoolguy300** [comment]
Answer: No

**Comment by McBawbaggings** [comment]
Yeah cunt +1

**Comment by SplergeBucket** [comment]
im ok with this if the code does what i think it does but judging from kierany's comment i dont think it does

**Comment by Spacedong** [comment]
the code I changed will now make it shittier and thats what everyone wants

**Comment by Swagile** [comment]
your code change is shit because it doesn't change the base factor for why epherdine is so shit

epherdine is a anti stun + hyperzine combo. we have a hyperzine alternative, but it takes a while to make + it doesn't give anti stun

we have anti stuns but anti stuns that ALSO give you a speed boost have HUGE negative implications and if you don't want those implications, you have to take like 5u of it, which disappears so quick that you can't function easily with those drugs unless you get addicted to them (meth, bath salts)

epherdine is the only drug that gives both a SPEED BOOST and also ANTI STUN with 0 drawback because you can drink like 20u and feel no addiction or OD while all other drugs that do this allow you only 5u at best until your fucked by drugs

remove speed boost and epherdine will be the "midway antistun"; it will give you stun resistance, but you can't go fast, so if you get shot twice with a taser your game is done, not getting lucky shot once and then speeding away so fast that you go faster than projectiles can go in the game

**Comment by Spacedong** [comment]
ok

**Comment by Swagile** [comment]
you did it johnny

**Comment by Kierany9** [comment]
nigga just remove the line with speedboost on it you dip

**Comment by Hackole** [comment]
Yesss +1

**Comment by oprayx77** [comment]
bakudan no switchu mo sudeni ASDBHASDNAWL

 yeah dude nerrf this stupid shit i wanna see roma jacktheling anderbergst literally everyone quit the server at once

**Comment by LufgtHuron** [comment]
All this is going to do is make traitors stronger and turn the station into even more of a "one stun one kill" gameplay. Shit solution.

**Comment by ArcLumin** [comment]
remove all stuns, buff disablers and stamina damage.

**Comment by Spacedong** [comment]
@lufgthuron I'd rather have antags be more dangerous than have all non-antagonists be invulnerable to stuns and superfast

**Comment by Swagile** [comment]
the problem is traitors already use epherdine and then STACK it with adrenaline

so if their super speed and epherdine is stopped, they pop adrenaline

it makes it almost impossible to defeat antagonists except to suicide bomb at that point

**Comment by JohnGinnane** [comment]
Two heads approved, code looks good, been open for discussion for two days, merging

**Comment by Kierany9** [comment]
>Question: Do you understand the numbers you've changed?

pls

**Comment by JohnGinnane** [comment]
Oh shit

**Comment by JohnGinnane** [comment]
The thresholds to be increased, assuming you wanted longer cooldown between stun resists

**Comment by JohnGinnane** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/7a12340428a22b4445cb2a2d82ee5c4b4dbf640f/code/modules/reagents/Chemistry-Reagents.dm#L126

**Comment by blobbernaut** [comment]
This is pure salty grudge, close this shit

**Pull request merged**
