### PR TITLE
Added unique outcome for putting aliens, monkeys, and corgis on meatspikes.

### PR DESCRIPTION
**Pull request by Spacedong**
Putting a monkey or a xenomorph on a meatspike will result in an instant kill in which you can then harvest their hide and meat from the spike. Also includes unique grotesque sprites for when a spike is occupied by eiither mob.

Gifs:

https://vgy.me/1pgAJa.gif

https://vgy.me/4ESa0Z.gif

EDIT: You can now meatspike corgis as well.

https://vgy.me/FpsF1d.gif

### CODE REVIEW

**Comment by banthebantz** [comment]
pete almost got you in the last gif

also yes pls

**Comment by McBawbaggings** [comment]
Butcher pete please.
+1
https://www.youtube.com/watch?v=2Fc1wr3dYxU

**Comment by ArcLumin** [comment]
I've been meaning for xenos to drop their internal organs. You want to make it so that xenos drop their internal organs when butchered with this PR or should I try to do it some other time?

**Comment by ArcLumin** [comment]
Why do ayys and corgis not drop skins lad? Set the skins from 0 to 1

**Comment by Hackole** [comment]
Why not the kitchen always needs love +1

**Comment by ArcLumin** [comment]
dude what the fuck the dongcode isn't broken

merging since HA

**Pull request merged**
