### PR TITLE
More hair covering hats.

### PR DESCRIPTION
**Pull request by Pyko1**
Added "flags = BLOCKHAIR" to Ushanka and cardborg helmet.

Any ideas of other hats that should hide hair?

### CODE REVIEW

**Comment by Memendia** [comment]
*Added "flags = BLOCKHAIR" to Ushanka and cardborg helmet.*
:+1: Fuck yes!!

**Comment by ArcLumin** [comment]
>Needs Head Input
Pure comedy.

**Comment by SplergeBucket** [comment]
yeah literally the bes tjoke tbh because no heads check these prs we're like homeles speople likes ets form a gangu

**Comment by ArcLumin** [comment]
More like
You know
Head input
Heads are where your hair grows
you know, bad puns.

**Comment by Nokington** [comment]
@SplergeBucket We are in a code freeze you nugget

**Comment by Nokington** [comment]
Once the freeze is over, :+1:

**Comment by FuryMcFlurry** [comment]
image
 hello?

**Pull request merged**
