### PR TITLE
its spelled "graviton"

### PR DESCRIPTION
**Pull request by Spacedong**
In theoretical physics, the graviton is a hypothetical elementary particle that mediates the force of gravitation in the framework of quantum field theory.

### CODE REVIEW

**Comment by ArcLumin** [comment]
Nah, you see dong. Gravatons were discovered in 2098 by Isaac Gavaikis. They're particles that can be introduced as a field to cause metals nearby to generate gravity. This is part of our lore, don't take away our lore

**Comment by lcass** [comment]
Rename to gravytons and I will +1

**Comment by banthebantz** [comment]
gravitons aren't real

**Comment by Kierany9** [comment]
>gravy tons

yes

**Comment by yobob591** [comment]
if you want to be accurate change it to higgs-boson faggot

**Comment by banthebantz** [comment]
change it to spacedong is an autist please

**Comment by Spacedong** [comment]
hahaha memes aren't real nigga

**Comment by doobiedoo23** [comment]
Could you please visit a doctor and come back with some sort of diagnosis just so we have proof you're an actual autist?

**Comment by MethMedic** [comment]
Tbh i think this is enough to prove he's an autist die

**Comment by JohnGinnane** [comment]
Code is good :¬)

**Comment by Kierany9** [comment]
inb4 this kills the server

**Comment by Spacedong** [comment]
space station 13 but every round theres no gravity

**Comment by JohnGinnane** [comment]
merging as it's very minor typo fix

**Pull request merged**
