### PR TITLE
Re-adds meeseeks

### PR DESCRIPTION
**Pull request by blobbernaut**
Just putting this up for consideration. I thought they were fun.

### CODE REVIEW

**Comment by Kokojos** [comment]
I dunno, as admin they often brought trouble

**Comment by Pyko1** [comment]
Is this still a thing, or fixed?

**Comment by Nokington** [comment]
Nah and conflicts.

**Comment by XeonFaux** [comment]
@Pyko1 It is still a thing.

**Comment by TDcoolguy300** [comment]
I am trying to figure out why it's having a merge conflict

**Comment by TDcoolguy300** [comment]
Oh, the change log of yours is fucked apparently, might want to fix that

**Comment by Nebyab** [comment]
i mean if this get's working, why not

**Comment by blobbernaut** [comment]
My hard drive crashed and it'll take more than a week to get it fixed under warranty

**Comment by danhibiki** [comment]
Still got merge conflicts, but sure I'd do it again if it doesn't bork everything.

**Comment by blobbernaut** [comment]
Can't fix until my Computer is repaired. If you guys approve you can change
this file and make a PR because I can't on my phone

**Comment by nalarmg** [comment]
Still conflicted after a somewhat vast period of time. Please feel free to re-open this if there's further interest or you're able to fix the conflicts. Closing for now.

**Pull request closed without merging**
