### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by Pyko1**
changes: 
  - bugfix: "Fixed Minor wiring issue at sec."
  - tweak: "Unreinforced some non-important interior walls at sec."

### CODE REVIEW

**Comment by Pyko1** [comment]
Hardly balancing tho, should have minor impact on safety. More of just consistency fix of avoiding unnecessary rwalls.

ie. HoS office has rwall only to space, yet the interior wall separating sec lockers from their toilet/shower is reinforced.

**Comment by Nokington** [comment]
I'd like pictures before I give a :+1:

**Comment by Lawligagger** [comment]
la imagen por favor

**Comment by Pyko1** [comment]
capture

**Comment by Nokington** [comment]
:+1:

**Pull request merged**
