### PR TITLE
Adds Nazi Clothing

### PR DESCRIPTION
**Pull request by Sarcalogo**
See pictures below (give me five minutes to edit them in).

Nazi 1
Nazi 2
Nazi 3
Nazi 4
Nazi 5
Nazi 6

We have Space Russians, may as well have Space Nazis. Sprites done by Heredth from /vg/station.

### CODE REVIEW

**Comment by McBawbaggings** [comment]
>no pictures

**Comment by Sarcalogo** [comment]
Refresh your page.

**Comment by McBawbaggings** [comment]
Could you add these to the theatre vending machine? They're nice.

**Comment by trifornt-tinfornt** [comment]
Hitler clothing had better spawn in the Captain's Locker, and the HoS had better have Nazi General Uniform in his locker.
If not, then 0/10 PR.

**Comment by Sarcalogo** [comment]
Not sure what the hell that CI build shit is about considering it's talking about files I never modified. And nobody has sprited a Hitler uniform. 

I planned on putting the officer's suit (the silver one) in the HoS locker, and the rest of the stuff in the autodrobe in the theater.

**Comment by Sarcalogo** [comment]
Someone else is going to have to tell me what this shit is about. I think it has to do me fucking something up when compiling though... let me see if I can fix it gonna have to create a test pr...

**Comment by calibraptor** [comment]
The soldier uniform and officer uniform have better defensive capability than security uniforms and could be combined with riot armor for almost complete melee invulnerability.

You'll have my conditional +1 if you either make it adminbus only or reduce the armor.

**Comment by Sarcalogo** [comment]
I'll get rid of the armor.

**Comment by McBawbaggings** [comment]
I didn't even notice the armor

**Comment by Sarcalogo** [comment]
Armor removed. Still not sure what to do with the officer uniform. I'd like to see if Heredth sprited any more nazi stuff like Hitler's brown jacket or SS uniforms. Probably not. If not maybe make it a contraband item in the autodrobe?

**Comment by Gandalf2k15** [comment]
can we have a nazi variant of the HoS's armor

**Comment by Sarcalogo** [comment]
I'm not a spriter. I just ported these.

**Comment by Sarcalogo** [comment]
The hell? What does it conflict with?

**Comment by TDcoolguy300** [comment]
Any of the DMIs

**Comment by Sarcalogo** [comment]
How do you suggest I resolve those conflicts? On that matter how do I 100 percent verify that 2 items are conflicting?

**Comment by Sarcalogo** [comment]
Oh I see what did it. Lame. Yeah I'll fix it. Going to close this and make the changes on an updated branch.

**Pull request closed without merging**
