### PR TITLE
Blob pls go

### PR DESCRIPTION
**Pull request by Kierany9**
# NALAR GET OVER HERE

Blob was disabled server-side in the config but these changes were never mirrored to the git. When Nalar changed the config to mirror [this PR](https://github.com/HippieStationCode/HippieStation13/pull/3205), blob was readded into rotation by mistake.

### CODE REVIEW

**Comment by gumner** [comment]
DELETE THIS PULL,BLOB BEST GAMEMODE

**Comment by Spacedong** [comment]
up raginmages to 0.5

**Comment by MethMedic** [comment]
Yea blob is a terrible game mode

**Comment by tortellinitony** [comment]
no -1

**Comment by gumner** [comment]
-10

**Comment by blobbernaut** [comment]
wot

**Comment by Kierany9** [comment]
i mean its technically a bug

_technically_

**Comment by blobbernaut** [comment]
this doesn't fucking change anything server side what are you even doing.

**Comment by banthebantz** [comment]
delet this blob best

**Comment by Kierany9** [comment]
Making sure that the changes get mirrored to git so that it doesn't get re-added again by mistake

**Comment by blobbernaut** [comment]
blob is fine leave this in for a while and see how people like it

**Comment by blobbernaut** [comment]
kierny pls go

**Comment by gumner** [comment]
remove kierany9

**Comment by Kierany9** [comment]
i have never seen a bugfix pr get dogpiled so fast


gg

**Comment by gumner** [comment]
_its not a bug_

**Comment by ArcLumin** [comment]
I'm not 100% sure it's a bugfix, as we don't know what the heads were thinking

Until nalar voices it, we'll have it set for head input

**Comment by gumner** [comment]
# YES!!!

**Comment by trifornt-tinfornt** [comment]
Both Spank and Bawb said that Blob being added to rotation wasn't intentional.
RIP blob, get the fuck out of here.

**Comment by gumner** [comment]
no

**Comment by gumner** [comment]
do not merge this till admiral himself says something about it ;^)

**Comment by blobbernaut** [comment]
well it was nalar that did it, so wait for him to say.

mcbawb please go.

**Comment by trifornt-tinfornt** [comment]
Nalar has no say in this, though. What the headmins say is what has to happen.

**Comment by McBawbaggings** [comment]
Blob shouldn't be in.

**Comment by Dudeinyourbackyard** [comment]
blob wasn't supposed to be in at all yo

**Comment by blobbernaut** [comment]
lies

**Comment by gumner** [comment]
LIESSSSSSSSSSS

**Comment by banthebantz** [comment]
we should respect the wishes of our god

delet this

**Comment by gumner** [comment]
^^

**Comment by tortellinitony** [comment]
no we need nalar to say for sure

**Comment by nalarmg** [comment]
The PR description is accurate. It was originally removed from rotation by request of the head admins. I recently updated the config to reflect another PR that changed a few things, which undid the change.

**Pull request merged**
