### PR TITLE
Pod secure safe fix

### PR DESCRIPTION
**Pull request by Spacedong**
fixes the red-alert only safes in the pods being able to be opened by alt clicking

### CODE REVIEW

**Comment by JohnGinnane** [comment]
I think you want this line and the next to the one indentation to the left, so it's inline with "if(s)":

https://github.com/Spacedong/HippieStation13/blob/9c0c2b662c4ca0f0d26daac8cb89c3c2f88af099/code/game/objects/items/weapons/storage/storage.dm#L80

**Comment by Spacedong** [comment]
COME ON TRAVIS PICK UP THE FUCKING PACE

**Comment by dreamcrab** [comment]
very cool very swag i like it

**Comment by blobbernaut** [comment]
Good shit

**Comment by Gandalf2k15** [comment]
Code is good, merging as its an important bug fix.

**Pull request merged**
