### PR TITLE
FIXES WINDOWS

### PR DESCRIPTION
**Pull request by Spacedong**
Fixes issue #3267.

Single tile facing reinforced windows are no longer discolored like in the picture.

https://vgy.me/p1VJsg.png

### CODE REVIEW

**Comment by McBawbaggings** [comment]
Okay +1?

**Comment by Spacedong** [comment]
changelog is done

**Comment by yobob591** [comment]
honestly while its not a huge deal its kinda irritating so this would be nicc

**Comment by banthebantz** [comment]
I for one welcome our new cyan window overlords

**Comment by JohnGinnane** [comment]
Wow so they weren't frosted or tinted?

**Comment by JohnGinnane** [comment]
Bug fix, merging

**Pull request merged**
