### PR TITLE
adds boxing mask closet to dorms

### PR DESCRIPTION
**Pull request by Spacedong**
OLE

edit: removes the extra pajama closet because ya don't need 2

### CODE REVIEW

**Comment by danhibiki** [comment]
>balancing
lolwut

**Comment by Voratius** [comment]
but y?

**Comment by Spacedong** [comment]
@voratius :muscle:

**Comment by McBawbaggings** [comment]
Yeah okay

**Comment by dreamcrab** [comment]
balance +400

**Comment by Spacedong** [comment]
2 heads approve, merge.

**Comment by JohnGinnane** [comment]
I'm happy to merge, but would you mind posting screenshots? If there's any mapping changes it helps to see what's changed

**Comment by Spacedong** [comment]
@johnginnane it just adds an extra closet to dorms room and removes an extra pajama closet because 1 is enough

**Comment by Spacedong** [comment]
https://vgy.me/LlgGEW.png

**Comment by JohnGinnane** [comment]
Very well

**Comment by JohnGinnane** [comment]
Oh neat, thanks!

**Pull request merged**
