### PR TITLE
Removes Tablecraft Cooking. Ports oldcooking. 

### PR DESCRIPTION
**Pull request by Spacedong**
I can't believe it's actually fucking happening this time edition. Microwave cooking is back. Cutlets, dough, and other shit that came with tablecraft cooking all gone. Cooking is now easier, simple, and less of a hassle to do. Let's face it, once tablecooking rolled out, almost nobody plays chef anymore. Let's make kitchen great again. Most of the credit goes to Mcbawg.

### CODE REVIEW

**Comment by McBawbaggings** [comment]
As someone who did a lot of contributing on this, I'm not too sure if that kills my vote.
I'm obviously very much for this.

This does leave a lot of the newer food items unmake able, but it makes pretty much all of the old recipes we used to have work.

I have added a few of the new stuff tablecooking brought such as rice.

Myself and hopefully spacedong will update the wiki too of course.

As to how the code works, it's pretty much atlas code cleaned up. It was mostly fixing path errors and trying to understand burger code.

**Comment by McBawbaggings** [comment]
Need to add gibber code.

**Comment by danhibiki** [comment]
plz

**Comment by Mithrandalf** [comment]
gas the kikes merge now

**Comment by Dudeinyourbackyard** [comment]
i hate tablecraft cooking
yes
1/3

**Comment by Spacedong** [comment]
won't be merged until mcbawg tidies up some shit, but still, cast yo :+1:'s

**Comment by LuisReyesX** [comment]
Re-add Cereal,Candy and Juice maker too

**Comment by Spacedong** [comment]
@LuisReyesX that comes in a later PR, also there was never a juice-maker, just candymaker and oven, those use old code and won't come with this PR

**Comment by Spacedong** [comment]
Gibber animation actually added this time. Can merge now.

**Comment by Lawligagger** [comment]
ok

**Comment by Kokojos** [comment]
+1

**Comment by LuisReyesX** [comment]
Hey @Spacedong, just for reference. The bartender had a machine that could make juice using fruits and shit.

**Pull request merged**
