### PR TITLE
Fixes healing with chaplains bible

### PR DESCRIPTION
**Pull request by Spacedong**
fixes issue #2890

EDIT: it was carbon

### CODE REVIEW

**Comment by blobbernaut** [comment]
:+1:

**Comment by Pyko1** [comment]
Shit title, shit description, DNM.

**Comment by trifornt-tinfornt** [comment]
Nah, this is good.
Chaplain constantly being told he can't heal people because it "refuses to heal this metallic taint" is retarded. Brain damage was better.

**Comment by Spacedong** [comment]
@pyko1 are you fucking retarded

**Comment by ArcLumin** [comment]
He labeled it DNM and Grudge because of how you titled/descripted it. I think

**Comment by Spacedong** [comment]
@pyko1 carbon did this and its supposed to only work for augmented people, dismemberment fucked it up, so now you can't heal anybody

**Comment by Spacedong** [comment]
also how is this grudgecode jesus christ

**Comment by ArcLumin** [comment]
Do we have a saltdong label

**Comment by ArcLumin** [comment]
In all seriousness, this needs fixing

**Comment by Kierany9** [comment]
"Crystal Is Blaming TG Again" 2.0

**Comment by Pyko1** [comment]
@spcedong, you really didin't tell anything what this PR did on description and topic.

**Comment by Kokojos** [comment]
@ArcLumin As soon as codechecked.

**Comment by ArcLumin** [comment]
Saltdong label as soon as checked?

**Comment by blobbernaut** [comment]
Have you tested it, donger?

**Comment by GeneralGoose** [comment]
haha grudgecode more like grudgetagging amirite

**Comment by blobbernaut** [comment]
Assuming this actually fixes the issue and allows chaplain to heal people, can this get merged soon?

**Comment by Pyko1** [comment]
@GeneralGoose The original title suggested it was some grudge shit, and didn't say a word what this PR was for.

**Comment by trifornt-tinfornt** [comment]
salty pyko
changing titles so people won't know that he's a dumbass

**Comment by blobbernaut** [comment]
> assuming the content of something SPACEDONG of all people does based off of just the title

**Comment by Spacedong** [comment]
@pyko1 get cucked

**Comment by Kokojos** [comment]
Code is okay.

**Comment by SplergeBucket** [comment]
yes merge

**Pull request merged**
