### PR TITLE
Disposals and sec shuttle changes

### PR DESCRIPTION
**Pull request by Pyko1**
capture
disposals

Fixes https://github.com/HippieStationCode/HippieStation13/issues/2183 https://github.com/HippieStationCode/HippieStation13/issues/2154

### CODE REVIEW

**Comment by Nokington** [comment]
Looks good but I absolutely hate those assistant spawn points unless the belt will start off now

**Comment by Pyko1** [comment]
The belt is still on, but there is now more space to get past it.

**Comment by Limed00d** [comment]
I'm okay with this.

**Comment by doobiedoo23** [comment]
Sure

**Pull request merged**
