### PR TITLE
Moves the pinpointer from Cap's Office to HoS Office

### PR DESCRIPTION
**Pull request by Sarcalogo**
And gives it to the HoS instead. It makes no sense for the Captain to start with the disk AND the pin pointer.

I map merged and this is the result. Created the branch from HippiestationCode so the map is up to date. Not sure if it conflicts with any other PR.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Can you post screenshot where the disk is now?

**Comment by JohnGinnane** [comment]
Also shouldn't the head of personnel get it seeing as he/she's next in line to the throne?

**Comment by Sarcalogo** [comment]
Disk is in the exact same spot. Pinpointer is right where the universal recorder was on the HoS's desk. It's given to the HoS because he's the one who will be using it to track down the nuke disk in case of nuke ops or something.

**Comment by JohnGinnane** [comment]
That does make more sense

**Comment by Hackole** [comment]
I'm down for this. Not a bad idea at all

**Comment by Crystalwarrior** [comment]
Definitely a good idea, otherwise nuke ops just toss the pinpointer and call it a day

**Comment by McBawbaggings** [comment]
I'm inclined to disagree,
Captain should have the responsibility of delegating the second in command to guard the disk, it shouldn't be predetermined.

**Comment by Sarcalogo** [comment]
It changes the location of the pin pointer, not the nuke disk. Right now, the captain starts with the nuke disk (incredibly important item) and the pinpointer (only way of tracking the incredibly important item). If the Captain dies, there is no way to track the disk unless the captain has handed of the pin pointer somewhere.

**Comment by Gandalf2k15** [comment]
Makes little to no sense to move it, its like that everywhere. Just means some fag can steal it from the HoS's room, which has windows.

**Comment by Sarcalogo** [comment]
It's not like that on /tg/, they changed it months ago. Ideally the HoS would carry the pinpointer with him at round start. And the windows are from space, or they'd have to break in through the entire brig.

**Comment by trifornt-tinfornt** [comment]
This is stupid. The Captain is given the disk and the pinpointer for a reason. Why would the HoS get it when he doesn't have all-access or the disk?
The Captain should be the one responsible for the disk, and in case he somehow loses it, he can track it. The HoS wouldn't exactly need the pinpointer.

**Comment by JohnGinnane** [comment]
I disagree trifornt, it makes sense if the disk is in one location, and the pin pointer is in another. It makes rushing Cap's office a little less effective because the pin pointer can still be used to locate the disk.

**Comment by Kokojos** [comment]
I agree with this PR

**Comment by Nebyab** [comment]
nah

**Comment by McBawbaggings** [comment]
This is currently sitting at 2 headmin disapproval

**Pull request closed without merging**
