### PR TITLE
Saxophones no longer honk when you move on top of them

### PR DESCRIPTION
**Pull request by Spacedong**
bugfiks

### CODE REVIEW

**Comment by JohnGinnane** [comment]
This is the way to do this. You should just set the on cross proc to return

**Comment by McBawbaggings** [comment]
What John said.

**Comment by JohnGinnane** [comment]
https://github.com/Spacedong/HippieStation13/blob/32dd8210bda3fda8203a98f7ede6154e09efd48a/code/game/objects/items/weapons/clown_items.dm#L49

**Comment by Spacedong** [comment]
done

**Comment by SpankMasterson** [comment]
+1 if it works

**Comment by JohnGinnane** [comment]
Merging as it's bug fix and code looks good

**Pull request merged**
