### PR TITLE
Adds 5 new AI Lawsets

### PR DESCRIPTION
**Pull request by Sarcalogo**
1. Hippocratic, based on the HIppocratic Oath.
2. Drone, which is basically the drone lawset applied to the AI.
3. Golden Rule, you should know what this is without me explaining it to you.
4. Reportertron, a lawset prioritizing reporting what is happening around the station like a journalist out for a scoop.
5. M.A.G.A, single law lawset "Make Space Station 13 great again!"

Basically a port from /tg/, except I changed the wording substantially on Hippocratic and Golden Rule while adding an exclamation point to M.A.G.A

### CODE REVIEW

**Comment by McBawbaggings** [comment]
Hippocratic is wordy af
Drone is pretty much impossible to follow and not fun
Golden rule is okay on paper, bad in practice.
CCTV would work better as a supplementary law than a lawset, also: Embellish or conceal the truth as necessary to make the reports more interesting. (and ) Issue your reports fairly to all. The truth will set them free. These sorta contradict?
Trump laws are begging to be shittered with.

**Comment by Sarcalogo** [comment]
Also, I'm not sure where to put the modules on the map, just need someone to confirm more or less.

Hippocratic = Safe
Drone = Safe
Golden = Safe
Reporter = Safe
M.A.G.A = High Risk

**Comment by Sarcalogo** [comment]
Okay. I cut down all of the words I could from the HIppocratic Oath. It's the actual translated oath from Wikipedia is what I used, and I cut down all I could.

Drone isn't impossible to follow at all, if drones can do it, why can't AI/Borgs do it? That being said, if you think people will add it to the AI to "griff them" it can be one of those modules that is research only, like TYRANT. Anyone with access to AI upload could purge and add a kill yourself law too.

Don't really agree with you on the CCTV thing, oh well. As for the contradictions, I guess in some sense you could be right, but I didn't devise the law set. If it's a big deal I can just delete the "truth will set you free" from the last law.

Trump laws is begging to be shittered with is kind of the point... like antimov and stuff. It's in the high risk modules area for a reason.

**Comment by McBawbaggings** [comment]
Borgs can follow drones, but the AI is just like an observer without deadchat.

**Comment by Sarcalogo** [comment]
Anyway, so this is what I plan based on what you said.

Hippocratic: Stays in added to map.
Drone: Added to R&D but potentially commented out.
Golden Rule: Stays in, probably added to the map. Could potentially add a second law to this law set making it less vague.
Reporter: Dunno.
Trump: Added and put under high risk modules, anything bad happens blame it on who uploaded it. 

I think if people try to act funny with the Golden Rule, by pretending they want to be killed or something they should just be banned, much like you'd ban someone for killing the whole crew under paladin because "evil is subjective man".

**Comment by Voratius** [comment]
"Treat others as you would want them to treat you" how is that safe exactly?

**Comment by calibraptor** [comment]
No thanks.

**Comment by Sarcalogo** [comment]
Because most people don't want to be treated like shit?

**Comment by McBawbaggings** [comment]
Those are huge implications

**Comment by Sarcalogo** [comment]
Not sure what you mean. Do you mean the AI will pretend to be a 1/10000000 masochist to get valids? What's to stop me from pretending that I think evil is good and good is evil while on paladin? Or any other subjective lawset? 

It's...you.

**Comment by Kokojos** [comment]
The only interesting one in all of these is the reporter one, so a no from me.

**Comment by Nebyab** [comment]
Hippocratic is dumb in this context
Drone is just a bad idea for the ai
Golden rule is dumb as an ai law
CCTV is amusing as a one off gimmick at best
the trump law is literally just a meme


was this merged on tg? if so how?!?

**Comment by calibraptor** [comment]
@Nebyab Who told you this was merged on tg?

**Comment by Sarcalogo** [comment]
It was merged on /tg/. But I guess I can close it considering that's 2 nos.

https://github.com/tgstation/tgstation/pull/16050

**Pull request closed without merging**
