### PR TITLE
Space Revolvers

### PR DESCRIPTION
**Pull request by Kierany9**
- Removes all .357 revolvers in space.
- Space russians now exclusively carry Mosins.
- Melee Space Russians carry combat knives instead of kitchen knives.
- Replaced the .357 in the derelict's detective office with a .38(detective's revolver)
- Replaced the gamma spaceship's three revolvers with a glock, a spare magazine and fake adrenal implants

- Added fake adrenal implants. These have a random chance of exploding(gibbing you), injecting you with cyanide and chloral, injecting you with water, injecting you with ephedrine and tricord while reducing your current stuns by 4 ticks and working like real adrenals. They have 2-4 uses, and if you and try and use them once they're depleted, you will explode.

no seriously whose fucking idea was it to litter space with 13 TC traitor items?

### CODE REVIEW

**Comment by ArcLumin** [comment]
Less guns in space is always good

**Comment by Gandalf2k15** [comment]
Literally no.

**Comment by Gandalf2k15** [comment]
What you are doing here is literally removing all reason to explore space. These guns are usually only ever found by non-antags that want to explore space, dont remove all reason to do so.

**Comment by Spacedong** [comment]
how about we port in some actual loot instead of just the same gun copypasted over and over

**Comment by Pyko1** [comment]
Since we dont have telescience anymore i think guns in space are fine, but there should be minimal amount of antag items due to jelly validhunters that are goign to kill you for spess exploration just because they can since its herp antag item derp.

**Comment by Kierany9** [comment]
>What you are doing here is literally removing all reason to explore space.

I've removed three guns from a template that has around a 20% chance to spawn *because it was accessible from rounstart thanks to the teleporter*, and because they're the equivalent of a 13 TC traitor item that crits in two shots. The other gun that I've removed has been replaced with one equally if not more viable for non antag self defense.

What the hell do you mean I've 'removed all reason to explore space'.

**Comment by banthebantz** [comment]
If they're replaced with good shit then I'm happy.

**Comment by Spacedong** [comment]
also fuck you gandalf its been fucking month and that stupid gamma shit is still accessible from teleporter, allowing you to get fucking invincible shit

**Comment by GeneralGoose** [comment]
@Gandalf2k15 >reasons to explore space

you mean to open the map in the editor, pinpoint where the guns are and then speedrun getting them in 2 minutes, then fucking off back to station?

**Comment by Spacedong** [comment]
@generalgoose doesn't work because map isn't static

**Comment by Spacedong** [comment]
and telescience was removed

**Comment by Spacedong** [comment]
we just need MORE space locations and MORE space loot

**Comment by Spacedong** [comment]
look at /tg/'s space ruins system, its unique and has lots of original assets, too bad none of us can sprite

**Comment by GeneralGoose** [comment]
still its not exploring
you just find guns and go back

**Comment by Spacedong** [comment]
exactly we need original _ideas_

**Comment by GeneralGoose** [comment]
yeah, i said it before, need more loot that isn't guns or anything like that

**Comment by Pyko1** [comment]
we need clowncar and such as spessloot

**Comment by Spacedong** [comment]
or just have it as a traitor item

**Comment by Spacedong** [comment]
seriously we need secret stuff, dont make changelogs for this stuff

**Comment by GeneralGoose** [comment]
also goon had some fun space things to explore and some relic crown of satan or something

**Comment by Pyko1** [comment]
aka annoying shit that does not remove people from round.

And clowncar should be annoying but not deadly and not traitorous.
Ie. Back on Nox clowns used to steal all lockers/shoes with their clown cars unlimited container space.

**Comment by Spacedong** [comment]
@GeneralGoose can you add me on steam

**Comment by ArcLumin** [comment]
I'd love a fast vehicle with unlimited container space

**Comment by GeneralGoose** [comment]
yeah clown car is funny and it's clown so extra points for that

@Spacedong k whats your steam

**Comment by Spacedong** [comment]
blute

**Comment by Mithrandalf** [comment]
God I hate all these spaceguns,

Why were they even added in the first place?

Glock is a fair spacegun, revolver is fucking not.

**Comment by Gandalf2k15** [comment]
Glock is another traitor item. Goes against policy. Make it a 1911 or something less traitory.

**Comment by Kokojos** [comment]
Remove +1/3

**Comment by Lawligagger** [comment]
sounds good hombre

**Comment by calibraptor** [comment]
Gandalf is against this PR, which mean I'm obligated to be for it.

+1/3rd

**Comment by McBawbaggings** [comment]
"Goes against policy."
Since when was traitor items off of the station completely forbidden?
Just don't put syndie items on station.

**Comment by Pyko1** [comment]
We did clean all syndie items from space jsut a while a go....
We as in Chron, and while a go as in last year.

**Comment by kkkkkkkr** [comment]
Ahaha, what the fuck? Are you serious? almost nobody is actively using them or searching for them at all, they make upf or fun gameplay moments and you're ruining it by removing them, space and maint are boring enough

**Comment by Mithrandalf** [comment]
Gandalf please dont make alts.

Spaceguns are bad mkay.

**Comment by GeneralGoose** [comment]
lol

**Comment by SplergeBucket** [comment]
yeah man fuck revolvers in space
make creative z-levels and rewards, and remove telescience already outside the station or mining its SHIT
SHIT I TELL YOU
or randomise the coordinates but that aint gunna work

**Comment by Kierany9** [comment]
Do you know how long it's been since telescience was removed?

**Comment by McBawbaggings** [comment]
not long enough

**Comment by Mithrandalf** [comment]
What about random loot slots like in maint?

**Comment by SplergeBucket** [comment]
telescience is dead?
fuck yeah
randomise this loot
the revolver is bullshit since it can become reloadable
there should be good stuff you have to ration out

**Comment by Spacedong** [comment]
telescience has been dead for fuckin months. maybe even a full year

**Comment by SplergeBucket** [comment]
oh right i was there for when it was removed

**Comment by SplergeBucket** [comment]
this really puts things into perspectives

**Comment by SplergeBucket** [comment]
BRING BACK TELESCIENCE

**Comment by McBawbaggings** [comment]
KEEP TELESCIENCE DEAD

**Comment by TDcoolguy300** [comment]
NO

**Comment by trifornt-tinfornt** [comment]
Of course Gandalf complains that his precious two-hit-kill .357s he can find in space (that he totally doesn't abuse whenever he gets antag I swear) might get revolved.
Gamma Derelict literally has 3 .357 revolvers in it that you can get as early as roundstart. That's not clever, that's not good balance, that's not something that's gonna make people "explore", it's just giving powergamers and murderboners even better ability to kill people.

**Comment by blobbernaut** [comment]
The fake adrenal implant idea is terrible. Replace it with a regular adrenal implant or something neat like an emag or a storage implant.

**Comment by trifornt-tinfornt** [comment]
Storage Implants are still 8 TC.
Emags are devices that, if in the proper hands, can wreak borg hell on the station.

Just remove the implants.

**Comment by GeneralGoose** [comment]
@trifornt-tinfornt pretty much what i said

btw you can replace that retarded implant that gibs you with some rnd implant, like revival implant or anti-knockdown implant

**Comment by IvanTheCracka** [comment]
MOSINS?  How about go fugg yourself? That gun is close to useless and has limited as fuck ammunition (the autolathe prints rubberbullets for it).  A better nerf would be :

A: Change it for a shittier gun.  Dont want to add a tator item like the Stetch or the Glock?  Then make another gun,  steal the sprite from another codebase and just make it use 9mm or 10mm

B: Code a .357 lever action carbine,  has to be pumped after each shot which takes some time,  cannot be stored in a backpack unless sawed off,  which increases pump time significantly

**Comment by ArcLumin** [comment]
Mosins should be a 1 TC traitor item

**Comment by Kokojos** [comment]
This has been accepted and code is good.

**Comment by blobbernaut** [comment]
I hate this PR a lot

**Pull request merged**
