### PR TITLE
Gang tags only on walls

### PR DESCRIPTION
**Pull request by Pyko1**
Allows gangs tags only to be sprayed on walls.

Fixes https://github.com/HippieStationCode/HippieStation13/issues/1886

### CODE REVIEW

**Comment by Cherkir** [comment]
is this actually a problem or just muh immershuns stuff

**Comment by Carbonhell** [comment]
Code's ok

**Comment by Nokington** [comment]
Sure as long as it doesn't break shit

**Comment by Nebyab** [comment]
I'm not convinced that this is something that really needs to be altered. So gang signs can be occluded, that's simply clever play from my perspective.

**Comment by Pyko1** [comment]
They cant be covered, they are still very much above the lockers, the PR to make them layer 2.9 was closed, not merged.

**Comment by Spacedong** [comment]
its impossible to tag the holodeck with this update because its surrounded by windows only and theres no walls

**Comment by nalarmg** [comment]
Needs further head input.

**Comment by Nokington** [comment]
Ive changed my mind on this. This might not be a good thing to do

**Comment by Carbonhell** [comment]
Both headmins are doubtful about this pr. Closing this PR

**Pull request closed without merging**
