### PR TITLE
Fixes cloaks so you can adjust them

### PR DESCRIPTION
**Pull request by blobbernaut**
Fixes cloaks so they can be adjusted, also fixes the captain's gloves not having a sprite. 

Both of these are just bugfixes.

### CODE REVIEW

**Comment by McBawbaggings** [comment]
Changelog please my dude.

**Comment by blobbernaut** [comment]
changeloggo

**Comment by banthebantz** [comment]
Changelog or I will summon carbonhell himself.

**Comment by blobbernaut** [comment]
[HippieStationCode/HippieStation13] New comment by banthebantz on pull request #2860: Fixes cloaks so you can adjust them

Changelog or I will summon carbonhell himself.

**Comment by blobbernaut** [comment]
!!!!!!!!!!!!!!!!!! it's there!!!!!!!!!!!!!!!!!

**Comment by blobbernaut** [comment]
If you have questions about the code, ask. I'd like this merged.

**Comment by SplergeBucket** [comment]
should be merged no?

**Comment by TDcoolguy300** [comment]
Code looks fine.

**Pull request merged**
