### PR TITLE
Last Resort no longer blows off limbs

### PR DESCRIPTION
**Pull request by blobbernaut**
This was a completely unintended buff that occurred as a result of dismemberment code having a chance to remove limbs with explosions. 

instead of having an explosion and a weak stun if the explosion fails (not likely. 15% chance to be capable of fighting after the explosion ATM.) the stun has been changed to a moderate paralyze and the dizziness has been increased.

This ability should be an escape tool, not a completely viable murder weapon.

Fixes https://github.com/HippieStationCode/HippieStation13/issues/2305

### CODE REVIEW

**Comment by calibraptor** [comment]
:+1:

**Comment by Kokojos** [comment]
Sure!

**Comment by JohnGinnane** [comment]
Code looks good

**Comment by Sarcalogo** [comment]
Yeah good job. Now the next step is to remove last resort as a round start ability,

**Comment by Nebyab** [comment]
ok

**Comment by Sarcalogo** [comment]
Pretty sure this conflicts with the recently merged removing of headslugs thing. May want to close it?

**Comment by McBawbaggings** [comment]
It was kinda funny but yeah sure. +1

**Comment by Kokojos** [comment]
It's ready to merge, but currently won't affect the code as the file is ignored in the .dme

**Comment by McBawbaggings** [comment]
I guess I'll merge???

**Pull request merged**
