### PR TITLE
NukeOP Reinforcements

### PR DESCRIPTION
**Pull request by Pyko1**
Increased the cost to call nukeops reinforcements from 25 to 35.

When you summon the reinforcements you get to choose what gear they have.

Assault
```
/datum/outfit/syndicate/no_crystals/assault
	name = "Syndicate Operative - Assault"
	suit =	/obj/item/clothing/suit/space/hardsuit/syndi/elite
	r_hand = /obj/item/weapon/gun/projectile/automatic/shotgun/bulldog
	backpack_contents = list(/obj/item/weapon/storage/box/engineer=1,\
		/obj/item/ammo_box/magazine/m12g/buckshot=1,\
		/obj/item/ammo_box/magazine/m12g=1,\
		/obj/item/ammo_box/magazine/m12g/stun=1,\
		/obj/item/ammo_box/magazine/m12g/dragon=1)
```

Medical
```
/datum/outfit/syndicate/no_crystals/medical
	name = "Syndicate Operative - Medical"
	suit =	/obj/item/clothing/suit/space/syndicate/black/red
	head = /obj/item/clothing/head/helmet/space/syndicate/black/red
	r_hand = /obj/item/weapon/gun/medbeam
	l_hand = /obj/item/weapon/gun/projectile/automatic/l6_saw/toy
	backpack_contents = list(/obj/item/weapon/storage/box/engineer=1,\
		/obj/item/clothing/shoes/magboots/syndie=1,\
		/obj/item/ammo_box/foambox/riot=1)
```

Hacker
```
/datum/outfit/syndicate/no_crystals/hacker
	name = "Syndicate Operative - Hacker"
	suit =	/obj/item/clothing/suit/space/syndicate/black/red
	head = /obj/item/clothing/head/helmet/space/syndicate/black/red
	l_pocket = /obj/item/device/multitool/ai_detect
	backpack_contents = list(/obj/item/weapon/storage/box/engineer=1,\
		/obj/item/weapon/aiModule/syndicate=1,\
		/obj/item/weapon/card/emag=1,\
		/obj/item/device/encryptionkey/binary=1,\
		/obj/item/ammo_box/magazine/m10mm=1,\
		/obj/item/ammo_box/magazine/m10mm=1,\
		/obj/item/weapon/c4=1)
```

Infiltrator
```
/datum/outfit/syndicate/no_crystals/infiltrator
	name = "Syndicate Operative - Infiltrator"
	suit =	/obj/item/clothing/suit/space/syndicate/black/red
	head = /obj/item/clothing/head/helmet/space/syndicate/black/red
	uniform = /obj/item/clothing/under/chameleon
	shoes = /obj/item/clothing/shoes/sneakers/syndigaloshes
	mask = /obj/item/clothing/mask/gas/voice
	gloves = /obj/item/clothing/gloves/color/yellow
	belt = /obj/item/weapon/storage/belt/utility/full
	backpack_contents = list(/obj/item/weapon/storage/box/engineer=1,\
		/obj/item/weapon/gun/energy/kinetic_accelerator/crossbow=1,\
		/obj/item/weapon/gun/projectile/automatic/pistol=1,\
		/obj/item/ammo_box/magazine/m10mm=1,\
		/obj/item/weapon/card/id/syndicate=1)
```

Medic/assault are syndicate bundles and extra items that would normally cost 21 TC.
The hacker and infiltrator sets are actually a bit more expensive as there was no bundle to start with, but I personally feel they are more or less in the line with others if not even weaker.
Half tempted to make it 40 TC, but that is starting to be too close to syndicate borg price.

"Fixes" https://github.com/HippieStationCode/HippieStation13/issues/1934

### CODE REVIEW

**Comment by McHatters** [comment]
This is a good idea, as syndicate reinforcements have to rely on the TC scraps that the other nukies have in order to buy anything worthwhile, if at all.

**Comment by Carbonhell** [comment]
Code needs fixing,already told pyko what to fix

**Comment by Nokington** [comment]
Sure

**Comment by Nebyab** [comment]
Get the code working and i'm cool with it

**Comment by Pyko1** [comment]
So yeah, the code should be fixed.

**Pull request merged**
