### PR TITLE
Adds Research Outpost [50% Done]

### PR DESCRIPTION
**Pull request by Sarcalogo**
This is a concept stolen from /vg/station, where the outpost is supposed to be used for doing xenorchaeology, the recovery and study of alien artifacts on the mining asteroid. We don't have that here, but I always liked the research outpost so I felt I may as well add something similar here. You get there by taking a shuttle from Science or by walking north for a long time from the mining asteroid area. Basically it's like the mining station except full of stuff.you can "experiment" with. Right now I have:

- break room
- bathroom
- two dorms
- two maintenance storage rooms
- mini chemistry
- mini botany
- power/atmos room
- EVA
- barricaded empty room (meant to eventually house RND, Scientists have to rebuild it)
- two empty rooms

I'm not sure what to put in the two empty rooms, and need feedback on that.  

There are also the gameplay issues. I want to disincentivize people from fucking off there every round, I have my own thoughts on that but tell me what you think.

Also this is nowhere near done, I have the basic shape and "rooms" made, but the wiring, atmos, and filling of the rooms is not complete at all.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Two questions:

1. Did you use the map merge tool?
2. Do you have any screenshots of the outpost?

**Comment by Sarcalogo** [comment]
This is what its modeled after. 

https://img.fireden.net/vg/image/1459/78/1459786377824.png

Nah didn't use the Map Merge tool because I figure nobody would make any changes to Z5.

**Comment by JohnGinnane** [comment]
What if you added some (strong) hostile mobs in there to give the impression the outpost was overrun? That way scientists need to gear up to fight them before running off at the start of the round

**Comment by Carbonhell** [comment]
It's a research outpost, it's not meant to be abandoned. Rather,make it heavily dependant on the main station,for example by making the atmos outpost spawn with no canisters and they must be moved from the station to the outpost. Same for power?Iunno. Also, do you have any plan on what might be there?I don't think xenoarcheology could fit anyhow on our server due to it being fast paced and the rounds being short,so.

**Comment by JohnGinnane** [comment]
Removing atmos and power sounds great. Would mean you need to spend 15 minutes or so setting it up, e.g. hook up cannisters, make sure atmos is running, probably need to bring some powered batteries and then wire solars or however its powered

**Comment by Probe1** [comment]
Here's the final of my Defficiency Research Outpost rework fwiw 
[Deff Outpost](https://cloud.githubusercontent.com/assets/8550416/14263932/7b3b5252-fa8b-11e5-86e4-a9ad0e5320ac.png)

Some finer points:  There's an ore loader outside so if a miner finds themselves way on the other side of the map they can unload there and it will be sent straight through to the mining outposts smelter.  Players can also use it to quickly get from the research outpost to the mining outpost but they'll have to break through windows to escape.

Made sure antagonists/dumb dirty assistants can break in.

Made sure research botanists can use the lids on hydroponic trays to prevent dangerous gasses from entering the room.  Optional bottling with a canister or venting to space.

The break room in the center has those two lined up doors so it's a straight shot right from the shuttle to the roid.

**Comment by Carbonhell** [comment]
What codebase are you using?We don't have baystation xenoarcheology machinery

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13

We forked from Baystation just about 3 years ago now.

**Comment by SplergeBucket** [comment]
ye the research outpost shouldnt be an abandoned shithole
unless the headmins say no on it
then make it an abandoned overrun shithole

**Comment by banthebantz** [comment]
yes

**Comment by doobiedoo23** [comment]
:+1: once this is ready to merge

**Comment by Gandalf2k15** [comment]
Quick and probably stupid question, how do you get to the outpost?

**Comment by Nokington** [comment]
What gandalf said and I would rather it be functional if possible

**Comment by Sarcalogo** [comment]
I'll finish it later.

**Comment by Sarcalogo** [comment]
Made some progress..

**Comment by Gandalf2k15** [comment]
Again how do you get to the outpost?

**Comment by Sarcalogo** [comment]
Through a shuttle. Just like how you get to mining. The shuttle is typically in Science, but I may move it somewhere else because of space issues.

**Comment by Carbonhell** [comment]
Any update?

**Comment by Sarcalogo** [comment]
I stopped working on it when I saw someone was working on something remarkably similar. They changed what they are doing so I can start back up again.. I'll probably.... finish it in this order.

1. Fill in all the rooms. 
2. Lighting and wiring.
3. Fixing the "areas"
4. Atmos.
5. Touching up, making it look prettier and some finalizations.

Mapping takes a long time to do and is a pain in the ass.

**Comment by Sarcalogo** [comment]
I'm not a great mapper. As far as I am concerned the place looks a bit too empty. Most of the rooms are complete, just have to finish Xenobiology. Now is the time to criticize and tell me what to add, remove, move around.

Alt Text
Alt Text
Alt Text
Alt Text

**Comment by Sarcalogo** [comment]
Also in terms of floor tiles, haven't even touched that asides from RND it's not going to just be white all over.

**Comment by Gandalf2k15** [comment]
Perhaps add some buttons to control things. And there is a lack of air alarms and andue firealarms. You should add some different types of doors too. Not a fan of the bottom left hand corner setup
..

**Comment by Gandalf2k15** [comment]
Needs maint areas toi

**Comment by Sarcalogo** [comment]
Yep. Air alarms, fire alarms, APC's etc are all not added in yet because I have to add new areas and I don't feel like doing that at the moment. Doors are also place holders because I don't feel like editing access on the different kinds of doors yet.

 Not doing maintenance areas, original research station didn't have any. 

As for the bottom left corner, just gotta be more specific as to what you dislike about it.

**Comment by Sarcalogo** [comment]
Anyway I'll probably make a lot of progress today (tomorrow) will sort the "areas" out and try to do the wiring and adding of all APCs. but I'm going to sleep now so..

**Comment by Gandalf2k15** [comment]
It's the corner. Where the sink is.

**Comment by Sarcalogo** [comment]
So at this point what needs to be done is:

Finishing touches on Xenobiology
Piping Atmos and adding air alarms
Piping two disposal chutes
Floor tile design changes for some of the rooms
Implementing shuttle

And that's that.

**Comment by carlarc** [comment]
Make the shuttle have some supplies that aren't completely fucking useless (I'm looking at you teleporter room)

**Comment by TDcoolguy300** [comment]
500% done or nothing

**Comment by Nokington** [comment]
any progress?

**Comment by Uqualm** [comment]
I'm a dummy. I'm about 90 percent done. Will make a new PR soon but have to close this because map merge silliness. Will open a new PR very soon.

**Comment by Sarcalogo** [comment]
Yep... Uqualm is right. Almost done...

**Pull request closed without merging**
