### PR TITLE
Stand Arrow 3: Fuck Spacedong

### PR DESCRIPTION
**Pull request by yobob591**
Arrow now has lower killchance but spawns from meteor events which are rare af

### CODE REVIEW

**Comment by MethMedic** [comment]
Yea. Spite spacedong and his garbage code

**Comment by MethMedic** [comment]
Spacedong? More like spaceDONT

**Comment by Anderbergst** [comment]
yea this is good

**Comment by Swagile** [comment]
needs code review first

**Comment by McBawbaggings** [comment]
Changelog is .txt
Needs to be .yml

**Comment by yobob591** [comment]
I am a supper reatard

**Comment by gumner** [comment]
it wont ever be used on meteor events though

**Comment by gumner** [comment]
i mean no one will go and try to find it on meteor event

**Comment by yobob591** [comment]
I could buff meteor events to make them more common

**Comment by gumner** [comment]
uhhh im not 100% sure,just make the arrow meteor another event apart from normal meteors

**Comment by oprayx77** [comment]
meteors are the worst fucking event and the sad part is now arrows are loped into them
RIP

**Comment by asskek** [comment]
i like this
now the stand arrow will never be used
just as planned
>:)

**Comment by asskek** [comment]
fuck

**Comment by asskek** [comment]
i mean to do
>>:)

**Comment by Spacedong** [comment]
lmao

**Comment by asskek** [comment]
DAMN IT
(>:))

**Comment by yobob591** [comment]
suffer

**Comment by oprayx77** [comment]
grudgecode is real

**Comment by yobob591** [comment]
i robusted his grudgecode by making it stronger

**Comment by McBawbaggings** [comment]
Remove the chance from the normal storm.
Then it should hopefully be rare enough so when it does happen, it's really fucking cool.

**Comment by yobob591** [comment]
no longer works on playerless mobs or guardians cause mcnigger hates fun

**Comment by McBawbaggings** [comment]
Come on now, we're nerfing the kill chance for more stand users.
A station full of stand users should be a rare but _fun_ occurrence.

**Comment by yobob591** [comment]
sure :^)

**Comment by McBawbaggings** [comment]
Yeah sure +1
20% chance to die seems fair considering how rare this will be (hopefully)

**Comment by MethMedic** [comment]
Ill make sure to spam meteors

**Comment by yobob591** [comment]
👌

**Comment by Hackole** [comment]
I'm fine with this +1

**Comment by yobob591** [comment]
mergg

**Comment by Sarcalogo** [comment]
More like fuck Yobob. Fuck off Jojofags, this is a game about Space, not fucking JoJo. You have enough fucking JoJo references already. So fuck off.

**Comment by yobob591** [comment]
dragon dildos/farting your ass off

sure

**Comment by Spacedong** [comment]
GOODBYE JOJO

**Comment by yobob591** [comment]
iS thIs a JoJo ReFrEnCe

**Comment by Spacedong** [comment]
@yobob591 can you make it drop something other than the arrow? preferably space dust or something?

**Comment by Spacedong** [comment]
or some iron ore idk

**Comment by yobob591** [comment]
there are already meteor drops that drop that shit

**Comment by Spacedong** [comment]
no, I mean, all this meteor would do would spawn a stand arrow, is it not made of rock and dust and shit? it should spawn debris along with the arrow.

**Comment by yobob591** [comment]
good point, but i mean it doesnt do that when meteors drop other shit, that sounds like something that should be added to the base meteor code not part of dis PR. Also this is ready to be merged already

**Comment by Spacedong** [comment]
k

**Comment by yobob591** [comment]
I may even make it so the meteor drops a shard and you have to CRAFT the arrow in the future, which would be cool, but for now this is good

**Comment by KittyKathy** [comment]
Nah you forgot one thing, you can use the stand arrow on dead mobs which means you can give a dead mob a stand which instantly gibs them when they get the stand.
Does this spawn on meaty ore events where meatballs assault the station?

**Comment by yobob591** [comment]
1. It checks for living, the problem was the delay that was gibbing

2. no only real meteors

**Comment by KittyKathy** [comment]
Oh okay that makes sense I remember I used to be able to spam the mining mobs with the arrow to gib them and get a second loot drop from them.

**Comment by yobob591** [comment]
ready to mergg

**Comment by banthebantz** [comment]
tunguska meteor plox

**Comment by yobob591** [comment]
it already habbens its just extraordinarily rare

**Comment by ArcLumin** [comment]
Code looks good to me. Gonna merge as it's got head okays

**Pull request merged**
