### PR TITLE
Removes the insanely slow delay on manifesting as a guardian.

### PR DESCRIPTION
**Pull request by Spacedong**
Fixes issue #2609. Your camera is no longer laggy when trying to recall to your host as a guardian. I've removed the retarded recall/manifest delay as well.

### CODE REVIEW

**Comment by dreamcrab** [comment]
yesss +777777777777

**Comment by JohnGinnane** [comment]
Code change looks simple enough. Have you tested it locally? I think we should maybe hold off on merging this for a day to get others' opinion

**Comment by trifornt-tinfornt** [comment]
Bring back the ghost sprite too.

**Comment by McBawbaggings** [comment]
As cool as the ghosts are, I feel the holoparasites fit SS13's them a hellva lot better. It's like sci-fi jojo and it's really cool.

**Comment by Gandalf2k15** [comment]
Merging as has head approval.

**Pull request merged**
