### PR TITLE
Moderator rank

### PR DESCRIPTION
**Pull request by blobbernaut**
Gives the moderator rank the ability to ban. 

Moderators have access to basic admin permissions, such as admin chat, but cannot spawn things or var edit things, so they're less able to screw around than a trial admin. Would be good for late night when sometimes there's no/few admins without having to grant somebody permission to dangerous stuff like the ability to spawn supermatters and heal themselves and whatnot.

### CODE REVIEW

**Comment by doobiedoo23** [comment]
why are mods necessary

**Comment by Limed00d** [comment]
what

**Comment by blobbernaut** [comment]
well they were already in the config just we don't use it.

It's intended so that if there's no admins on somebody can just hop on and promote a mentor or something without having to worry about shitty events or power tripping taking place.

**Comment by Nokington** [comment]
w h a t

**Comment by doobiedoo23** [comment]
are you just doing this so we can give you mod

**Comment by blobbernaut** [comment]
it was already a rank on the config but it wasn't worth using because they didn't have +BAN 

you don't have to go out and create a bunch of moderators if you don't want to

**Comment by Nokington** [comment]
yeah no we have never used mods and i dont think we ever will

**Comment by Nokington** [comment]
http://puu.sh/oy1vL/f91bbc6b93.png what in the fuck

**Comment by Nokington** [comment]
this is the dumbest pr i have ever seen

**Comment by doobiedoo23** [comment]
amazing

**Comment by blobbernaut** [comment]
the @ sign means it takes the access from everything above it......... trial admins and everybody below them still have +BAN

**Comment by Nokington** [comment]
wew lad

**Comment by blobbernaut** [comment]
hey it says that right in the file.....

**Comment by blobbernaut** [comment]
there's literally nothing wrong with this it doesn't change anything except make a moderator rank easier to use

**Comment by doobiedoo23** [comment]
we don't use mod

**Comment by Pyko1** [comment]
In my opinion trial min should be mods with just +ban, if its meant to evaluate how they handle things, then make the current trialmins somethign like Junior Admin before GA, to see if they can handle extra shit.

if trialmins aka mods have only +ban they don't need as much monitoring.
also carbon wanted me to tell all of you that he is gay and that

```
Carbonhell [11:19 PM] 
Can you write in that PR that if it gets merged it needs nalar.to edit the config
Seems like it edits the config
```

**Comment by Pyko1** [comment]
also no point in denying this in middle of discussion as this has merits.

or at least as far as I know current trialmins need a lot of baby handling.

**Comment by Nokington** [comment]
Yes this is something that would need to be changed in the config, this PR would do nothing as far as I know. http://puu.sh/oy27q/3901e92fce.png

**Comment by Pyko1** [comment]
yeah but it servers as a prime place to talk possible changes tho releated to this matter, even if its not perfect as it is, just deny/close in 20 mins is bad, at least give it a chance for changes.

At least I can see some merit in some kind of test admin rank that cant pretty much edit everything if he knows the tricks to get around.

**Comment by blobbernaut** [comment]
the idea is creating a rank that doesn't start people off with the ability to spawn a singularity or the badmin payload or delete all the floor tiles on the entire station.

**Comment by Nokington** [comment]
http://puu.sh/oy2oZ/f7e722c7e2.png

Our ranks are fine as they currently are and if we wanted to change them we would bring them on the forums and in the admin discussion room

**Comment by Pyko1** [comment]
Or at least, the way I see the trialmin should be really the mod + ban, as current trialmins shoudl still be able to massmodify shit even they cant var edit it etc

**Comment by blobbernaut** [comment]
yeah but this doesn't even change the current ranks, it just makes the other one an option. You don't promote somebody to moderator, it doesn't change anything, trial admin permissions are still the same as they currently are.

wait what? Explain pyko?

**Comment by Pyko1** [comment]
cant var edit, mass modify used to work at least

**Comment by Pyko1** [comment]
basically what im saying they should oly have +ban and view vars on ahelpers or soem shit, basically block it to less than currently

**Comment by Pyko1** [comment]
at least I believe I can do tons of shit that might not be that intended as a trialmin, let aolne spawning and shit allowed to begin with.

**Comment by blobbernaut** [comment]
seems like nokington disagrees, i just thought this was an idea with no possible downside because it changes precisely nothing unless we decide to use moderator ranks

**Comment by Nokington** [comment]
It is literally useless to merge this. It will do absolutely nothing because this type of thing has to be changed in the config

**Comment by Pyko1** [comment]
My personal opinion is even if we keep denied, at least open it so its not buried so anyone on git can easily see it. for discussion, as it is its not really needed tho.

**Comment by lcass** [comment]
I remember multiple admins myself including mocking the moderator rank for it's sheer stupidity , the point in having a trialmin rank is to allow you to fuck up and learn how to admin , having a position below is only suitable on high RP because they mainly deal with either RP related issues or very minor inflictions.

**Comment by blobbernaut** [comment]
this PR

**Comment by Pyko1** [comment]
yeah but trialmins have quite a lot of power over the server, and they at least used to be able to get around varedit limits with massmodify, would be really better if they could stat with some babysit free rank where you pretty much jsut have to watch their chat. There is tons of shit a trialman can see without no one noticing it unless you go through all server logs line by line if we knows what to do.

**Pull request closed without merging**
