### PR TITLE
Removes the windows blocking the liberation stations from the front on Centcomm.

### PR DESCRIPTION
**Pull request by Spacedong**
Removes these useless tard windows so people can access them from all angles for more meme carnage slaughter fun. 

https://vgy.me/F73NyS.png

### CODE REVIEW

**Comment by Limed00d** [comment]
Sure why not

**Comment by Carbonhell** [comment]
mapwise it's fine, if another headmin okays it it's in

**Comment by Carbonhell** [comment]
@nebyab @nokington

**Comment by Kokojos** [comment]
No problem with the map this time.

**Comment by Nokington** [comment]
ok

**Comment by Spacedong** [comment]
2 headmins ok merge

**Comment by Pyko1** [comment]
merging, since spacedong seems to have bribed the headmins

**Pull request merged**
