### PR TITLE
Vampire bats no longer fly at the speed of light.

### PR DESCRIPTION
**Pull request by Spacedong**
wew lad they were on par with a person on adrenals bats aren't that fast

### CODE REVIEW

**Comment by trifornt-tinfornt** [comment]
also make turning into a bat to begin with actually take time as well as not being able to use it while you're unconscious.
vampires are just unbelievably annoying

**Comment by GuyonBroadway** [comment]
I like it when a vampire bat keeps getting beaten up and repeatedly changing. Reminds me of this https://youtu.be/2Gn4gVpLncA

**Comment by Spacedong** [comment]
i like that episode

**Comment by blobbernaut** [comment]
It's supposed to be a getaway mechanic. Now you change it so that they're not any faster than a person?

**Comment by Hackole** [comment]
It's sort of meant to be an escape-y thing, Why nerf it? It does what it's supposed to do

**Comment by trifornt-tinfornt** [comment]
Because you can use it in literally any situation. Even when you're literally unconscious.

**Comment by ArcLumin** [comment]
Code's good

**Comment by blobbernaut** [comment]
And now that vampire adrenal is being removed this should definitely not be merged without buffing them some other way.

**Comment by Swagile** [comment]
ehhhh

i dunno, their bat form is literally infinite last resort as long as they have blood; they CANNOT die because of this and if they know how to procure blood at high volumes they can keep spamming this infinitely in a rounds time

**Comment by McBawbaggings** [comment]
I'd honestly rather add a stun based on the percentage of HP lost as a bat.

**Comment by McBawbaggings** [comment]
Like when you transfrom from bat back into humie.

**Comment by Swagile** [comment]
GM + 1 if code checks out

**Comment by Dudeinyourbackyard** [comment]
yeah iunno about making them slower than humans, perhaps make them just slightly faster or what mcbaw suggested

**Comment by Pyko1** [comment]
more input needed

**Pull request closed without merging**
