### PR TITLE
The wardrobe locker in Chemistry now contains 2 standard biosuits

### PR DESCRIPTION
**Pull request by Spacedong**
weird, thought chemists always had these, guess not

### CODE REVIEW

**Comment by ArcLumin** [comment]
Code's fine

**Comment by McBawbaggings** [comment]
Ayy +1

**Comment by Dudeinyourbackyard** [comment]
yeah why not
+1

**Comment by Pyko1** [comment]
Hardly mapping if the map isnt even changed.

**Comment by ArcLumin** [comment]
Merging since head okays

**Pull request merged**
