### PR TITLE
Mapfix

### PR DESCRIPTION
**Pull request by Pyko1**
Fixed disposals buttons and moved things around the armory.
Added 2 barriers.
capture

Fixes: https://github.com/HippieStationCode/HippieStation13/issues/2003 https://github.com/HippieStationCode/HippieStation13/issues/2009

### CODE REVIEW

**Comment by Nebyab** [comment]
ok

**Comment by carlarc** [comment]
Much easier to get to the loyalty implants, A little harder for the lawyer to just run in and tase the warden. Though I'd like for the empty spot above to have a rack or a table or something.

**Comment by Pyko1** [comment]
I actually used to have rack there, but removed it since it made the corner table look shit.
A table could do, but getting over one or dismantling it can be a real pain in the ass with airflow, hence I decided to leave an empty spot if anyone wants to break in from space. Half tempted to move the table for same reason.

**Comment by carlarc** [comment]
thats kind of the reason for me to want it tho

**Comment by Nokington** [comment]
:+1:

**Pull request merged**
