### PR TITLE
its 7.62x54 not .762x54 you mong what the fuck are you smoking

### PR DESCRIPTION
**Pull request by Spacedong**

### CODE REVIEW

**Comment by McBawbaggings** [comment]
The most important PR

**Comment by McBawbaggings** [comment]
+1

**Comment by JohnGinnane** [comment]
Code is fine. Not sure we need a changelog for something this trivial?

**Comment by McBawbaggings** [comment]
Nah, I wouldn't say so.

**Comment by JohnGinnane** [comment]
Merging so

**Comment by ArcLumin** [comment]
Last time we said we didn't need a changelog or anything for something so trivial as typo fixes, spacedong turned all cats invisible

HAVE WE NOT LEARNED OUR LESSON?

**Comment by Spacedong** [comment]
all ammo and bullets are now invisible for maximum stealth opportunity

**Comment by JohnGinnane** [comment]
What do you mean Arc? I checked the code, it's literally two characters..

**Comment by ArcLumin** [comment]
More that the last time spacedong fixed typos shit turned invisible. Invisible dong strikes again.

**Pull request merged**
