### PR TITLE
Ragin' Space Ninjas

### PR DESCRIPTION
**Pull request by Kierany9**
i warned you bro

MEMORIES BROKEN THE TRUTH GOES UNSPOKEN I'VE EVEN FORGOTTEN MY NAME!

### CODE REVIEW

**Comment by banthebantz** [comment]
no one is ever going to do this.

**Comment by McBawbaggings** [comment]
+1 if you actually write a proper changelog

**Comment by asskek** [comment]
you know ninjas can move invisibly indefinitely, right?

**Comment by TheOneAndOnlyCreeperJoe** [comment]
Space Ninja is super snowflakey and will shit out runtimes if there's more than 2 ninjas at the same time.

When I'm saying the word "shit out", it's like an 80 year old man eating ten bags of Cheetos. He's going to be there for a few months.

**Comment by yobob591** [comment]
amazing tag, though it would be better to unfuck _one_ ninja first, they are already clunky buggy unbalanced etc

**Comment by Kierany9** [comment]
this now works

**Comment by McBawbaggings** [comment]
Oh, if it's gonna cause elods of runtimes then I'll refrain.

**Comment by SpankMasterson** [comment]
sure why not +1

**Comment by banthebantz** [comment]
Ninja code makes me want to die

**Comment by QuarianCommando** [comment]
Time to re-write ninjas?

**Comment by Kierany9** [comment]
non-space ninjas because i'm too lazy to code technobabble shit

**Comment by Dudeinyourbackyard** [comment]
jesus christ how terrifying
please no
-1

**Comment by QuarianCommando** [comment]
I mean, some of the code might be salvageable.

**Comment by gumner** [comment]
heh...this has 2 headmins +1's.... heh....heheh.........# SPESS NINJAS

**Comment by Pyko1** [comment]
+1 / -1 and one +1 refrain if lots of runtimes so better coding and try again?

**Comment by banthebantz** [comment]
Good luck recoding ninja, heh.

**Comment by QuarianCommando** [comment]
I'm doing it. I've been getting bored of all my other time wasting activities, so I'll just recode ninjas.

**Comment by banthebantz** [comment]
Well if you're doing that please make it so it doesn't have an entire module dedicated to it for snowflake reasons and try to condense it all down to just a few files as opposed to fucking dozens for the suit alone.

**Comment by QuarianCommando** [comment]
Stage one of my lengthy suicide note has been made into one of those in-progress PRs.

**Comment by ArcLumin** [comment]
Closing this until ninja gets reworks to make this viable

**Pull request closed without merging**
