### PR TITLE
Fixes riot armor slowdown.

### PR DESCRIPTION
**Pull request by Spacedong**
yeah lets not have hulks running around with 90% resistance to melee at top speed yes k thanks

### CODE REVIEW

**Comment by danhibiki** [comment]
You should definitely include a changelog entry for this.

**Comment by Pyko1** [comment]
Affects these issues: https://github.com/HippieStationCode/HippieStation13/issues/1824 https://github.com/HippieStationCode/HippieStation13/issues/1850
Enough to close em if this gets merged?

**Comment by Spacedong** [comment]
yeah it fixes the crusade armor by extension too but I'd still remove that from chaplain's locker since he basically gets riot armor for free anyway

**Comment by Nebyab** [comment]
ok

**Comment by danhibiki** [comment]
I'd be against removing the chaplains armor just on principle, especially now that it has a slowdown.

But if it wasn't implicit, yes. this update is good.

**Comment by Spacedong** [comment]
nah i didnt remove chaplain's armor I was just saying that its fixed and has slowdown anyway

**Comment by Nokington** [comment]
yeah as long as chaplains shit is fixed too
then yes

**Comment by Carbonhell** [comment]
3 heads ok and the code's good, merge..?

**Pull request merged**
